#!/usr/bin/env python3
"""Extract a decision-instant Lua fixture from a behav-dump timeline.

This is the LOCAL-VALIDATION half of the iteration loop (CLAUDE.md "Agent
iteration loop"): a bad decision is spotted at time T in a replay; this tool
freezes that instant — every hero's real position/HP/mana/level/team — plus the
GROUND TRUTH of what followed (per-enemy damage actually dealt to the subject
over the next window, and whether/when the subject died). The Lua fixture feeds
tests/mock/replay_fixture.lua, which rebuilds the world under the mock Bot API
so the REAL decision helpers (jmz_func) run on the REAL game state, and a unit
test asserts the fixed decision. No simulator involved.

Usage:
  python3 make_fixture.py <timeline.json> --t 309.5 --hero luna \
      -o tests/fixtures/f_071423_luna_chase.lua [--window 5]
"""
import argparse
import bisect
import json
import os
from collections import Counter, defaultdict

FULL = "npc_dota_hero_"


def bare(n):
    return n.replace(FULL, "")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("timeline")
    ap.add_argument("--t", type=float, required=True, help="decision instant (game-clock s)")
    ap.add_argument("--hero", required=True, help="subject hero, bare name (e.g. luna)")
    ap.add_argument("--window", type=float, default=5.0, help="ground-truth window after t")
    ap.add_argument("-o", "--out", required=True)
    args = ap.parse_args()

    tl = json.load(open(args.timeline))
    subj = FULL + args.hero

    # Keep only each hero's longest-lived entity idx (drops illusions — same
    # canonicalization as replayscope/build.py).
    life = defaultdict(Counter)
    for s in tl["snapshots"]:
        if "idx" in s:
            life[s["hero"]][s["idx"]] += 1
    canon = {h: c.most_common(1)[0][0] for h, c in life.items()}

    per = defaultdict(list)
    for s in tl["snapshots"]:
        if s["hero"] in canon and s.get("idx") != canon[s["hero"]]:
            continue
        per[s["hero"]].append(s)
    for h in per:
        per[h].sort(key=lambda s: s["t"])

    def at(h, t):
        arr = per[h]
        ts = [x["t"] for x in arr]
        j = bisect.bisect_right(ts, t) - 1
        return arr[max(j, 0)] if arr else None

    units = []
    for h in sorted(per):
        s = at(h, args.t)
        if s is None:
            continue
        hp_pct = s.get("hp_pct") or 0
        max_hp = int(round(s["hp"] / hp_pct)) if hp_pct > 0 and s.get("hp") else s.get("hp", 0)
        units.append({
            "name": h, "team": s["team"],
            "x": round(s["x"], 1), "y": round(s["y"], 1),
            "hp": s.get("hp", 0), "max_hp": max_hp,
            "mp": s.get("mp", 0), "max_mp": s.get("max_mp", 0),
            "level": s.get("level", 1), "alive": hp_pct > 0,
            # real inventory (slot-ordered, '' = empty) and TP cooldown, when the
            # dump carries them — lets fixtures exercise item decisions too.
            "items": [x for x in (s.get("items") or [])],
            "tp_cd": s.get("tp_cd", 0),
            # real ability state (name/level/cd remaining) — lets fixtures feed
            # FULL hero scripts (SkillsComplement), not just decision helpers.
            "abilities": [
                {"name": a.get("name", ""), "level": a.get("level", 0),
                 "cd": a.get("cd", 0)}
                for a in (s.get("abilities") or [])
            ],
        })
    assert any(u["name"] == subj for u in units), "subject %s not in timeline" % subj

    # Ground truth: per-enemy-hero damage actually dealt to the subject in
    # (t, t+window], and the subject's death time after t (if it died).
    burst = Counter()
    died_after = None
    for e in tl.get("events", []):
        if e.get("type") == "DAMAGE" and e.get("target") == subj \
                and e.get("actor_hero") and args.t < e["t"] <= args.t + args.window:
            burst[e["actor"]] += e["value"]
        if e.get("type") == "DEATH" and e.get("target") == subj and e["t"] >= args.t \
                and died_after is None:
            died_after = round(e["t"] - args.t, 1)

    game = os.path.basename(args.timeline).replace(".json", "")
    L = []
    L.append("-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.")
    L.append("-- %s @ t=%.1f (%d:%02d), subject %s." % (
        game, args.t, int(args.t // 60), int(args.t % 60), args.hero))
    L.append("-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the")
    L.append("-- following %.0fs; observed.died_after = seconds until the subject died (ground truth)." % args.window)
    L.append("return {")
    L.append("  game = '%s', time = %.1f, window = %.1f," % (game, args.t, args.window))
    L.append("  self = '%s'," % subj)
    L.append("  units = {")
    for u in units:
        items = ", ".join("'%s'" % i for i in u["items"])
        abil = ", ".join("{ name = '%s', level = %d, cd = %s }"
                         % (a["name"], a["level"], a["cd"]) for a in u["abilities"])
        L.append("    { name = '%s', team = %d, x = %.1f, y = %.1f, hp = %d, max_hp = %d,"
                 " mp = %d, max_mp = %d, level = %d, alive = %s, tp_cd = %s,"
                 " items = { %s },\n      abilities = { %s } }," % (
                     u["name"], u["team"], u["x"], u["y"], u["hp"], u["max_hp"],
                     u["mp"], u["max_mp"], u["level"], "true" if u["alive"] else "false",
                     u["tp_cd"], items, abil))
    L.append("  },")
    L.append("  observed = {")
    L.append("    burst = {")
    for actor, v in burst.most_common():
        L.append("      ['%s'] = %d," % (actor, v))
    L.append("    },")
    L.append("    died_after = %s," % (died_after if died_after is not None else "nil"))
    L.append("  },")
    L.append("}")
    open(args.out, "w").write("\n".join(L) + "\n")
    print("wrote %s  (units=%d, burst=%s, died_after=%s)" % (
        args.out, len(units), dict(burst), died_after))


if __name__ == "__main__":
    main()
