#!/usr/bin/env bash
# Mutation stand for tests/test_staytower_tower_ring.lua (test_set.md §FK).
#
# WHAT IT IS FOR. This round brings ONE CLAUSE across a call site. The gated half
# of the field-regen family (J.IsFieldRegenSituation) vetoes on
# `#bot:GetNearbyTowers( 1200, true ) > 0`, and its own comment says the clause
# exists so the lever does not cancel a bot's LOCAL back-off from a tower. The
# PROMOTED half (J.ShouldStayAndRegen, live in every turbo game) cancels the same
# retreat bid from ABOVE the whole guard chain and reads no building at all. The
# lever is that one veto, gated on 'staytower', on 12 frames of a 1012-frame
# corpus.
#
# The case has three halves and they forge differently:
#   (a) the BEHAVIOUR: a driven before/after on real frames plus a domain price,
#       both legs from the shipped predicate with one soak id toggled;
#   (b) ⭐ the TWO-COLUMN construction. The shipped predicate's last clause reads
#       GetGold(), which a .dem does not carry (GH #495), so through the mock's
#       scalar the flip set is EMPTY. The sweep drives the corpus twice (gold 0
#       and 200) and the suite asserts both columns, precisely so the zero cannot
#       be read as "the lever does nothing". Mutants M10-M12 attack that
#       construction rather than the lever;
#   (c) the PROVENANCE claim -- 1200 is quoted from a SHIPPED sibling, not tuned
#       here, so the quotation must be proven live in both directions. Move the
#       quoted number and the lever is untouched, still gated, still passing its
#       behaviour tests, and the FINDING is about something else.
#
# The shapes under test:
#   * THE LEVER LEAVES OR INVERTS (M1, M2, M4) -- the gate lands un-negated, the
#     block is deleted, or the veto fires where there is NO tower;
#   * ⭐ THE GATE STOPS BEING FIRST (M5) -- behaviourally identical in both
#     legs, and it destroys the only reason "un-armed this is byte-identical
#     shipped behaviour" is a fact rather than a sentence. The mutant that most
#     looks like a tidy-up;
#   * THE RADIUS STOPS BEING THE SIBLING'S (M3) or THE SIBLING'S OWN MOVES (M6)
#     -- the provenance claim, both directions;
#   * THE PREMISE MOVES (M7, M8) -- the shipped chase ring and band this lever
#     sits between are edited instead, so its domain silently becomes another
#     set while every assertion about the lever still passes;
#   * THE PULLCAD TRAP (M9) -- a second soak id joins the gate's condition;
#   * ⭐ THE TWO-COLUMN CONSTRUCTION COLLAPSES (M10) -- the gold override stops
#     taking, so the g200 column reads the g0 column's zero. This is the shape
#     the whole file exists to make impossible to publish;
#   * THE TOGGLE STOPS TOGGLING (M11) -- the armed leg is driven disarmed
#     (flips -> 0, i.e. "tested, no effect", the SAFE-LOOKING direction);
#   * THE ARMING IS TOO WIDE (M12) -- the stub arms every candidate, so a sibling
#     lever can move the answer while the flip is still attributed here;
#   * THE TWO ROUTES STOP BEING TWO (M13) -- the independent prefix walk stops
#     asking about towers, so it and the driven count measure different sets;
#   * ⭐ A ZERO THAT WAS NEVER MEASURED (M14) -- the direction counter stops
#     being bumped. `flip_false_to_true` then reads exactly as it does when 1012
#     frames were driven and none went the wrong way: the GH #171 shape;
#   * THE INSTRUMENT READS PROSE INSTEAD OF CODE (M15) -- strip_comments leaves
#     the sweep, and this lever's comment QUOTES the sibling clause verbatim, so
#     several [source] facts would be satisfiable by that quotation;
#   * THE CONTROL (C1) -- a comment-only edit inside the lever must SURVIVE. If it
#     is caught, something in the suite is being satisfied by prose.
#
# ⛔ ANCHOR UNIQUENESS IS PART OF EACH DECLARATION, not a detail of the regex
# (GH #550, and GH #555 for the two live instances it left behind). Two needles
# in this file are deliberately MULTI-LINE for that reason: the plain statement
# form of the tower clause occurs twice in jmz_func.lua (J.IsFieldRegenSituation
# and J.ShouldFieldBuyRegenHurt) and the 1200 chase-ring line occurs twice as
# well, so each is pinned with a neighbouring line that names its function. The
# lever's own clause is written as a two-line conjunction whose second line
# occurs exactly once in the whole file, and `anchor` proves that every run.
#
# Each mutant edits ONE file in place and restores it from a copy taken OUTSIDE
# the tree, proving the restore with `sha256sum -c` after every mutant
# (evidence-discipline rule 1: `git checkout --` would silently discard the
# uncommitted work that is the whole subject here).
#
#   bash tools/agent/mutstand_staytower.sh
#
# ⚠️ DO NOT EDIT THIS FILE WHILE IT IS RUNNING. bash reads a script by BYTE
# OFFSET as it executes; inserting bytes ahead of the current offset misaligns
# every later read and the run is void (paid for on 2026-09-06, one whole stand
# re-run).
#
# Exit 0 = every mutant landed as declared. Exit 1 = a real mutant SURVIVED, or
# the control was CAUGHT (rule 2: suspect the assertion before the mutation --
# and per its converse, first confirm the edit landed where you meant).
set -uo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

JMZ=bots/FunLib/jmz_func.lua
SWEEP=tests/_staytower_sweep.lua
TEST=staytower_tower

TMP=$(mktemp -d)
nrun=0; ncaught=0; nbad=0; nunmeas=0
INFLIGHT=""

save() {
    cp "$1" "$TMP/$(basename "$1").orig"
    sha256sum "$1" > "$TMP/$(basename "$1").sha"
    INFLIGHT="$1"
}
restore() {
    cp "$TMP/$(basename "$1").orig" "$1"
    if ! sha256sum -c "$TMP/$(basename "$1").sha" >/dev/null; then
        echo "FATAL: restore of $1 did not verify -- stopping before anything else runs"
        exit 2
    fi
    INFLIGHT=""
}
# GH #418's trap: restore FIRST, delete the copies SECOND. The reverse leaves a
# mutant in the tree and destroys the only original.
on_exit() {
    if [ -n "$INFLIGHT" ]; then
        echo "INTERRUPTED with $INFLIGHT mutated -- restoring before exit"
        restore "$INFLIGHT"
    fi
    rm -rf "$TMP"
}
trap on_exit EXIT

# Rule 3: read the exit code directly, never through a pipe.
run_test() {
    local rc=0
    lua5.1 tests/run_tests.lua "$TEST" > "$TMP/$TEST.log" 2>&1 || rc=$?
    echo "$rc"
}

# ⛔ THE ANCHOR CHECK, and it runs BEFORE the mutant does. A `perl -0pi -e "s///"`
# without /g rewrites the FIRST match, so an anchor that occurs twice cuts a
# function the label does not name -- and then prints CAUGHT, which is
# indistinguishable from a mutant that worked (GH #550). Every anchor declares how
# many times it may occur, and a mismatch is a STAND failure, not a mutant result.
anchor() {
    local want=$1 file=$2 needle=$3
    local n
    n=$(NEEDLE="$needle" python3 -c 'import os,sys; sys.stdout.write(str(open(sys.argv[1]).read().count(os.environ["NEEDLE"])))' "$file" 2>/dev/null || true)
    [ -z "$n" ] && n=0
    if [ "$n" -ne "$want" ]; then
        printf 'ANCHOR    %-58s occurs %s time(s) in %s, expected %s\n' \
            "$needle" "$n" "$file" "$want"
        nbad=$((nbad + 1))
        return 1
    fi
    return 0
}

# want=caught (a real mutant), want=survive (a control), want=unmeasurable (a
# real mutant this corpus provably cannot catch, with the reason recorded at the
# call site). UNMEASURABLE is not a pass.
mutant() {
    local want=$1 label=$2 target=$3; shift 3
    nrun=$((nrun + 1))
    save "$target"
    "$@"
    if cmp -s "$target" "$TMP/$(basename "$target").orig"; then
        restore "$target"
        printf 'NO-OP     %-58s (the edit matched nothing -- the mutant never existed)\n' "$label"
        nbad=$((nbad + 1))
        return
    fi
    local rc; rc=$(run_test)
    restore "$target"
    if [ "$want" = caught ]; then
        if [ "$rc" -ne 0 ]; then
            ncaught=$((ncaught + 1))
            printf 'CAUGHT    %-58s exit=%s\n' "$label" "$rc"
        else
            nbad=$((nbad + 1))
            printf 'SURVIVED  %-58s exit=%s\n' "$label" "$rc"
            echo "          ^ per evidence-discipline rule 2, suspect the ASSERTION first;"
            echo "            per its converse, first confirm the edit landed where you meant."
        fi
    elif [ "$want" = unmeasurable ]; then
        if [ "$rc" -eq 0 ]; then
            nunmeas=$((nunmeas + 1))
            printf 'UNMEASURABLE %-55s exit=%s  (declared; NOT a pass)\n' "$label" "$rc"
        else
            nbad=$((nbad + 1))
            printf 'CAUGHT    %-58s exit=%s  ** re-classify as `caught` **\n' "$label" "$rc"
        fi
    else
        if [ "$rc" -eq 0 ]; then
            ncaught=$((ncaught + 1))
            printf 'SURVIVED  %-58s exit=%s  (control, as declared)\n' "$label" "$rc"
        else
            nbad=$((nbad + 1))
            printf 'CAUGHT    %-58s exit=%s  ** CONTROL WENT RED **\n' "$label" "$rc"
            echo "          ^ a comment edit turned this suite red: something in it"
            echo "            is being satisfied by prose rather than by code."
        fi
    fi
}

# --- M1, M2, M4: the lever leaves, or lands inverted -------------------------
anchor 1 "$JMZ" "	if J.IsSoakCandidate( 'staytower' )"
m1() { perl -0pi -e "s/\tif J\.IsSoakCandidate\( 'staytower' \)/\tif not J.IsSoakCandidate( 'staytower' )/" "$JMZ"; }
mutant caught "M1 the gate lands negated (shipped and armed legs swap)" "$JMZ" m1

anchor 1 "$JMZ" "	and #bot:GetNearbyTowers( 1200, true ) > 0"
m2() { perl -0pi -e "s/\tif J\.IsSoakCandidate\( 'staytower' \)\n\tand #bot:GetNearbyTowers\( 1200, true \) > 0\n\tthen\n\t\treturn false\n\tend\n//" "$JMZ"; }
mutant caught "M2 the veto block is deleted outright" "$JMZ" m2

# Inverted: the lever now releases a bot precisely where there is NO tower, which
# is every held frame the family's own controls are built from.
m4() { perl -0pi -e "s/\tand #bot:GetNearbyTowers\( 1200, true \) > 0/\tand #bot:GetNearbyTowers( 1200, true ) == 0/" "$JMZ"; }
mutant caught "M4 the veto is inverted (fires where there is no tower)" "$JMZ" m4

# --- M5: ⭐ the gate stops being the FIRST conjunct ---------------------------
# Behaviourally identical on BOTH legs -- `and` is commutative for these two
# operands -- so no [frame] or [census] number moves. What dies is the reason
# "un-armed, shipped behaviour is byte-identical" is a fact: with the engine call
# first, every turbo frame of every shipped game now pays for a GetNearbyTowers
# sweep this lever claims to be inert for. This is the tidy-up-shaped mutant.
m5() { perl -0pi -e "s/\tif J\.IsSoakCandidate\( 'staytower' \)\n\tand #bot:GetNearbyTowers\( 1200, true \) > 0/\tif #bot:GetNearbyTowers( 1200, true ) > 0\n\tand J.IsSoakCandidate( 'staytower' )/" "$JMZ"; }
mutant caught "M5 the gate is no longer the first conjunct (inertness dies)" "$JMZ" m5

# --- M3, M6: the provenance claim, both directions ---------------------------
# The lever's own copy of the radius drifts to the sibling family's OTHER
# constant, which is the most plausible wrong number in this file.
m3() { perl -0pi -e "s/\tand #bot:GetNearbyTowers\( 1200, true \) > 0/\tand #bot:GetNearbyTowers( 1600, true ) > 0/" "$JMZ"; }
mutant caught "M3 the lever's radius drifts from the sibling's 1200" "$JMZ" m3

# ...and the OWNING constant moves instead, which leaves this lever untouched,
# still gated, still passing every behaviour test, while the finding it is named
# after ("the sibling already asks this, at this radius") is no longer true.
anchor 1 "$JMZ" "	-- it is vacuously satisfied, not verified.
	if #bot:GetNearbyTowers( 1200, true ) > 0 then return false end"
m6() { perl -0pi -e "s/\t-- it is vacuously satisfied, not verified\.\n\tif #bot:GetNearbyTowers\( 1200, true \) > 0 then return false end/\t-- it is vacuously satisfied, not verified.\n\tif #bot:GetNearbyTowers( 900, true ) > 0 then return false end/" "$JMZ"; }
mutant caught "M6 the SIBLING's own 1200 moves (the quotation goes stale)" "$JMZ" m6

# --- M7, M8: the premise this lever sits between moves -----------------------
# The chase ring the lever inherits unchanged. Widened, the shipped predicate
# stops holding bots this lever's domain is drawn from, and the domain silently
# becomes a different set. Anchored on two lines because the ring statement
# itself occurs twice in this file.
anchor 1 "$JMZ" "		or J.HasNearbyHeroDamager( bot, 3000, 3.0 ) )
	then
		return false
	end
	if #J.GetNearbyHeroes( bot, 1200, true, BOT_MODE_NONE ) > 0 then return false end"
m7() { perl -0pi -e "s/\t\tor J\.HasNearbyHeroDamager\( bot, 3000, 3\.0 \) \)\n\tthen\n\t\treturn false\n\tend\n\tif #J\.GetNearbyHeroes\( bot, 1200, true, BOT_MODE_NONE \) > 0 then return false end/\t\tor J.HasNearbyHeroDamager( bot, 3000, 3.0 ) )\n\tthen\n\t\treturn false\n\tend\n\tif #J.GetNearbyHeroes( bot, 400, true, BOT_MODE_NONE ) > 0 then return false end/" "$JMZ"; }
mutant caught "M7 the PROMOTED chase ring shrinks (the domain becomes another set)" "$JMZ" m7

anchor 1 "$JMZ" "	if nHP < 0.18 or nHP > 0.75 then return false end"
m8() { perl -0pi -e "s/\tif nHP < 0\.18 or nHP > 0\.75 then return false end/\tif nHP < 0.18 or nHP > 0.55 then return false end/" "$JMZ"; }
mutant caught "M8 the PROMOTED band ceiling drops to the sibling's 0.55" "$JMZ" m8

# --- M9: the pullcad trap ----------------------------------------------------
# A dependency written as prose becomes a dependency written as code -- which is
# the good instinct and the wrong place: the day either id is promoted, a
# promoted id is in no armed string and the whole condition freezes FALSE, while
# check_armed_wiring.py still calls the site WIRED.
m9() { perl -0pi -e "s/\tif J\.IsSoakCandidate\( 'staytower' \)\n\tand #bot:GetNearbyTowers/\tif J.IsSoakCandidate( 'staytower' ) and J.IsSoakCandidate( 'stayfield2' )\n\tand #bot:GetNearbyTowers/" "$JMZ"; }
mutant caught "M9 a second soak id joins the gate's condition" "$JMZ" m9

# --- M10: ⭐ the two-column construction collapses ----------------------------
anchor 1 "$SWEEP" "                    bot.GetGold = function() return fGold end"
m10() { perl -0pi -e "s/                    bot\.GetGold = function\(\) return fGold end/                    bot.GetGold = function() return 0 end/" "$SWEEP"; }
mutant caught "M10 the gold override stops taking (g200 reads g0's zero)" "$SWEEP" m10

# --- M11, M12: the toggle and the arming -------------------------------------
anchor 1 "$SWEEP" "                            armed = true"
m11() { perl -0pi -e "s/                            armed = true\n/                            armed = false\n/" "$SWEEP"; }
mutant caught "M11 the armed leg is driven disarmed (flips -> 0)" "$SWEEP" m11

anchor 1 "$SWEEP" "                        return armed and sId == 'staytower'"
m12() { perl -0pi -e "s/                        return armed and sId == 'staytower'/                        return armed/" "$SWEEP"; }
mutant caught "M12 the stub arms every candidate at once" "$SWEEP" m12

# --- M13, M14: the second route, and an unmeasured zero ----------------------
anchor 1 "$SWEEP" "                            if #tw > 0 then bump('prefix_tower') end"
m13() { perl -0pi -e "s/                            if #tw > 0 then bump\('prefix_tower'\) end/                            bump('prefix_tower')/" "$SWEEP"; }
mutant caught "M13 the prefix walk stops asking about towers" "$SWEEP" m13

# ⭐ THIS MUTANT'S FIRST RUN SURVIVED, AND IT WAS RIGHT TO. `flip_false_to_true`
# is a claim whose whole content is a zero, and direction is fixed by
# construction, so the bump was never reached on this corpus and deleting it left
# the same zero. Per evidence-discipline rule 2 the suspect was the ASSERTION:
# the sweep now tallies both directions through one function and calls it a second
# time with the legs swapped, so the branch that must report 0 is the branch the
# swapped call reports the whole domain (12) through. Deleting it now moves a
# nonzero column, which is why this mutant can be declared `caught` at all.
anchor 1 "$SWEEP" "                                if b and not a then bump(sUp) end"
m14() { perl -0pi -e "s/                                if b and not a then bump\(sUp\) end/                                local _ = sUp/" "$SWEEP"; }
mutant caught "M14 the FALSE->TRUE branch of the tally is deleted" "$SWEEP" m14

# Its mirror: delete the other branch and the domain columns go to zero while
# `flip_false_to_true` still reads its innocent 0.
anchor 1 "$SWEEP" "                                if a and not b then bump(sDown) end"
m14b() { perl -0pi -e "s/                                if a and not b then bump\(sDown\) end/                                local _ = sDown/" "$SWEEP"; }
mutant caught "M14b the TRUE->FALSE branch of the tally is deleted" "$SWEEP" m14b

# And the swapped call itself, which is the only thing making M14 measurable: drop
# it and the suite is back to asserting an unmeasured zero.
anchor 1 "$SWEEP" "                            tally(arm, shipped,"
m14c() { perl -0pi -e "s/                            tally\(arm, shipped,\n                                g == 0 and 'dirprobe_down_g0' or 'dirprobe_down_g200',\n                                g == 0 and 'dirprobe_up_g0' or 'dirprobe_up_g200'\)\n//" "$SWEEP"; }
mutant caught "M14c the swapped direction probe is removed entirely" "$SWEEP" m14c

# --- M15: the instrument reads prose instead of code -------------------------
anchor 1 "$SWEEP" "    return (s:gsub('%-%-[^\\n]*', ''))"
m15() { perl -0pi -e "s/    return \(s:gsub\('%-%-\[\^\\\\n\]\*', ''\)\)/    return s/" "$SWEEP"; }
mutant caught "M15 strip_comments becomes the identity (prose satisfies code)" "$SWEEP" m15

# --- C1: the control ---------------------------------------------------------
anchor 1 "$JMZ" "	-- [staytower / owner priority P2, 2026-09-06] The BUILDING half of this"
c1() { perl -0pi -e "s/\t-- \[staytower \/ owner priority P2, 2026-09-06\] The BUILDING half of this/\t-- [staytower \/ owner priority P2, 2026-09-06] THE BUILDING HALF of this/" "$JMZ"; }
mutant survive "C1 comment-only edit inside the lever" "$JMZ" c1

printf '\nSTAND: %d mutants run, %d landed as declared, %d unmeasurable, %d unexpected\n' \
    "$nrun" "$ncaught" "$nunmeas" "$nbad"
if [ "$nbad" -eq 0 ] && [ "$nunmeas" -eq 0 ]; then
    echo 'STAND GREEN'
    exit 0
fi
if [ "$nbad" -eq 0 ]; then
    echo 'STAND AMBER -- every mutant landed as declared, but some are UNMEASURABLE'
    exit 0
fi
echo 'STAND RED'
exit 1
