-- [GH #492, director 2026-09-05] THE DECLARATION THAT COMES WITH THE REPAIR.
--
-- tests/mock/replay_fixture.lua now answers `GetExtrapolatedLocation`. Before
-- it did not, the name fell through bot_api.lua's `^Get -> 0` catch-all, every
-- shipped consumer indexed the 0 as a location, and the frame RAISED -- which
-- two `pcall` sweeps with two buckets for a three-valued read scored as a
-- measured "no". The frames deleted that way were the enemy-in-your-face ones,
-- i.e. the reason J.CanEnemyInterruptTpChannel exists. That is the defect the
-- repair closes, and it is priced in test_midsupmirror_checkability.lua.
--
-- ⭐ THIS FILE PRICES WHAT THE REPAIR DID **NOT** BUY, because that is the half
-- that will rot. A fixture is ONE INSTANT: make_fixture.py dumps x/y and no
-- velocity, no facing, no waypoint. So the mock cannot extrapolate; it answers
-- the current location, modelling every unit as STANDING STILL. The shipped
-- guard reads
--     nNow  = dist(bot, enemy:GetLocation())
--     nSoon = dist(bot, enemy:GetExtrapolatedLocation(0.5))
--     if nNow <= nReach or (... and nSoon < nNow - 10) then return true end
-- and under this model nSoon == nNow ALWAYS, so the second clause -- "it is
-- closing the gap on me" -- is unreachable on this corpus. The first clause,
-- "it can strike me right now", is answered honestly.
--
-- ⇒ EVERY domain count taken through this mock is a LOWER BOUND on
-- interruption, never an upper one, and it errs toward "the TP is safe".
--
-- ⚠️ WHY THIS IS A TEST AND NOT A COMMENT. The repo's standing lesson is that a
-- mock default states a world assumption nobody declared; a comment declaring
-- one is the same failure one step later, because nothing measures a comment.
-- The three assertions below are the measurement: the day make_fixture.py
-- starts carrying motion, [model] goes red and the standing-still story stops
-- being true silently instead of loudly.

package.path = 'tests/?.lua;' .. package.path
local rf = require('mock.replay_fixture')

local FIX  = 'tests/fixtures/f_071423_luna_chase.lua'
local SUBJ = 'npc_dota_hero_luna'

local tests = {}

local function read_file(path)
    local f = assert(io.open(path, 'r'), path .. ' is not readable')
    local s = f:read('*a')
    f:close()
    return s
end

-- Every fixture opens with a generated `-- GENERATED by ... --t=... subject ...`
-- header, so a scanner that reads the raw bytes would answer "this fixture
-- carries velocity" for a fixture that merely MENTIONS the word in a comment.
-- That is not hypothetical prudence: the header is the first thing
-- make_fixture.py writes and it names the tool's own arguments. Cut each line
-- at its first `--`. Fixture data is numbers, bare keys and single-quoted
-- item/hero names, none of which contain `--`; the [model] leg proves the strip
-- did not eat the data by requiring an `x =` in every file AFTER stripping.
local function strip_line_comments(src)
    local out = {}
    for line in (src .. '\n'):gmatch('([^\n]*)\n') do
        local at = line:find('--', 1, true)
        out[#out + 1] = at and line:sub(1, at - 1) or line
    end
    return table.concat(out, '\n')
end

local function fixture_files()
    local p = assert(io.popen('ls tests/fixtures'))
    local files = {}
    for f in p:lines() do
        if f:match('^f_.*%.lua$') then files[#files + 1] = 'tests/fixtures/' .. f end
    end
    p:close()
    table.sort(files)
    return files
end

tests['[mock] the name answers a location on a real frame'] = function()
    local J, bot = rf.load(FIX, SUBJ)
    local near = J.GetNearbyHeroes(bot, 100000, true, BOT_MODE_NONE)
    assert(near ~= nil and #near > 0, FIX .. ' has no enemy hero to read')
    local n = 0
    for _, h in pairs(near) do
        local e = h:GetExtrapolatedLocation(0.5)
        assert(type(e) == 'table', 'GetExtrapolatedLocation answered a '
            .. type(e) .. ' -- the mock repair was reverted, and every count '
            .. 'in test_midsupmirror_checkability.lua reverts with it')
        assert(type(e.x) == 'number' and type(e.y) == 'number',
            'the answer is a table but not a location: it has no numeric x/y')
        n = n + 1
    end
    assert(n > 0, 'the loop body never ran -- this test asserts nothing')
end

tests['[model] no fixture carries motion, so standing-still is forced'] = function()
    -- The scanner is proved against a key that IS there before it is trusted
    -- about keys that are not: a regex that matches nothing would otherwise
    -- report "no fixture carries velocity" for the rest of time.
    local files = fixture_files()
    assert(#files >= 100, 'only ' .. #files .. ' fixtures found -- the corpus '
        .. 'shrank or the glob broke; either way re-read before trusting this')
    local nWithX, offenders = 0, {}
    for _, path in ipairs(files) do
        local src = strip_line_comments(read_file(path))
        if src:find('%f[%w]x%s*=%s*%-?%d') then nWithX = nWithX + 1 end
        for _, key in ipairs({ 'vel', 'velocity', 'facing', 'vx', 'vy',
                               'speed', 'waypoint', 'heading' }) do
            if src:find('%f[%w]' .. key .. '%s*=') then
                offenders[#offenders + 1] = path .. ' carries `' .. key .. '`'
            end
        end
    end
    assert(nWithX == #files, 'the scanner found an `x =` in only ' .. nWithX
        .. ' of ' .. #files .. ' fixtures -- it is not reading what it thinks '
        .. 'it is, so its negative answer below means nothing')
    assert(#offenders == 0, 'a fixture now carries motion state:\n  '
        .. table.concat(offenders, '\n  ')
        .. '\nThe standing-still model in tests/mock/replay_fixture.lua is no '
        .. 'longer FORCED by the corpus -- it is now a CHOICE, and an '
        .. 'undeclared one. Teach the mock to use the real velocity, then '
        .. 're-take every domain that rests on it (test_set.md §EF.1, the '
        .. 'int_true/int_in_domain counts in test_midsupmirror_checkability.lua).')
end

tests['[consequence] the closing-the-gap clause cannot fire on this corpus'] = function()
    -- Driven on real frames rather than argued from the model: for every enemy
    -- the guard would scan, the two distances it compares are equal, so
    -- `nSoon < nNow - 10` is false by arithmetic and not by assumption.
    local J, bot = rf.load(FIX, SUBJ)
    local vBotLoc = bot:GetLocation()
    local near = J.GetNearbyHeroes(bot, 100000, true, BOT_MODE_NONE)
    local n = 0
    for _, h in pairs(near) do
        local nNow  = J.GetLocationToLocationDistance(vBotLoc, h:GetLocation())
        local nSoon = J.GetLocationToLocationDistance(vBotLoc,
                          h:GetExtrapolatedLocation(0.5))
        assert(nSoon == nNow, 'the extrapolated distance (' .. tostring(nSoon)
            .. ') differs from the current one (' .. tostring(nNow)
            .. ') -- the mock started extrapolating for real. That is good '
            .. 'news and it invalidates this pricing: the guard can now fire '
            .. 'on its second clause, so re-take the domains named above.')
        assert(not (nSoon < nNow - 10), 'the closing-the-gap clause became '
            .. 'reachable -- re-price')
        n = n + 1
    end
    assert(n > 0, 'the loop body never ran -- this test asserts nothing')
end

tests['[guard] and the first clause DOES fire, so the repair is not cosmetic'] = function()
    -- The whole point of the repair is that the guard now reaches an answer
    -- instead of raising. Stated on the frame that was the standing example of
    -- the censoring (test_midsupmirror_checkability.lua's CENSORED frame).
    local J, bot = rf.load(FIX, SUBJ)
    J.IsSoakCandidate = function() return false end
    local ok, ans = pcall(J.CanEnemyInterruptTpChannel, bot)
    assert(ok, 'J.CanEnemyInterruptTpChannel still raises on the frame the '
        .. 'repair was written for: ' .. tostring(ans))
    assert(type(ans) == 'boolean', 'the guard answered a ' .. type(ans))
    -- On THIS frame luna has slardar inside attack reach; that is the whole
    -- reason it was the censored example. A corpus-wide count (257 in domain,
    -- 0 raising, 73 answering true) lives in test_midsupmirror_checkability.lua.
    assert(ans == true, 'the guard answers FALSE on the frame where luna is '
        .. 'being hit at melee range -- the first clause is not doing the work '
        .. 'this pricing says it does; re-read before trusting the 73')
end

return tests
