-- [ratchet] [hero] Crystal Maiden -- the `cmqreach` reach claim, on a REAL
-- FRAME instead of a synthetic world.  Claims GH #354 section 5, which asked
-- the hero group for exactly this and named the frame:
--
--     69e067 / 20260831_004433_slot1, t = 1190.4
--
-- Sister file: tests/test_cm_q_creep_aoe_reach.lua (the gate/plumbing half,
-- synthetic worlds, a spy on FindAoELocation).  That file states the shape of
-- the defect; this one prices it on the frame the replay group picked.
--
-- WHY THIS COULD NOT BE BUILT BEFORE TODAY, AND WHAT CHANGED
--
-- `make_fixture.py` wrote heroes and buildings and dropped the creep samples on
-- the floor, so EVERY fixture in tests/fixtures/ describes a world with NO
-- CREEPS IN IT.  tests/mock/replay_fixture.lua answers `FindAoELocation` with
-- the conservative stand-in `{count = 0, targetloc = <self>}`, and every
-- shipped creep-AoE decision sits behind a `.count >= 2..5` read of that
-- result.  So the branch under test was not "not exercised by the corpus", it
-- was UNREACHABLE BY CONSTRUCTION in every fixture ever generated -- the datum
-- the question is about was discarded at fixture-write time.  The generator now
-- carries the creep sample (position and team, which is all the dump has), and
-- WHY THE FRAME IS IN tests/frames/ AND NOT tests/fixtures/
--
-- Because tests/fixtures/ is not just a shelf of worlds, it is the CENSUS
-- CORPUS: about two dozen tests glob it and take readings over everything they
-- find.  This frame is 19:50 with heroes up to level 22, and the corpus before
-- it topped out at level 19 and t~790 -- so admitting it turns eight of those
-- readings red, three of which are real re-decisions rather than bookkeeping
-- (Axe t15 finally measurable IN domain, the Black King Bar zero behind
-- test_axe_cull_immune_veto, the Alchemist objective-clock band).  Those are
-- four different questions belonging to four different levers, and answering
-- them in a hurry to make a suite green is the opposite of what those ratchets
-- exist for.  The frame is therefore STAGED: real, generated by the same
-- script, loaded by name here, and outside the glob until somebody pays that
-- list on purpose.  tests/frames/README.md carries the list and the price.
--
-- this file is the first test to read it.  Section 6 pins that the loader's
-- stand-in is STILL count = 0, because that gap is real and this file does not
-- close it: the search below is done here, by this test, not by the loader.
--
-- WHAT IS ASKED, AND THE FORM OF THE ANSWER
--
-- `bot:FindAoELocation( bEnemies, bHeroes, vBase, nMaxDistanceFromBase,
-- nRadius, fTimeInFuture, nMaxHealth )` may return ANY point within
-- `nMaxDistanceFromBase` of `vBase` (docs/BOT_API_REFERENCE.md:1366).  Which
-- one it picks among equally good centres is an engine internal this repo
-- cannot read.  So the question is NOT asked as "what point does the engine
-- return" -- it is asked with a quantifier that makes the engine's choice
-- irrelevant:
--
--     over the REAL creep positions on this frame, how far from CM is the
--     NEAREST point that covers at least k of them?
--
-- If even the nearest qualifying centre is out of cast range, then EVERY
-- qualifying centre is, and whatever the engine hands back with `count >= k`
-- is a point she cannot cast at.  That is a bound, not a model of the engine.
--
-- THE READING (section 3, and it is the point of this file)
--
--     nearest legal centre covering >= 1 enemy creep :   805.9
--                                       >= 2          :   904.5
--                                       >= 3          :   925.1
--                                       >= 4          :  1152.4
--                                       >= 5          :  1312.3
--                                       >= 6          :  none
--     the ring she may cast into                      :   732
--     the ring the SHIPPED code searches               :  1157
--     the ring the ARMED code searches ('cmqreach')    :   732
--
-- Read off those two columns:
--   * SHIPPED can return a centre with count 2, 3 or 4 (5 is beyond even the
--     wide ring), and every such centre is between 904.5 and 1157 from her --
--     that is 172.5 to 425 units BEYOND the 732 she may cast into.  There is no
--     tie-break under which the shipped search hands back a castable creep
--     point on this frame.
--   * ARMED returns count 0: the nearest centre covering even ONE enemy creep
--     is 805.9 away, outside the 732 ring.  Every `count >= N` creep site is
--     false, so the armed side does not cast Nova on the wave here at all.
--
-- That is the fix's own claim -- "armed casts on waves no more often than
-- shipped, and never relocates a cast that was already legal" -- observed on a
-- real frame rather than argued.  It does NOT show a gain; see section 6.
--
-- THE SOLVER IS EXACT, AND IS PINNED AS SUCH
--
-- For a fixed radius r, the nearest point of an intersection of disks to C is
-- C itself (when feasible), or a point where one constraint is active (the
-- projection of C onto that circle), or a vertex where two are (an intersection
-- of two circles).  Those three families are the whole candidate set, so the
-- minimum below is exact -- no grid, no tolerance ladder.  Cross-checked
-- offline against a 2-unit brute-force grid on this very frame: 904.86 /
-- 925.18 / 1152.48 for k = 2/3/4, each a hair above the exact value, which is
-- the direction a grid must err.  Section 5 pins the solver on synthetic inputs
-- with hand-computable answers, because a solver checked only on the frame it
-- was written for is checked against nothing (the M4/M8 lesson from
-- tests/test_aoe_result_field_names.lua, twice paid for now).
--
-- WHAT THIS FILE DOES NOT CLAIM (section 6, measured where possible)
--
--   * NOT that the armed side is better here.  It says the armed side casts
--     nothing on this frame and the shipped side can only aim at a point it
--     cannot reach.  Which of those two is worth more is what the engine does
--     with an out-of-range order, and that is unreadable from the bot VM.
--   * NOT a firing claim.  Whether execution REACHES a creep return site needs
--     creep health (`nCanKillCreeps...` filters on it, and every creep site
--     also wants a valid weakest lane creep) and the mode predicates
--     `IsFarming` / `IsPushing` / `IsDefending` -- none of which the dump
--     carries.  Section 6 states this as a fact about the fixture, not as a
--     property of the hero.
--   * NOT that the creep positions are the ones she cast at.  They are a
--     sample.  This dump was taken at `-creep-interval 0.5` (the wave farm's
--     default is 3.0), so the sample sits dt = 0.0 from the instant -- the
--     resolution objection GH #354 section 4 raised against the 3.0s corpus
--     does not apply to this frame, and section 1 asserts that rather than
--     assuming it.
package.path = 'tests/?.lua;' .. package.path
local rf = require('mock.replay_fixture')

local FRAME = 'tests/frames/f_20260831_004433_cm_creepreach.lua'

local NOVA = 'crystal_maiden_crystal_nova'

-- External anchors, same two as the sister file: Crystal Nova's KV is flat
-- (`AbilityCastRange 700` at every rank, `radius value 425`).  The dumper
-- carries neither, and nCastRange = GetCastRange() + aetherRange + 32.
local NOVA_CAST_RANGE = 700
local NOVA_RADIUS = 425
local N_CAST_RANGE = NOVA_CAST_RANGE + 0 + 32   -- 732; no Aether Lens, see §1

local EPS = 1e-6

-- =====================================================================
-- The exact solver (see header).  Kept in this file on purpose: it is a
-- reading instrument, not shipped logic, and section 5 is its calibration.
-- =====================================================================

local function dist(ax, ay, bx, by)
    local dx, dy = ax - bx, ay - by
    return math.sqrt(dx * dx + dy * dy)
end

--- How many of `tPts` a radius-`r` disk centred at (qx, qy) covers.
local function coverage(tPts, qx, qy, r)
    local n = 0
    for _, p in ipairs(tPts) do
        if dist(qx, qy, p.x, p.y) <= r + EPS then n = n + 1 end
    end
    return n
end

--- Every candidate centre the exact minimum can sit on (header: C itself, the
--- projection of C onto each circle, and each pair of circles' intersections).
local function candidates(tPts, cx, cy, r)
    local out = { { x = cx, y = cy } }
    for _, p in ipairs(tPts) do
        local d = dist(cx, cy, p.x, p.y)
        if d > EPS then
            local s = math.max(0.0, d - r) / d
            out[#out + 1] = { x = cx + (p.x - cx) * s, y = cy + (p.y - cy) * s }
        end
    end
    for i = 1, #tPts do
        for j = i + 1, #tPts do
            local a, b = tPts[i], tPts[j]
            local dx, dy = b.x - a.x, b.y - a.y
            local d = math.sqrt(dx * dx + dy * dy)
            if d > EPS and d <= 2 * r then
                local h = math.sqrt(math.max(0.0, r * r - (d / 2) * (d / 2)))
                local mx, my = (a.x + b.x) / 2, (a.y + b.y) / 2
                local ux, uy = -dy / d, dx / d
                out[#out + 1] = { x = mx + ux * h, y = my + uy * h }
                out[#out + 1] = { x = mx - ux * h, y = my - uy * h }
            end
        end
    end
    return out
end

--- Distance from (cx, cy) to the NEAREST centre of a radius-`r` disk that
--- covers at least `k` of `tPts`.  nil when no such centre exists anywhere.
--- The engine's own `nMaxDistanceFromBase` is applied by the CALLER, by
--- comparing this distance against the search radius: minimising |q - C| means
--- that constraint can never be active at the optimum, it can only exclude it.
local function nearest_centre(tPts, cx, cy, r, k)
    local best, bx, by
    for _, q in ipairs(candidates(tPts, cx, cy, r)) do
        if coverage(tPts, q.x, q.y, r) >= k then
            local d = dist(cx, cy, q.x, q.y)
            if best == nil or d < best then best, bx, by = d, q.x, q.y end
        end
    end
    return best, bx, by
end

-- =====================================================================
-- Frame helpers
-- =====================================================================

local function load_frame()
    local J, bot, heroes, fx = rf.load(FRAME)
    return J, bot, heroes, fx
end

--- The enemy lane creeps on the frame, in CM's terms: team 4 is neutrals and
--- her own team's creeps are not what `FindAoELocation(true, ...)` looks at.
local function enemy_creeps(fx, subj_team)
    local out = {}
    for _, c in ipairs(fx.creeps or {}) do
        if c.team ~= 4 and c.team ~= subj_team then
            out[#out + 1] = { x = c.x, y = c.y }
        end
    end
    return out
end

local function subject_team(fx)
    for _, u in ipairs(fx.units) do
        if u.name == fx.self then return u.team end
    end
    error('subject not in the fixture')
end

local function close_to(got, want, tol, what)
    assert(got ~= nil and math.abs(got - want) <= tol,
        string.format('%s: got %s, want %s +-%s', what, tostring(got), want, tol))
end

local tests = {}

-- =====================================================================
-- §1  The frame itself
-- =====================================================================

tests['§1 provenance: this is the frame GH #354 section 5 named'] = function()
    local _, _, _, fx = load_frame()
    assert(fx.game == '20260831_004433_slot1', 'the game: ' .. tostring(fx.game))
    assert(fx.time == 1190.4, 'the instant: ' .. tostring(fx.time))
    assert(fx.self == 'npc_dota_hero_crystal_maiden', 'the subject')
end

tests['§1 the creep sample is CONTEMPORANEOUS, not up to 1.5s stale'] = function()
    local _, _, _, fx = load_frame()
    assert(fx.creeps ~= nil and #fx.creeps > 0,
        'the fixture carries creeps at all (the generator gap this file closed)')
    assert(fx.creep_interval == 0.5,
        'dumped at -creep-interval 0.5, not the farm default 3.0: '
        .. tostring(fx.creep_interval))
    for _, c in ipairs(fx.creeps) do
        assert(c.dt == 0.0, 'every creep sample sits on the instant: dt=' .. tostring(c.dt))
    end
end

tests['§1 she can actually cast: rank 4, off cooldown, mana over cost'] = function()
    -- The sister file had to MUTATE the cooldown to reach the search at all,
    -- and both archived CM frames hold Nova below rank 3 while every creep site
    -- wants nSkillLV >= 3.  This frame needs no mutation, which is what makes
    -- it the first CM frame in the corpus where the creep branch is live.
    local _, bot = load_frame()
    local hNova = bot:GetAbilityByName(NOVA)
    assert(hNova:GetLevel() == 4, 'Nova rank on the frame: ' .. hNova:GetLevel())
    assert(hNova:GetCooldownTimeRemaining() == 0, 'off cooldown on the frame')
    assert(bot:GetLevel() == 17, 'hero level on the frame: ' .. bot:GetLevel())
    assert(bot:GetMana() == 512, 'her mana on the frame: ' .. bot:GetMana())
    assert(bot:FindItemSlot('item_aether_lens') < 0,
        'no Aether Lens, so aetherRange is 0 and the cast ring is 732')
end

tests['§1 the world she is in: 8 enemy lane creeps, none of them close'] = function()
    local _, bot, _, fx = load_frame()
    local team = subject_team(fx)
    local tCreeps = enemy_creeps(fx, team)
    assert(#tCreeps == 8, 'enemy lane creeps on the frame: ' .. #tCreeps)

    local loc = bot:GetLocation()
    local nearest
    for _, p in ipairs(tCreeps) do
        local d = dist(loc.x, loc.y, p.x, p.y)
        if nearest == nil or d < nearest then nearest = d end
    end
    -- 1230.9 > 732 + 425: not one enemy creep can be covered by a disk centred
    -- inside her cast ring.  This single number already decides §3's armed row.
    close_to(nearest, 1230.9, 0.2, 'nearest enemy creep')
    assert(nearest > N_CAST_RANGE + NOVA_RADIUS,
        'no enemy creep is within cast ring + radius')
end

-- =====================================================================
-- §2  The two rings, read off the SHIPPED helper on this frame
-- =====================================================================

tests['§2 the rings come from the shipped helper, not from constants here'] = function()
    local J = load_frame()
    local X = rf.load_hero('crystal_maiden')

    J.IsModeTurbo = function() return true end
    J.IsSoakCandidate = function() return false end
    local nShipped = X.cm_GetCreepAoESearchRange(N_CAST_RANGE, NOVA_RADIUS)

    J.IsSoakCandidate = function(id) return id == 'cmqreach' end
    local nArmed = X.cm_GetCreepAoESearchRange(N_CAST_RANGE, NOVA_RADIUS)

    assert(nShipped == 1157, 'shipped creep search ring: ' .. nShipped)
    assert(nArmed == 732, 'armed creep search ring: ' .. nArmed)
    assert(nArmed == N_CAST_RANGE, 'armed searches exactly the castable ring')
    assert(nShipped - nArmed == NOVA_RADIUS, 'the overshoot is the whole radius')
end

-- =====================================================================
-- §3  THE READING -- real creeps, real position, exact geometry
-- =====================================================================

tests['§3 SHIPPED: every centre it may return with count >= 2 is out of cast range'] = function()
    local J, bot, _, fx = load_frame()
    local X = rf.load_hero('crystal_maiden')
    J.IsModeTurbo = function() return true end
    J.IsSoakCandidate = function() return false end
    local nSearch = X.cm_GetCreepAoESearchRange(N_CAST_RANGE, NOVA_RADIUS)

    local tCreeps = enemy_creeps(fx, subject_team(fx))
    local loc = bot:GetLocation()

    local tWant = { [1] = 805.9, [2] = 904.5, [3] = 925.1, [4] = 1152.4, [5] = 1312.3 }
    for k = 1, 5 do
        local d = nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, k)
        close_to(d, tWant[k], 0.1, 'nearest centre covering >= ' .. k)
    end
    assert(nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, 6) == nil,
        'no centre anywhere covers 6 of them')

    -- What the shipped ring can and cannot hand back on this frame.
    for k = 2, 4 do
        local d = nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, k)
        assert(d <= nSearch, 'count >= ' .. k .. ' is inside the 1157 search ring')
        assert(d > N_CAST_RANGE,
            'and outside the 732 cast ring by ' .. string.format('%.1f', d - N_CAST_RANGE))
    end
    local d5 = nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, 5)
    assert(d5 > nSearch, 'count >= 5 is beyond even the shipped ring: ' .. d5)

    -- The overshoot in the units the fix is about: the cheapest 2-creep centre
    -- is 172.5 beyond her reach, the cheapest 4-creep one is 420.4 beyond.
    close_to(nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, 2) - N_CAST_RANGE,
        172.5, 0.1, 'overshoot at the count>=2 sites')
    close_to(nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, 4) - N_CAST_RANGE,
        420.4, 0.1, 'overshoot at the count>=4 sites')
end

tests['§3 ARMED: the search returns count 0, so no creep site can fire'] = function()
    local J, bot, _, fx = load_frame()
    local X = rf.load_hero('crystal_maiden')
    J.IsModeTurbo = function() return true end
    J.IsSoakCandidate = function(id) return id == 'cmqreach' end
    local nSearch = X.cm_GetCreepAoESearchRange(N_CAST_RANGE, NOVA_RADIUS)

    local tCreeps = enemy_creeps(fx, subject_team(fx))
    local loc = bot:GetLocation()

    -- Not "fewer creeps": NONE.  The nearest centre covering even one is 805.9.
    local d1 = nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, 1)
    assert(d1 > nSearch,
        'armed, not one enemy creep is coverable from inside the cast ring: '
        .. string.format('%.1f > %d', d1, nSearch))

    -- So the count the armed search reports is 0, and the eight creep sites all
    -- read `count >= 2..5`.  Both thresholds are read off the shipped source
    -- rather than remembered here.
    local fh = assert(io.open('bots/BotLib/hero_crystal_maiden.lua', 'r'))
    local src = fh:read('*a')
    fh:close()
    local nSites = 0
    for n in src:gmatch('nCan%a+CreepsLocationAoE%.count >= (%d)') do
        nSites = nSites + 1
        assert(tonumber(n) >= 2, 'every creep site wants at least 2: ' .. n)
    end
    assert(nSites == 8, 'the eight creep return sites, by their thresholds: ' .. nSites)
end

-- =====================================================================
-- §3b  Which of the eight sites this frame actually reaches, and where it aims
-- =====================================================================

tests['§3b the HURT search is the priceable one, and its count on this frame is 4'] = function()
    -- nMaxHealth = 0 for the hurt search, so no creep health is needed and §3's
    -- numbers ARE its numbers.  Its two thresholds in the source are >= 4 and
    -- >= 5, and the largest count any centre inside the shipped 1157 ring
    -- achieves here is 4: the three `>= 4` sites are satisfiable on this frame
    -- and the `>= 5` site is not.
    local _, bot, _, fx = load_frame()
    local tCreeps = enemy_creeps(fx, subject_team(fx))
    local loc = bot:GetLocation()

    local nMax = 0
    for k = 1, #tCreeps do
        local d = nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, k)
        if d ~= nil and d <= 1157 then nMax = k end
    end
    assert(nMax == 4, 'largest count reachable inside the shipped ring: ' .. nMax)

    local fh = assert(io.open('bots/BotLib/hero_crystal_maiden.lua', 'r'))
    local src = fh:read('*a')
    fh:close()
    local n4, n5 = 0, 0
    for n in src:gmatch('nCanHurtCreepsLocationAoE%.count >= (%d)') do
        if n == '4' then n4 = n4 + 1 elseif n == '5' then n5 = n5 + 1 end
    end
    assert(n4 == 3 and n5 == 1, 'hurt sites: three at >=4, one at >=5 (' .. n4 .. '/' .. n5 .. ')')
end

tests['§3b the hurt post-filter does NOT rescue it: the count survives, the point stays unreachable'] = function()
    -- Before the eight sites read it, the hurt result passes through
    -- `J.GetInLocLaneCreepCount( bot, 1600, nRadius, targetloc ) <= 2 -> count = 0`.
    -- On this frame that filter passes: all four creeps the nearest 4-covering
    -- centre covers are also within 1600 of her, so the count is not zeroed and
    -- the three `>= 4` sites return a point 420.4 beyond her cast range.
    local _, bot, _, fx = load_frame()
    local tCreeps = enemy_creeps(fx, subject_team(fx))
    local loc = bot:GetLocation()

    local d, qx, qy = nearest_centre(tCreeps, loc.x, loc.y, NOVA_RADIUS, 4)
    close_to(d, 1152.4, 0.1, 'the nearest 4-covering centre')

    local nInLoc = 0
    for _, p in ipairs(tCreeps) do
        if dist(qx, qy, p.x, p.y) <= NOVA_RADIUS + EPS
            and dist(loc.x, loc.y, p.x, p.y) <= 1600 then
            nInLoc = nInLoc + 1
        end
    end
    assert(nInLoc == 4, 'creeps within 425 of the point AND 1600 of her: ' .. nInLoc)
    assert(nInLoc > 2, 'so the <= 2 filter does not zero the count')
end

-- =====================================================================
-- §4  Why the engine's tie-break cannot rescue the shipped side here
-- =====================================================================

tests['§4 the bound is over ALL qualifying centres, not the nearest one only'] = function()
    local _, bot, _, fx = load_frame()
    local tCreeps = enemy_creeps(fx, subject_team(fx))
    local loc = bot:GetLocation()

    -- The claim of §3 is a MINIMUM, so it holds for whatever the engine picks.
    -- Demonstrated rather than asserted: sample the whole shipped search disk
    -- on a coarse lattice and check that no point in it both covers >= 2 and
    -- sits inside the cast ring.  (A lattice can only miss such a point, and
    -- the exact solver above already says there is none -- the two instruments
    -- disagreeing is what this node exists to catch.)
    local nInRangeWithCreeps = 0
    for gx = -1157, 1157, 17 do
        for gy = -1157, 1157, 17 do
            local qx, qy = loc.x + gx, loc.y + gy
            if dist(loc.x, loc.y, qx, qy) <= N_CAST_RANGE
                and coverage(tCreeps, qx, qy, NOVA_RADIUS) >= 1 then
                nInRangeWithCreeps = nInRangeWithCreeps + 1
            end
        end
    end
    assert(nInRangeWithCreeps == 0,
        'a castable point covering an enemy creep was found on the lattice: '
        .. nInRangeWithCreeps)
end

-- =====================================================================
-- §5  Solver calibration on synthetic inputs (see header)
-- =====================================================================

tests['§5 solver: one point -- the nearest centre is on the line, at d - r'] = function()
    local pts = { { x = 1000, y = 0 } }
    local d = nearest_centre(pts, 0, 0, 425, 1)
    close_to(d, 575, 1e-6, 'single point at 1000, radius 425')
    -- Inside the disk already: the answer must be 0, not d - r.
    close_to(nearest_centre({ { x = 100, y = 0 } }, 0, 0, 425, 1), 0, 1e-6,
        'a point already within r of C')
end

tests['§5 solver: two points -- the lens vertex, hand-computed'] = function()
    -- Points at (0, +-300): a radius-425 disk covers both iff its centre is
    -- within 425 of each, so the legal set is the lens of the two circles,
    -- whose left vertex sits at x = -sqrt(425^2 - 300^2).  C far to the left
    -- makes that vertex the nearest legal centre.
    local pts = { { x = 0, y = 300 }, { x = 0, y = -300 } }
    local h = math.sqrt(425 * 425 - 300 * 300)
    local d = nearest_centre(pts, -5000, 0, 425, 2)
    close_to(d, 5000 - h, 1e-6, 'nearest point of the lens from far left')
    -- ...and covering just ONE of them is cheaper, which is the ordering every
    -- k-threshold claim in §3 depends on.
    assert(nearest_centre(pts, -5000, 0, 425, 1) < d, 'k=1 is never worse than k=2')
end

tests['§5 solver: k beyond what any disk can cover returns nil, not a number'] = function()
    -- Three points pairwise 900 apart: no radius-425 disk covers two of them
    -- (900 > 850), so k = 2 is infeasible ANYWHERE.  A solver that clamped
    -- instead of refusing would answer some finite distance here.
    local s = 900
    local pts = {
        { x = 0, y = 0 }, { x = s, y = 0 }, { x = s / 2, y = s * math.sqrt(3) / 2 },
    }
    assert(nearest_centre(pts, 0, 0, 425, 2) == nil, 'k=2 is infeasible at 900 apart')
    close_to(nearest_centre(pts, 0, 0, 425, 1), 0, 1e-6, 'k=1 is C itself')
    -- 849 apart: now a covering disk exists, and it is the midpoint.
    local ok = { { x = 0, y = 0 }, { x = 849, y = 0 } }
    close_to(nearest_centre(ok, 424.5, 0, 425, 2), 0, 1e-6, 'k=2 at 849 apart, C at the midpoint')
end

tests['§5 solver: the projection family is load-bearing, not decoration'] = function()
    -- Two points 800 apart, C far away on the perpendicular bisector.  The
    -- nearest 2-covering centre is a LENS VERTEX; the nearest 1-covering centre
    -- is a PROJECTION onto one circle.  A candidate set missing the projections
    -- would over-report the k=1 answer -- which is the exact defect the offline
    -- Python first draft had (it read 1157 where the truth was 1152.4), caught
    -- only by a brute-force grid.  This node is that catch, made permanent.
    local pts = { { x = -400, y = 3000 }, { x = 400, y = 3000 } }
    local d1 = nearest_centre(pts, 0, 0, 425, 1)
    local want1 = math.sqrt(400 * 400 + 3000 * 3000) - 425
    close_to(d1, want1, 1e-6, 'k=1 is the projection onto the nearer circle')
    local d2 = nearest_centre(pts, 0, 0, 425, 2)
    -- lens vertex on the near side: (0, 3000 - sqrt(425^2 - 400^2))
    close_to(d2, 3000 - math.sqrt(425 * 425 - 400 * 400), 1e-6, 'k=2 is the lens vertex')
    assert(d2 > d1, 'and it is farther, as it must be')
end

tests['§5 solver: coverage counts by disk membership, boundary included'] = function()
    local pts = { { x = 425, y = 0 }, { x = 426, y = 0 } }
    assert(coverage(pts, 0, 0, 425) == 1, 'the point exactly at r counts, the one past it does not')
end

-- =====================================================================
-- §6  What is NOT settled here, measured where it can be
-- =====================================================================

tests['§6 CLOSED: the loader now answers the creep search, and it agrees with §3'] = function()
    -- Was a LIMIT ("the loader still answers count = 0, so no fixture drives
    -- the branch") until hero 2026-08-31 wired tests/mock/replay_fixture.lua to
    -- the creep sample.  Kept here rather than deleted, because it is the only
    -- CROSS-CHECK the two halves get: §3's solver answers "how far is the
    -- nearest centre covering k", the loader answers "what is the largest k
    -- reachable inside the ring", and they were written for different questions
    -- by different code.  On this frame they must agree, and the arithmetic
    -- that ties them is entirely in §3's own table:
    --      >= 4 sits at 1152.4, inside the shipped 1157 ring
    --      >= 5 sits at 1312.3, outside it
    --   => the largest count the shipped search can return here is exactly 4.
    --      >= 1 sits at 805.9, outside the armed 732 ring  =>  armed returns 0.
    local _, bot, _, fx = load_frame()
    assert(#fx.creeps > 0, 'the fixture carries ' .. #fx.creeps .. ' creep samples')

    local loc = bot:GetLocation()
    local rShipped = bot:FindAoELocation(true, false, loc, 1157, NOVA_RADIUS, 0.5, 0)
    local rArmed = bot:FindAoELocation(true, false, loc, N_CAST_RANGE, NOVA_RADIUS, 0.5, 0)
    assert(rShipped.count == 4,
        'the shipped ring reaches a 4-creep centre and no 5: ' .. rShipped.count)
    assert(rArmed.count == 0,
        'the armed ring reaches nothing at all: ' .. rArmed.count)

    -- And the point it names is really 420.4 beyond her cast range -- the
    -- overshoot §3 priced, now read off the loader's own answer.
    local dOver = dist(loc.x, loc.y, rShipped.targetloc.x, rShipped.targetloc.y)
        - N_CAST_RANGE
    assert(dOver > 400 and dOver <= 1157 - N_CAST_RANGE + EPS,
        'the shipped centre is out of cast range by ' .. string.format('%.1f', dOver))
end

tests['§6 LIMIT: the wave post-filter still zeroes it, so no return site fires'] = function()
    -- The next blocker, measured rather than argued.  Between the search and
    -- the eight return sites sits
    --     J.GetInLocLaneCreepCount( bot, 1600, nRadius, targetloc ) <= 2
    --         -> nCanHurtCreepsLocationAoE.count = 0
    -- and that helper reads `bot:GetNearbyLaneCreeps`, which the loader does
    -- NOT build from the sample: creep UNITS are a second observation surface,
    -- and building them means answering GetHealth for units the dump gives no
    -- health for (X.cm_GetWeakestUnit asks every one of them).  A fabricated 0
    -- there would flow straight into "can I kill this creep" arithmetic, which
    -- is worse than an absent world.  So the AoE search is live and the wave
    -- census is not, and this node states which half is which.
    local J, bot = load_frame()
    local loc = bot:GetLocation()
    local r = bot:FindAoELocation(true, false, loc, 1157, NOVA_RADIUS, 0.5, 0)
    assert(r.count == 4, 'anti-vacuity: the search half is live here')
    assert(#bot:GetNearbyLaneCreeps(1600, true) == 0,
        'no creep units in the fixture world')
    assert(J.GetInLocLaneCreepCount(bot, 1600, NOVA_RADIUS, r.targetloc) == 0,
        'so the post-filter counts zero and zeroes the hurt count')
end

tests['§6 LIMIT: the dump carries no creep health, so the KILL search is unpriceable'] = function()
    -- `nCanKillCreepsLocationAoE` passes nMaxHealth = nova_damage, i.e. it
    -- counts only creeps the cast would KILL.  Creep samples are position and
    -- team only, so every number in §3 belongs to the HURT search
    -- (nMaxHealth = 0) and is an UPPER bound on the kill search's count.
    local _, _, _, fx = load_frame()
    for _, c in ipairs(fx.creeps) do
        assert(c.hp == nil and c.max_hp == nil,
            'a creep sample gained a health field -- reprice §3 before trusting it')
    end
    local fh = assert(io.open('bots/BotLib/hero_crystal_maiden.lua', 'r'))
    local src = fh:read('*a')
    fh:close()
    assert(src:find('nCanKillCreepsLocationAoE = bot:FindAoELocation( true, false, '
        .. 'bot:GetLocation(), nCreepSearch, nRadius, 0.5, nDamage )', 1, true),
        'the kill search still filters on nDamage')
end

tests['§6 LIMIT: reaching a creep site needs mode predicates the dump does not carry'] = function()
    -- Every creep return site sits under IsFarming / IsPushing / IsDefending /
    -- IsGoingOnSomeone, and a dump has no mode.  So this file prices the SEARCH
    -- and says nothing about whether she was in a mode that would have used it
    -- -- the same boundary GH #354 section 8 drew for the offline tool.
    local fh = assert(io.open('bots/BotLib/hero_crystal_maiden.lua', 'r'))
    local src = fh:read('*a')
    fh:close()
    local body = src:match('function X%.ConsiderQImpl%(%)(.-)\nend\n')
    assert(body ~= nil, 'ConsiderQImpl is still in the file')
    for _, sPred in ipairs({ 'J.IsFarming', 'J.IsPushing', 'J.IsDefending',
                            'J.IsGoingOnSomeone' }) do
        assert(body:find(sPred, 1, true), 'still gated on ' .. sPred)
    end
end

return tests
