-- [GH #492, director 2026-09-05] THE DECLARATION THAT COMES WITH THE REPAIR.
--
-- tests/mock/replay_fixture.lua now answers `GetExtrapolatedLocation`. Before
-- it did not, the name fell through bot_api.lua's `^Get -> 0` catch-all, every
-- shipped consumer indexed the 0 as a location, and the frame RAISED -- which
-- two `pcall` sweeps with two buckets for a three-valued read scored as a
-- measured "no". The frames deleted that way were the enemy-in-your-face ones,
-- i.e. the reason J.CanEnemyInterruptTpChannel exists. That is the defect the
-- repair closes, and it is priced in test_midsupmirror_checkability.lua.
--
-- ⭐ THIS FILE PRICES WHAT THE REPAIR DID **NOT** BUY, because that is the half
-- that will rot. A fixture is ONE INSTANT: make_fixture.py dumps x/y and no
-- velocity, no facing, no waypoint. So the mock cannot extrapolate; it answers
-- the current location, modelling every unit as STANDING STILL. The shipped
-- guard reads
--     nNow  = dist(bot, enemy:GetLocation())
--     nSoon = dist(bot, enemy:GetExtrapolatedLocation(0.5))
--     if nNow <= nReach or (... and nSoon < nNow - 10) then return true end
-- and under this model nSoon == nNow ALWAYS, so the second clause -- "it is
-- closing the gap on me" -- is unreachable on this corpus. The first clause,
-- "it can strike me right now", is answered honestly.
--
-- ⇒ EVERY domain count taken through this mock is a LOWER BOUND on
-- interruption, never an upper one, and it errs toward "the TP is safe".
--
-- ⚠️ WHY THIS IS A TEST AND NOT A COMMENT. The repo's standing lesson is that a
-- mock default states a world assumption nobody declared; a comment declaring
-- one is the same failure one step later, because nothing measures a comment.
-- The three assertions below are the measurement: the day make_fixture.py
-- starts carrying motion, [model] goes red and the standing-still story stops
-- being true silently instead of loudly.
--
-- ⭐⭐ 2026-09-05, GH #495 / owed_executions:mock_getvelocity_ultloc. THE SECOND
-- SITE JOINED THIS FILE, and that is the whole reason the ruling put it here
-- rather than in a file of its own. tests/mock/replay_fixture.lua now also
-- answers `GetVelocity` -- with the ZERO VECTOR, which is not a second world
-- assumption but THE SAME ONE said twice: every unit is standing still.
-- Two sites, one claim, and no test in between is how they drift: teach one of
-- them real motion and the other keeps answering the old world, silently, on
-- every frame. So the coupling is pinned as ARITHMETIC in the [coupling] leg
-- below -- `ext(t) == loc + vel*t` for several t -- which is false the instant
-- either site moves without the other, and cannot be satisfied by a comment.
--
-- ⚠️ WHAT THE SECOND REPAIR DID NOT BUY, measured rather than assumed.
-- J.GetUltLoc went from 503 raises / 0 answers to 0 raises / 503 answers on its
-- in-domain frames (tests/test_mockscalar_return_shape.lua carries that row).
-- But the location it answers is NEVER its interception point on this corpus:
--   * v == 0 collapses the lead term -- `dest = (t + 0.35) * v + y` == y; and
--   * `target:GetMovementDirectionStability()` is ITSELF an unrepaired
--     `^Get -> 0` catch-all name, so `< 0.4` is true on 503/503 in-domain
--     frames and dest is overwritten with the fountain-ward point regardless.
-- Measured split of the 503: 453 answer a Vector, 50 answer nil (out of range
-- or mana < 100), 2 take the IsDisabled branch. ⇒ THE LEAD-THE-TARGET MATHS IS
-- STILL UNWITNESSED. Anyone reading "GetUltLoc answers now" as "GetUltLoc is
-- exercised now" is reading the degenerate branch and calling it the helper.
-- The [degenerate] leg below is that sentence made falsifiable.

package.path = 'tests/?.lua;' .. package.path
local rf = require('mock.replay_fixture')

local FIX  = 'tests/fixtures/f_071423_luna_chase.lua'
local SUBJ = 'npc_dota_hero_luna'

local tests = {}

local function read_file(path)
    local f = assert(io.open(path, 'r'), path .. ' is not readable')
    local s = f:read('*a')
    f:close()
    return s
end

-- Every fixture opens with a generated `-- GENERATED by ... --t=... subject ...`
-- header, so a scanner that reads the raw bytes would answer "this fixture
-- carries velocity" for a fixture that merely MENTIONS the word in a comment.
-- That is not hypothetical prudence: the header is the first thing
-- make_fixture.py writes and it names the tool's own arguments. Cut each line
-- at its first `--`. Fixture data is numbers, bare keys and single-quoted
-- item/hero names, none of which contain `--`; the [model] leg proves the strip
-- did not eat the data by requiring an `x =` in every file AFTER stripping.
local function strip_line_comments(src)
    local out = {}
    for line in (src .. '\n'):gmatch('([^\n]*)\n') do
        local at = line:find('--', 1, true)
        out[#out + 1] = at and line:sub(1, at - 1) or line
    end
    return table.concat(out, '\n')
end

local function fixture_files()
    local p = assert(io.popen('ls tests/fixtures'))
    local files = {}
    for f in p:lines() do
        if f:match('^f_.*%.lua$') then files[#files + 1] = 'tests/fixtures/' .. f end
    end
    p:close()
    table.sort(files)
    return files
end

tests['[mock] the name answers a location on a real frame'] = function()
    local J, bot = rf.load(FIX, SUBJ)
    local near = J.GetNearbyHeroes(bot, 100000, true, BOT_MODE_NONE)
    assert(near ~= nil and #near > 0, FIX .. ' has no enemy hero to read')
    local n = 0
    for _, h in pairs(near) do
        local e = h:GetExtrapolatedLocation(0.5)
        assert(type(e) == 'table', 'GetExtrapolatedLocation answered a '
            .. type(e) .. ' -- the mock repair was reverted, and every count '
            .. 'in test_midsupmirror_checkability.lua reverts with it')
        assert(type(e.x) == 'number' and type(e.y) == 'number',
            'the answer is a table but not a location: it has no numeric x/y')
        n = n + 1
    end
    assert(n > 0, 'the loop body never ran -- this test asserts nothing')
end

tests['[mock] the velocity name answers a zero vector on a real frame'] = function()
    local J, bot = rf.load(FIX, SUBJ)
    local near = J.GetNearbyHeroes(bot, 100000, true, BOT_MODE_NONE)
    assert(near ~= nil and #near > 0, FIX .. ' has no enemy hero to read')
    local n = 0
    for _, h in pairs(near) do
        local v = h:GetVelocity()
        assert(type(v) == 'table', 'GetVelocity answered a ' .. type(v)
            .. ' -- the mock repair was reverted, and J.GetUltLoc goes back to '
            .. 'raising on all 503 of its in-domain frames')
        assert(type(v.x) == 'number' and type(v.y) == 'number',
            'the answer is a table but not a vector: it has no numeric x/y')
        assert(v.x == 0 and v.y == 0 and (v.z or 0) == 0,
            'GetVelocity answered a NON-ZERO velocity (' .. tostring(v.x) .. ', '
            .. tostring(v.y) .. ') while the corpus carries no motion -- that is '
            .. 'an invented world, and the [coupling] leg below says which other '
            .. 'site now disagrees with it')
        n = n + 1
    end
    assert(n > 0, 'the loop body never ran -- this test asserts nothing')
end

tests['[coupling] the two sites state ONE world, as arithmetic'] = function()
    -- The reason both repairs are pinned in one file. Under the declared model
    -- (standing still) the engine identity ext(t) = loc + vel*t holds for every
    -- t; under any OTHER shared model it also holds; it fails exactly when one
    -- site is taught motion and the other is not. So this is the drift alarm,
    -- and unlike the comments above it cannot be satisfied by prose.
    local J, bot = rf.load(FIX, SUBJ)
    local near = J.GetNearbyHeroes(bot, 100000, true, BOT_MODE_NONE)
    local n = 0
    for _, h in pairs(near) do
        local loc, vel = h:GetLocation(), h:GetVelocity()
        for _, t in ipairs({ 0, 0.5, 2 }) do
            local ext = h:GetExtrapolatedLocation(t)
            assert(math.abs(ext.x - (loc.x + vel.x * t)) < 1e-6
               and math.abs(ext.y - (loc.y + vel.y * t)) < 1e-6,
                'at t=' .. t .. ' the extrapolation and the velocity disagree: '
                .. 'ext=(' .. ext.x .. ', ' .. ext.y .. ') but loc+vel*t=('
                .. (loc.x + vel.x * t) .. ', ' .. (loc.y + vel.y * t) .. '). '
                .. 'ONE of tests/mock/replay_fixture.lua\'s two motion answers '
                .. 'was changed without the other, so the mock now holds two '
                .. 'contradictory worlds. Fix both, then re-take every domain '
                .. 'that rests on either (test_set.md §EF.1 / §EL.6, the counts '
                .. 'in test_mockscalar_return_shape.lua).')
        end
        n = n + 1
    end
    assert(n > 0, 'the loop body never ran -- this test asserts nothing')
end

tests['[degenerate] GetUltLoc answers, but never from its lead-the-target arc'] = function()
    -- "It answers now" is not "it is exercised now". Two independent collapses
    -- stand between this helper and the interception maths it exists for, and
    -- BOTH are mock defaults rather than facts about the game:
    --   (1) v == 0            -> `dest = (t + 0.35) * v + y` == y
    --   (2) stability == 0    -> `< 0.4` true -> dest overwritten fountain-ward
    -- (2) is a `^Get -> 0` catch-all name that is NOT on the three-name roster
    -- of GH #495 (it is type-correct: the engine returns a number), which is
    -- why nothing else in the harness is watching it. Corpus-wide at the time
    -- of writing: 503/503 in-domain frames take (2); 453 answer a Vector, 50
    -- answer nil, 2 take the IsDisabled branch.
    local J, bot = rf.load(FIX, SUBJ)
    local near = J.GetNearbyHeroes(bot, 1600, true, BOT_MODE_NONE)
    assert(near ~= nil and #near > 0, FIX .. ' has no enemy inside 1600')
    local n = 0
    for _, h in pairs(near) do
        assert(h:GetVelocity().x == 0 and h:GetVelocity().y == 0,
            'collapse (1) is gone: the lead term can now move dest')
        assert(h:GetMovementDirectionStability() < 0.4,
            'collapse (2) is gone: GetMovementDirectionStability was repaired, '
            .. 'so dest is no longer forced fountain-ward. That is good news '
            .. 'and it invalidates this pricing -- re-take the GetUltLoc row in '
            .. 'tests/test_mockscalar_return_shape.lua and say so.')
        n = n + 1
    end
    assert(n > 0, 'the loop body never ran -- this test asserts nothing')
    -- And the helper does reach an answer, which is what the repair bought.
    local ok, ans = pcall(J.GetUltLoc, bot, near[1], 0, 2000, 1000)
    assert(ok, 'J.GetUltLoc still raises on a real frame: ' .. tostring(ans))
    assert(ans == nil or type(ans) == 'table',
        'J.GetUltLoc answered a ' .. type(ans) .. ', not a location or nil')
end

tests['[model] no fixture carries motion, so standing-still is forced'] = function()
    -- The scanner is proved against a key that IS there before it is trusted
    -- about keys that are not: a regex that matches nothing would otherwise
    -- report "no fixture carries velocity" for the rest of time.
    local files = fixture_files()
    assert(#files >= 100, 'only ' .. #files .. ' fixtures found -- the corpus '
        .. 'shrank or the glob broke; either way re-read before trusting this')
    local nWithX, offenders = 0, {}
    for _, path in ipairs(files) do
        local src = strip_line_comments(read_file(path))
        if src:find('%f[%w]x%s*=%s*%-?%d') then nWithX = nWithX + 1 end
        for _, key in ipairs({ 'vel', 'velocity', 'facing', 'vx', 'vy',
                               'speed', 'waypoint', 'heading' }) do
            if src:find('%f[%w]' .. key .. '%s*=') then
                offenders[#offenders + 1] = path .. ' carries `' .. key .. '`'
            end
        end
    end
    assert(nWithX == #files, 'the scanner found an `x =` in only ' .. nWithX
        .. ' of ' .. #files .. ' fixtures -- it is not reading what it thinks '
        .. 'it is, so its negative answer below means nothing')
    assert(#offenders == 0, 'a fixture now carries motion state:\n  '
        .. table.concat(offenders, '\n  ')
        .. '\nThe standing-still model in tests/mock/replay_fixture.lua is no '
        .. 'longer FORCED by the corpus -- it is now a CHOICE, and an '
        .. 'undeclared one. It is stated at TWO sites and both must be taught '
        .. 'the real motion together (the [coupling] leg above is what refuses '
        .. 'to let you do only one): GetExtrapolatedLocation, which answers the '
        .. 'current location, and GetVelocity, which answers the zero vector. '
        .. 'Then re-take every domain that rests on either: test_set.md §EF.1 '
        .. 'and §EL.6, the int_true/int_in_domain counts in '
        .. 'test_midsupmirror_checkability.lua, and the GetUltLoc carrier row '
        .. 'in test_mockscalar_return_shape.lua.')
end

tests['[consequence] the closing-the-gap clause cannot fire on this corpus'] = function()
    -- Driven on real frames rather than argued from the model: for every enemy
    -- the guard would scan, the two distances it compares are equal, so
    -- `nSoon < nNow - 10` is false by arithmetic and not by assumption.
    local J, bot = rf.load(FIX, SUBJ)
    local vBotLoc = bot:GetLocation()
    local near = J.GetNearbyHeroes(bot, 100000, true, BOT_MODE_NONE)
    local n = 0
    for _, h in pairs(near) do
        local nNow  = J.GetLocationToLocationDistance(vBotLoc, h:GetLocation())
        local nSoon = J.GetLocationToLocationDistance(vBotLoc,
                          h:GetExtrapolatedLocation(0.5))
        assert(nSoon == nNow, 'the extrapolated distance (' .. tostring(nSoon)
            .. ') differs from the current one (' .. tostring(nNow)
            .. ') -- the mock started extrapolating for real. That is good '
            .. 'news and it invalidates this pricing: the guard can now fire '
            .. 'on its second clause, so re-take the domains named above.')
        assert(not (nSoon < nNow - 10), 'the closing-the-gap clause became '
            .. 'reachable -- re-price')
        n = n + 1
    end
    assert(n > 0, 'the loop body never ran -- this test asserts nothing')
end

tests['[guard] and the first clause DOES fire, so the repair is not cosmetic'] = function()
    -- The whole point of the repair is that the guard now reaches an answer
    -- instead of raising. Stated on the frame that was the standing example of
    -- the censoring (test_midsupmirror_checkability.lua's CENSORED frame).
    local J, bot = rf.load(FIX, SUBJ)
    J.IsSoakCandidate = function() return false end
    local ok, ans = pcall(J.CanEnemyInterruptTpChannel, bot)
    assert(ok, 'J.CanEnemyInterruptTpChannel still raises on the frame the '
        .. 'repair was written for: ' .. tostring(ans))
    assert(type(ans) == 'boolean', 'the guard answered a ' .. type(ans))
    -- On THIS frame luna has slardar inside attack reach; that is the whole
    -- reason it was the censored example. A corpus-wide count (257 in domain,
    -- 0 raising, 73 answering true) lives in test_midsupmirror_checkability.lua.
    assert(ans == true, 'the guard answers FALSE on the frame where luna is '
        .. 'being hit at melee range -- the first clause is not doing the work '
        .. 'this pricing says it does; re-read before trusting the 73')
end

return tests
