-- [hero, GH #88] Tiny's Tree Grab guard: the deleted clause was a no-op, and
-- the repair everyone reaches for first is one we cannot validate.
--
-- THE SITE (bots/BotLib/hero_tiny.lua, X.ConsiderTreeGrab). It used to read:
--
--     if not J.IsRetreating(bot)
--     and bot:GetHealth() > 0.15            <-- deleted
--     and bot:DistanceFromFountain() > 800
--     and nEnemyHeroes ~= nil and #nEnemyHeroes == 0
--
-- GetHealth() returns HIT POINTS, not a fraction. X.SkillsComplement returns
-- early on J.CanNotUseAbility(bot), whose first clause is `not bot:IsAlive()`,
-- so the line only ever ran on a unit holding at least 1 hp: it was TRUE on
-- every frame it could be evaluated in. Deleting it is behaviour-equivalent;
-- section 2 drives the real function to show that, on the exact frame the
-- intended repair would have vetoed.
--
-- WHY IT IS DELETED AND NOT REPAIRED TO `J.GetHP(bot) > 0.15`.
--   (a) is structurally unbuyable for Tiny. The soak farm's drafter reads
--       bots/Customize/soak_pool.lua, generated by gen_soak_pool.py from
--       tools/batch_test/soak/hero_pool.txt -- a curated 41-hero pool that does
--       not contain Tiny. The archive agrees independently: seed_roster_index
--       over the banked corpus reports 0 Tiny appearances in 11048 banked
--       validation games across 112 seeds, and the union of every roster those
--       seeds ever drafted is exactly the 41 pool heroes. seed_draft.py answers
--       `--find tiny` with "not in pool". A gate on a hero no corpus can carry
--       is armed == shipped end to end -- the axeblink trap, by construction,
--       and known before spending anything rather than after.
--   (c) is weak on its own terms. The two surviving clauses already require
--       that Tiny is not retreating and that no enemy hero is within 700, and
--       Tree Grab is an instant self-buff that neither channels nor displaces
--       him. The frames the repair would have vetoed are frames where nothing
--       was near enough to punish the cast.
--
-- HONEST BOUNDS.
--   * Nothing here is a real frame. There cannot be one: the corpus contains no
--     Tiny, which is the finding. Section 1 is a census of files in this repo
--     (checkable), section 2 drives the shipped function under the mock API,
--     section 3 is source text. No claim below rests on a replay.
--   * "Behaviour-equivalent" is an argument about the engine's units contract
--     (an alive unit holds >= 1 hp) plus the IsAlive early-out, not a measured
--     result. Section 2 makes the argument falsifiable at the one place it
--     matters: the decision this function returns at 1 hp.
--   * The census numbers in the paragraph above are recorded, not re-derived --
--     they need the S3 archive. What section 1 pins is the *repo-local* half:
--     the pool file that produces them. If Tiny enters that pool, the recorded
--     numbers are stale and this whole disposition must be reopened.

package.path = 'tests/?.lua;' .. package.path
local api = require('mock.bot_api')

local TINY_SRC = 'bots/BotLib/hero_tiny.lua'
local POOL_SRC = 'tools/batch_test/soak/hero_pool.txt'
local TREE_ID = 77           -- an arbitrary tree handle; the engine's are ints

local tests = {}

local function read_file(path)
    local fh = assert(io.open(path, 'r'), 'cannot open ' .. path)
    local s = fh:read('*a')
    fh:close()
    return s
end

-- ---------------------------------------------------------------------------
-- 1. The revival tripwire. This is the single fact that would make condition
--    (a) buyable, so it is the single fact worth ratcheting.

local function pool_heroes()
    local names = {}
    for line in read_file(POOL_SRC):gmatch('[^\n]+') do
        line = line:gsub('^%s+', ''):gsub('%s+$', '')
        if line ~= '' and not line:match('^#') then
            names[#names + 1] = line:match('^([%w_]+)')
        end
    end
    return names
end

tests['[GH #88] the soak draft pool still cannot carry Tiny'] = function()
    local names = pool_heroes()
    assert(#names == 41,
        'the soak pool moved from 41 heroes to ' .. #names .. '. That is fine, '
        .. 'but re-read GH #88: the "condition (a) is unbuyable" disposition '
        .. 'for hero_tiny.lua is a statement about this file.')
    for _, n in ipairs(names) do
        assert(n ~= 'tiny',
            'Tiny is now in the soak draft pool (' .. POOL_SRC .. '). Condition '
            .. '(a) for a Tree Grab hp floor just became buyable, so the '
            .. 'deletion recorded in X.ConsiderTreeGrab is no longer the '
            .. 'forced answer -- reopen GH #88 and decide it on evidence.')
    end
end

-- ---------------------------------------------------------------------------
-- 2. The behavioural half: drive the shipped X.ConsiderTreeGrab.

--- A Tiny standing in his own jungle at 1 hp with a tree in reach: exactly the
--- frame `J.GetHP(bot) > 0.15` would have vetoed, and the frame the shipped
--- clauses have no quarrel with.
local function make_frame(over)
    over = over or {}
    api.reset_modules()

    -- J.GetHP reads the UN-HOOKED getters for own-team units, so a fractional
    -- read of the subject needs both pairs supplied or it divides by nil.
    local spec = {
        GetHealth = over.hp or 1,
        GetMaxHealth = 1000,
        OriginalGetHealth = over.hp or 1,
        OriginalGetMaxHealth = 1000,
        DistanceFromFountain = over.fountain or 3000,
        GetNearbyTrees = function() return { TREE_ID } end,
        GetNearbyHeroes = function() return over.nearby or {} end,
    }
    if over.mode then
        spec.GetActiveMode = over.mode
        spec.GetActiveModeDesire = over.mode_desire or 0.9
    end

    local bot = api.MakeHero('npc_dota_hero_tiny', spec)
    api.install({ bot = bot })
    _G.GetTreeLocation = function() return api.Vector(1000, 1000, 128) end

    local X = dofile(TINY_SRC)
    local J = require(GetScriptDirectory() .. '/FunLib/jmz_func')

    -- Tree Grab off cooldown. The mock auto-creates ability handles whose
    -- Is* methods default to false, so this has to be said out loud.
    bot:GetAbilityByName('tiny_tree_grab').__spec.IsFullyCastable = true

    return X, bot, J
end

local function make_enemy()
    return api.MakeHero('npc_dota_hero_lina', {
        IsNull = false, CanBeSeen = true, IsAlive = true,
        IsInvulnerable = false, IsIllusion = false,
        GetTeam = 3, -- TEAM_DIRE, opposite the subject
        GetLocation = api.Vector(300, 0, 0),
    })
end

tests['[GH #88] ground truth: the test frame is inside the repair\'s domain'] = function()
    local _, bot, J = make_frame()
    assert(bot:GetHealth() == 1, 'the subject holds the engine minimum, 1 hp')
    assert(J.GetHP(bot) <= 0.15,
        'the frame must sit BELOW the 0.15 floor the repair would have '
        .. 'installed, or section 2 proves nothing; got ' .. tostring(J.GetHP(bot)))
    -- ...and above zero, because a dead Tiny never reaches this function at all.
    assert(J.GetHP(bot) > 0, 'an alive unit holds at least 1 hp')
    assert(J.CanNotUseAbility(bot) == false,
        'the frame must actually reach X.ConsiderTreeGrab through '
        .. 'X.SkillsComplement\'s guard')
end

tests['[GH #88] at 1 hp with nothing nearby, Tree Grab is still taken'] = function()
    local X, _, _ = make_frame()
    local desire, target = X.ConsiderTreeGrab()
    assert(desire == BOT_ACTION_DESIRE_HIGH,
        'the shipped decision at 1 hp must be unchanged by the deletion; got '
        .. tostring(desire))
    assert(target == TREE_ID, 'and it must still name the nearby tree')
end

-- The same frame, one clause at a time, so this file can tell the difference
-- between "the guard is inert" and "the whole function is inert".

tests['[GH #88] an enemy hero within 700 still denies the grab'] = function()
    local X = make_frame({ nearby = { make_enemy() } })
    local desire = X.ConsiderTreeGrab()
    assert(desire == BOT_ACTION_DESIRE_NONE,
        'the surviving `#nEnemyHeroes == 0` clause must still bite; got '
        .. tostring(desire))
end

tests['[GH #88] standing in the fountain still denies the grab'] = function()
    local X = make_frame({ fountain = 400 })
    local desire = X.ConsiderTreeGrab()
    assert(desire == BOT_ACTION_DESIRE_NONE,
        'the surviving `DistanceFromFountain() > 800` clause must still bite; '
        .. 'got ' .. tostring(desire))
end

tests['[GH #88] retreating still denies the grab'] = function()
    local X = make_frame({ mode = BOT_MODE_RETREAT, mode_desire = 0.9 })
    local desire = X.ConsiderTreeGrab()
    assert(desire == BOT_ACTION_DESIRE_NONE,
        'the surviving `not J.IsRetreating(bot)` clause must still bite; got '
        .. tostring(desire))
end

-- ---------------------------------------------------------------------------
-- 3. Source: no hp term may reappear in this function without a decision.

tests['[GH #88] X.ConsiderTreeGrab carries no hp term in code'] = function()
    local src = read_file(TINY_SRC)
    local body = src:match('function X%.ConsiderTreeGrab%b()%s*(.-)\nend')
    assert(body, 'X.ConsiderTreeGrab must still exist in ' .. TINY_SRC)

    for line in body:gmatch('[^\n]+') do
        -- Comment lines are the prose ABOUT the defect and must not count.
        if not line:match('^%s*%-%-') then
            assert(not line:find('GetHealth', 1, true),
                'a raw GetHealth() comparison is back in X.ConsiderTreeGrab -- '
                .. 'that is the GH #88 defect verbatim: ' .. line)
            assert(not line:find('GetHP', 1, true),
                'an hp floor has been added to X.ConsiderTreeGrab. That is a '
                .. 'NEW VETO on a hero the soak farm cannot draft, so it cannot '
                .. 'buy condition (a) evidence -- see GH #88 before shipping '
                .. 'it: ' .. line)
        end
    end
end

return tests
