#!/usr/bin/env python3
"""Generate bots/Customize/soak_pool.lua for the in-game soak drafter.

Just the flat hero list — team partitioning is done in-game per clock bucket
(custom_loader.ApplySoakDraft), so order here doesn't matter.

Usage: gen_soak_pool.py --out /path/to/bots/Customize/soak_pool.lua
"""
import argparse
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    heroes = []
    with open(os.path.join(HERE, "hero_pool.txt")) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            heroes.append(line.split(",")[0])

    with open(args.out, "w") as f:
        f.write("-- generated by gen_soak_pool.py; farm-instance only, never shipped\n")
        f.write("return {\n")
        for name in heroes:
            f.write(f"    '{name}',\n")
        f.write("}\n")
    print(f"wrote {args.out}: {len(heroes)} heroes")


if __name__ == "__main__":
    main()
