#!/usr/bin/env python3
"""Generate bots/Customize/soak_pool.lua for the in-game soak drafter.

Emits {name, role} pairs (role = 'core' | 'support' | 'either' from
hero_pool.txt) so custom_loader.ApplySoakDraft can build role-balanced,
position-ordered comps (cores -> pos 1-3 slots, supports -> pos 4-5 slots).

Usage: gen_soak_pool.py --out /path/to/bots/Customize/soak_pool.lua
"""
import argparse
import os

HERE = os.path.dirname(os.path.abspath(__file__))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    heroes = []
    with open(os.path.join(HERE, "hero_pool.txt")) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = [p.strip() for p in line.split(",")]
            name = parts[0]
            pos_field = parts[1] if len(parts) > 1 else ""
            pos = [int(p) for p in pos_field.split("/") if p.isdigit() and 1 <= int(p) <= 5]
            if not pos:
                pos = [1, 2, 3, 4, 5]  # unspecified -> any position
            heroes.append((name, pos))

    with open(args.out, "w") as f:
        f.write("-- generated by gen_soak_pool.py; farm-instance only, never shipped\n")
        f.write("return {\n")
        for name, pos in heroes:
            f.write(f"    {{ name = '{name}', pos = {{ {', '.join(str(p) for p in pos)} }} }},\n")
        f.write("}\n")
    print(f"wrote {args.out}: {len(heroes)} heroes with positions")


if __name__ == "__main__":
    main()
