-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- tl_260905_010205_luna_outchan @ t=1349.5 (22:29), subject luna.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = 'tl_260905_010205_luna_outchan', time = 1349.5, window = 5.0,
  self = 'npc_dota_hero_luna',
  units = {
    { name = 'npc_dota_hero_axe', team = 2, x = -5096.2, y = -5112.5, hp = 3296, max_hp = 3296, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_bristleback', team = 3, x = 2134.4, y = 2405.6, hp = 0, max_hp = 0, mp = 0, max_mp = 0, level = 1, alive = false, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_crystal_maiden', team = 2, x = -7985.4, y = -1135.0, hp = 2366, max_hp = 2366, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_luna', team = 2, x = 3474.5, y = -715.5, hp = 3760, max_hp = 3760, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_nevermore', team = 2, x = 5028.3, y = -3741.3, hp = 3100, max_hp = 3100, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 3, x = 7027.9, y = 3521.2, hp = 2452, max_hp = 2452, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_pudge', team = 3, x = 7441.0, y = 2155.0, hp = 2664, max_hp = 2664, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_spirit_breaker', team = 3, x = 5509.3, y = 1651.2, hp = 2628, max_hp = 2628, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_tidehunter', team = 3, x = 2451.2, y = 6777.7, hp = 3393, max_hp = 3393, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
    { name = 'npc_dota_hero_venomancer', team = 2, x = 5993.2, y = -3195.0, hp = 2212, max_hp = 2212, mp = 0, max_mp = 0, level = 1, alive = true, tp_cd = 0, net_worth = 0, items = {  },
      abilities = {  }, },
  },
  buildings = {
    { name = 'watch_tower', team = 2, x = -4096, y = -448, alive = true, hp = 1.0, },
    { name = 'watch_tower', team = 3, x = 3392, y = -448, alive = true, hp = 1.0, },
  },
  observed = {
    burst = {
    },
    died_after = nil,
  },
}
