-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 011405 @ t=51.5 (0:51), subject jakiro.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '011405', time = 51.5, window = 5.0,
  self = 'npc_dota_hero_jakiro',
  units = {
    { name = 'npc_dota_hero_axe', team = 2, x = -6147.2, y = 4589.3, hp = 501, max_hp = 736, mp = 295, max_mp = 327, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_stick', 'ironwood_branch', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'axe_berserkers_call', level = 0, cd = 0 }, { name = 'axe_battle_hunger', level = 1, cd = 3.4 }, { name = 'axe_counter_helix', level = 0, cd = 0 }, { name = 'axe_culling_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = 5209.7, y = -5854.2, hp = 526, max_hp = 714, mp = 327, max_mp = 327, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_stick', 'ironwood_branch', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 0, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 0, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 3, x = 6415.9, y = -4709.0, hp = 648, max_hp = 648, mp = 355, max_mp = 399, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_stick', 'ironwood_branch', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 1, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 0, cd = 0 }, { name = 'death_prophet_exorcism', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 2, x = 5532.8, y = -6246.4, hp = 582, max_hp = 758, mp = 471, max_mp = 471, level = 1, alive = true, tp_cd = 0, items = { 'mantle', 'clarity', 'tango', 'ironwood_branch', 'ironwood_branch', 'circlet', 'blood_grenade', '', '' },
      abilities = { { name = 'jakiro_dual_breath', level = 1, cd = 0 }, { name = 'jakiro_ice_path', level = 0, cd = 0 }, { name = 'jakiro_liquid_fire', level = 0, cd = 0 }, { name = 'jakiro_liquid_ice', level = 0, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = -471.0, y = -479.3, hp = 372, max_hp = 691, mp = 495, max_mp = 584, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'null_talisman', '', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 1, cd = 6.1 }, { name = 'lina_light_strike_array', level = 0, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_pudge', team = 3, x = -6265.3, y = 4797.7, hp = 720, max_hp = 720, mp = 259, max_mp = 267, level = 1, alive = true, tp_cd = 0, items = { '', 'tango', 'flask', '', 'wind_lace', 'blood_grenade', '', '', '' },
      abilities = { { name = 'pudge_meat_hook', level = 1, cd = 2.2 }, { name = 'pudge_rot', level = 0, cd = 0 }, { name = 'pudge_flesh_heap', level = 0, cd = 0 }, { name = 'pudge_dismember', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_shadow_shaman', team = 2, x = -5988.8, y = 4429.9, hp = 676, max_hp = 676, mp = 300, max_mp = 387, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'clarity', '', 'faerie_fire', 'blood_grenade', 'magic_wand', '', '', '' },
      abilities = { { name = 'shadow_shaman_ether_shock', level = 1, cd = 11.4 }, { name = 'shadow_shaman_voodoo', level = 0, cd = 0 }, { name = 'shadow_shaman_shackles', level = 0, cd = 0 }, { name = 'shadow_shaman_fowl_play', level = 1, cd = 0 }, { name = 'shadow_shaman_mass_serpent_ward', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = 5884.2, y = -4910.9, hp = 530, max_hp = 582, mp = 279, max_mp = 279, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'magic_stick', 'clarity', 'slippers', 'circlet', 'ironwood_branch', 'ironwood_branch', '' },
      abilities = { { name = 'sniper_shrapnel', level = 0, cd = 0 }, { name = 'sniper_headshot', level = 1, cd = 0 }, { name = 'sniper_take_aim', level = 0, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = -5957.8, y = 4981.8, hp = 401, max_hp = 626, mp = 283, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', '', '', 'faerie_fire', 'enchanted_mango', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 0, cd = 0 }, { name = 'vengeful_spirit_wave_of_terror', level = 1, cd = 11.2 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 3, x = 376.1, y = 154.8, hp = 514, max_hp = 670, mp = 197, max_mp = 411, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'empty_bottle', '', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 1, cd = 0 }, { name = 'zuus_lightning_bolt', level = 0, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 22.6 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
    },
    died_after = 154.7,
  },
}
