-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 013254 @ t=37.3 (0:37), subject lina.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '013254', time = 37.3, window = 5.0,
  self = 'npc_dota_hero_lina',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = 5858.7, y = -5874.6, hp = 714, max_hp = 714, mp = 327, max_mp = 327, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_stick', 'ironwood_branch', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 0, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 0, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ember_spirit', team = 3, x = -238.1, y = -54.7, hp = 518, max_hp = 626, mp = 339, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'quelling_blade', '', '', '', '' },
      abilities = { { name = 'ember_spirit_searing_chains', level = 0, cd = 0 }, { name = 'ember_spirit_sleight_of_fist', level = 0, cd = 0 }, { name = 'ember_spirit_flame_guard', level = 1, cd = 0 }, { name = 'ember_spirit_activate_fire_remnant', level = 0, cd = 0 }, { name = 'ember_spirit_immolation', level = 1, cd = 0 }, { name = 'ember_spirit_fire_remnant', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = 5576.9, y = -5503.9, hp = 610, max_hp = 610, mp = 411, max_mp = 411, level = 1, alive = true, tp_cd = 0, items = { '', 'tango', 'faerie_fire', 'enchanted_mango', 'blood_grenade', '', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 1, cd = 0 }, { name = 'lich_frost_shield', level = 0, cd = 0 }, { name = 'lich_sinister_gaze', level = 0, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = -858.6, y = -830.1, hp = 692, max_hp = 692, mp = 538, max_mp = 584, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'null_talisman', '', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 1, cd = 0 }, { name = 'lina_light_strike_array', level = 0, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 3, x = -5838.1, y = 5341.0, hp = 492, max_hp = 654, mp = 303, max_mp = 387, level = 1, alive = true, tp_cd = 0, items = { 'mantle', 'blood_grenade', 'tango', 'ironwood_branch', 'ironwood_branch', 'circlet', '', '', '' },
      abilities = { { name = 'lion_impale', level = 1, cd = 9.4 }, { name = 'lion_voodoo', level = 0, cd = 0 }, { name = 'lion_mana_drain', level = 0, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6272.4, y = -5086.0, hp = 692, max_hp = 692, mp = 279, max_mp = 279, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 0, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 1, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 0, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_spirit_breaker', team = 3, x = 5863.6, y = -5060.8, hp = 940, max_hp = 940, mp = 291, max_mp = 291, level = 1, alive = true, tp_cd = 0, items = { 'quelling_blade', 'tango', 'ironwood_branch', 'ironwood_branch', 'bracer', '', '', '', '' },
      abilities = { { name = 'spirit_breaker_charge_of_darkness', level = 0, cd = 0 }, { name = 'spirit_breaker_bulldoze', level = 0, cd = 0 }, { name = 'spirit_breaker_greater_bash', level = 1, cd = 0 }, { name = 'spirit_breaker_nether_strike', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = -5714.9, y = 5346.7, hp = 544, max_hp = 626, mp = 302, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', '', '', 'faerie_fire', 'enchanted_mango', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 0, cd = 0 }, { name = 'vengeful_spirit_wave_of_terror', level = 1, cd = 13.1 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_viper', team = 2, x = -5882.7, y = 4847.2, hp = 552, max_hp = 692, mp = 302, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'magic_stick', 'ironwood_branch', 'enchanted_mango', 'circlet', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'viper_poison_attack', level = 1, cd = 0 }, { name = 'viper_nethertoxin', level = 0, cd = 0 }, { name = 'viper_corrosive_skin', level = 0, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 2, x = -6348.5, y = 4524.8, hp = 574, max_hp = 676, mp = 299, max_mp = 375, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'enchanted_mango', '', '', 'blood_grenade', 'magic_wand', '', '', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 1, cd = 17.2 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 0, cd = 0 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
    },
    died_after = 502.0,
  },
}
