-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260725_045650_slot1 @ t=419.0 (6:59), subject lion.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260725_045650_slot1', time = 419.0, window = 5.0,
  self = 'npc_dota_hero_lion',
  units = {
    { name = 'npc_dota_hero_axe', team = 3, x = 6463.2, y = 1629.6, hp = 1894, max_hp = 1894, mp = 368, max_mp = 368, level = 8, alive = true, tp_cd = 15.7, items = { 'vanguard', 'helm_of_iron_will', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'axe_berserkers_call', level = 1, cd = 0 }, { name = 'axe_battle_hunger', level = 2, cd = 0 }, { name = 'axe_counter_helix', level = 4, cd = 0 }, { name = 'axe_culling_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_centaur', team = 2, x = -6220.5, y = 1251.2, hp = 0, max_hp = 0, mp = 339, max_mp = 339, level = 4, alive = false, tp_cd = 16, items = { 'helm_of_iron_will', 'magic_wand', 'tango', 'quelling_blade', 'ring_of_protection', '', '', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 2, cd = 0 }, { name = 'centaur_double_edge', level = 2, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 0, cd = 0 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 3, x = -6220.5, y = 1251.2, hp = 1344, max_hp = 1421, mp = 747, max_mp = 848, level = 10, alive = true, tp_cd = 0, items = { 'plate_mail', 'magic_wand', 'arcane_boots', 'faerie_fire', 'tango', 'empty_bottle', 'clarity', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 4, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 4, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 95.2 }, { name = 'special_bonus_h_p200', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_earthshaker', team = 3, x = 6439.6, y = -1901.8, hp = 1352, max_hp = 1352, mp = 668, max_mp = 668, level = 9, alive = true, tp_cd = 9.9, items = { 'urn_of_shadows', 'sentry_ward', 'magic_wand', '', 'arcane_boots', 'dustof_appearance', '', '', '' },
      abilities = { { name = 'earthshaker_fissure', level = 3, cd = 0 }, { name = 'earthshaker_enchant_totem', level = 1, cd = 0 }, { name = 'earthshaker_aftershock', level = 4, cd = 0 }, { name = 'earthshaker_echo_slam', level = 1, cd = 22.2 }, { name = 'earthshaker_slugger', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = 4236.3, y = -4454.9, hp = 568, max_hp = 978, mp = 491, max_mp = 908, level = 7, alive = true, tp_cd = 8.6, items = { 'ring_of_regeneration', 'urn_of_shadows', 'magic_wand', '', '', 'arcane_boots', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 1, cd = 10.3 }, { name = 'lina_light_strike_array', level = 1, cd = 0 }, { name = 'lina_fiery_soul', level = 4, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 2, x = 5245.9, y = -5911.2, hp = 789, max_hp = 978, mp = 708, max_mp = 708, level = 8, alive = true, tp_cd = 0.7, items = { 'null_talisman', 'tranquil_boots', 'flask', 'magic_wand', 'ring_of_regeneration', 'observer_ward', '', 'blood_grenade', '' },
      abilities = { { name = 'lion_impale', level = 4, cd = 0 }, { name = 'lion_voodoo', level = 1, cd = 0 }, { name = 'lion_mana_drain', level = 2, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 1, cd = 31.9 } } },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 2, x = 1493.0, y = -6086.8, hp = 762, max_hp = 1176, mp = 977, max_mp = 1244, level = 8, alive = true, tp_cd = 35.1, items = { 'magic_wand', 'null_talisman', 'power_treads', 'blitz_knuckles', 'null_talisman', '', '', '', '' },
      abilities = { { name = 'obsidian_destroyer_arcane_orb', level = 1, cd = 0 }, { name = 'obsidian_destroyer_astral_imprisonment', level = 4, cd = 0 }, { name = 'obsidian_destroyer_objurgation', level = 0, cd = 0 }, { name = 'obsidian_destroyer_sanity_eclipse', level = 1, cd = 62.1 } } },
    { name = 'npc_dota_hero_phantom_assassin', team = 2, x = 1254.1, y = -6167.2, hp = 846, max_hp = 846, mp = 387, max_mp = 387, level = 6, alive = true, tp_cd = 33.1, items = { 'boots_of_speed', '', '', 'quelling_blade', 'orb_of_corrosion', 'magic_wand', '', '', '' },
      abilities = { { name = 'phantom_assassin_stifling_dagger', level = 3, cd = 0 }, { name = 'phantom_assassin_phantom_strike', level = 1, cd = 0 }, { name = 'phantom_assassin_blur', level = 1, cd = 0 }, { name = 'phantom_assassin_immaterial', level = 1, cd = 0 }, { name = 'phantom_assassin_coupde_grace', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 3, x = -6228.6, y = 1991.5, hp = 1323, max_hp = 1468, mp = 420, max_mp = 423, level = 7, alive = true, tp_cd = 0, items = { 'power_treads', '', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'slardar_sprint', level = 1, cd = 0 }, { name = 'slardar_slithereen_crush', level = 1, cd = 0 }, { name = 'slardar_bash', level = 4, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_venomancer', team = 3, x = -5658.5, y = 2923.8, hp = 442, max_hp = 911, mp = 468, max_mp = 495, level = 7, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'tango', 'observer_ward', 'magic_wand', 'tranquil_boots', 'dustof_appearance', 'clarity', 'famango', 'blood_grenade' },
      abilities = { { name = 'venomancer_venomous_gale', level = 1, cd = 3.7 }, { name = 'venomancer_snakebite', level = 4, cd = 0 }, { name = 'venomancer_plague_ward', level = 1, cd = 0 }, { name = 'venomancer_noxious_plague', level = 1, cd = 14.1 } } },
  },
  observed = {
    burst = {
    },
    died_after = 18.5,
  },
}
