-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260725_050713_slot1 @ t=573.0 (9:33), subject earthshaker.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260725_050713_slot1', time = 573.0, window = 5.0,
  self = 'npc_dota_hero_earthshaker',
  units = {
    { name = 'npc_dota_hero_axe', team = 3, x = 1196.6, y = -4152.0, hp = 2136, max_hp = 2136, mp = 524, max_mp = 543, level = 11, alive = true, tp_cd = 11.7, items = { 'crimson_guard', 'power_treads', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'axe_berserkers_call', level = 1, cd = 0 }, { name = 'axe_battle_hunger', level = 4, cd = 0 }, { name = 'axe_counter_helix', level = 4, cd = 0 }, { name = 'axe_culling_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_centaur', team = 2, x = -6355.1, y = 2485.4, hp = 593, max_hp = 1461, mp = 276, max_mp = 423, level = 8, alive = true, tp_cd = 0, items = { '', 'magic_wand', 'helm_of_iron_will', 'quelling_blade', 'ring_of_protection', 'phase_boots', '', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 3, cd = 0 }, { name = 'centaur_double_edge', level = 4, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 1, cd = 70.8 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 3, x = 1532.4, y = 1469.4, hp = 1464, max_hp = 1464, mp = 872, max_mp = 872, level = 10, alive = true, tp_cd = 0, items = { 'plate_mail', 'magic_wand', 'arcane_boots', 'splint_mail', 'circlet', 'empty_bottle', 'faerie_fire', 'tango', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 4, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 4, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 60.8 }, { name = 'special_bonus_h_p200', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_earthshaker', team = 3, x = 3690.7, y = -5410.8, hp = 1376, max_hp = 1403, mp = 461, max_mp = 668, level = 9, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'sentry_ward', 'magic_wand', 'blood_grenade', 'arcane_boots', '', '', '', '' },
      abilities = { { name = 'earthshaker_fissure', level = 3, cd = 12.2 }, { name = 'earthshaker_enchant_totem', level = 1, cd = 0 }, { name = 'earthshaker_aftershock', level = 4, cd = 0 }, { name = 'earthshaker_echo_slam', level = 1, cd = 103.9 }, { name = 'earthshaker_slugger', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = -781.3, y = -172.4, hp = 1032, max_hp = 1087, mp = 1004, max_mp = 1004, level = 9, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'sentry_ward', 'magic_wand', 'chain_mail', 'headdress', 'arcane_boots', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 1, cd = 0 }, { name = 'lina_light_strike_array', level = 3, cd = 0 }, { name = 'lina_fiery_soul', level = 4, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 2, x = -1396.8, y = 314.3, hp = 1081, max_hp = 1110, mp = 622, max_mp = 708, level = 8, alive = true, tp_cd = 0, items = { 'null_talisman', 'tranquil_boots', 'headdress', 'magic_wand', 'observer_ward', 'belt_of_strength', '', 'blood_grenade', '' },
      abilities = { { name = 'lion_impale', level = 4, cd = 0 }, { name = 'lion_voodoo', level = 1, cd = 0 }, { name = 'lion_mana_drain', level = 2, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 1, cd = 31.8 } } },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 2, x = -912.9, y = -518.9, hp = 1149, max_hp = 1309, mp = 1103, max_mp = 1352, level = 10, alive = true, tp_cd = 9.5, items = { 'oblivion_staff', 'null_talisman', 'power_treads', 'chain_mail', 'null_talisman', 'magic_wand', '', '', '' },
      abilities = { { name = 'obsidian_destroyer_arcane_orb', level = 1, cd = 2.2 }, { name = 'obsidian_destroyer_astral_imprisonment', level = 4, cd = 0 }, { name = 'obsidian_destroyer_objurgation', level = 0, cd = 0 }, { name = 'obsidian_destroyer_sanity_eclipse', level = 1, cd = 62 } } },
    { name = 'npc_dota_hero_phantom_assassin', team = 2, x = 1658.4, y = -6375.8, hp = 201, max_hp = 1155, mp = 298, max_mp = 423, level = 8, alive = true, tp_cd = 20.2, items = { 'power_treads', 'ring_of_health', '', 'quelling_blade', 'orb_of_corrosion', 'magic_wand', '', '', '' },
      abilities = { { name = 'phantom_assassin_stifling_dagger', level = 3, cd = 0 }, { name = 'phantom_assassin_phantom_strike', level = 3, cd = 0 }, { name = 'phantom_assassin_blur', level = 1, cd = 32.5 }, { name = 'phantom_assassin_immaterial', level = 1, cd = 0 }, { name = 'phantom_assassin_coupde_grace', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 3, x = 2771.9, y = 5937.5, hp = 1688, max_hp = 1688, mp = 423, max_mp = 423, level = 7, alive = true, tp_cd = 10.3, items = { 'ogre_axe', 'power_treads', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'slardar_sprint', level = 1, cd = 0 }, { name = 'slardar_slithereen_crush', level = 1, cd = 0 }, { name = 'slardar_bash', level = 4, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_venomancer', team = 3, x = -2233.5, y = 2254.3, hp = 1077, max_hp = 1081, mp = 366, max_mp = 644, level = 8, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'ring_of_protection', 'fluffy_hat', 'tranquil_boots', 'magic_wand', 'wizard_hat', 'great_famango', 'dustof_appearance', 'blood_grenade' },
      abilities = { { name = 'venomancer_venomous_gale', level = 1, cd = 0 }, { name = 'venomancer_snakebite', level = 4, cd = 0 }, { name = 'venomancer_plague_ward', level = 2, cd = 0 }, { name = 'venomancer_noxious_plague', level = 1, cd = 60.5 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_obsidian_destroyer'] = 77,
    },
    died_after = 9.3,
  },
}
