-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_071859_slot1 @ t=192.4 (3:12), subject queen_of_pain.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_071859_slot1', time = 192.4, window = 5.0,
  self = 'npc_dota_hero_queen_of_pain',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = -2998.4, y = 4412.5, hp = 0, max_hp = 0, mp = 146, max_mp = 375, level = 3, alive = false, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_wand', 'bracer', 'clarity', '', '', '' } },
    { name = 'npc_dota_hero_lich', team = 2, x = 5977.0, y = -4089.0, hp = 335, max_hp = 736, mp = 99, max_mp = 555, level = 4, alive = true, tp_cd = 0, items = { 'ring_of_protection', 'faerie_fire', 'circlet', 'sobi_mask', 'observer_ward', 'boots_of_speed', '', 'blood_grenade', 'clarity' } },
    { name = 'npc_dota_hero_medusa', team = 2, x = 6481.4, y = -4144.9, hp = 230, max_hp = 230, mp = 404, max_mp = 609, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', '', 'null_talisman', 'magic_wand', '', '', '', '' } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = -6179.7, y = 3254.8, hp = 943, max_hp = 1072, mp = 261, max_mp = 491, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'blood_grenade', 'magic_wand', '', '', 'arcane_boots', '', '', '' } },
    { name = 'npc_dota_hero_oracle', team = 3, x = -4901.8, y = 5188.8, hp = 714, max_hp = 714, mp = 559, max_mp = 559, level = 3, alive = true, tp_cd = 17.1, items = { 'null_talisman', 'clarity', 'tango', 'magic_stick', 'boots_of_speed', 'ironwood_branch', '', 'blood_grenade', 'ironwood_branch' } },
    { name = 'npc_dota_hero_queen_of_pain', team = 2, x = -1477.2, y = -1158.1, hp = 299, max_hp = 869, mp = 67, max_mp = 646, level = 5, alive = true, tp_cd = 0, items = { 'flask', 'magic_wand', '', 'faerie_fire', 'null_talisman', 'empty_bottle', '', '', '' } },
    { name = 'npc_dota_hero_sven', team = 3, x = 6375.9, y = -2729.2, hp = 512, max_hp = 1000, mp = 339, max_mp = 339, level = 3, alive = true, tp_cd = 0, items = { 'clarity', 'boots_of_speed', 'belt_of_strength', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_tidehunter', team = 2, x = -6459.4, y = 3971.0, hp = 1053, max_hp = 1053, mp = 346, max_mp = 411, level = 4, alive = true, tp_cd = 0, items = { 'recipe_soul_ring', 'magic_wand', 'boots_of_speed', 'quelling_blade', 'gauntlets', 'ring_of_protection', 'tango', '', '' } },
    { name = 'npc_dota_hero_viper', team = 3, x = -42.9, y = -88.3, hp = 319, max_hp = 955, mp = 232, max_mp = 459, level = 6, alive = true, tp_cd = 37.8, items = { 'boots_of_speed', 'faerie_fire', 'magic_wand', '', 'wraith_band', '', '', '', '' } },
    { name = 'npc_dota_hero_warlock', team = 3, x = 6805.7, y = -2797.3, hp = 836, max_hp = 874, mp = 532, max_mp = 644, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'blood_grenade', '', 'arcane_boots', 'magic_wand', '', '', '', '' } },
  },
  observed = {
    burst = {
    },
    died_after = nil,
  },
}
