-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_072738_slot1 @ t=160.4 (2:40), subject zuus.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_072738_slot1', time = 160.4, window = 5.0,
  self = 'npc_dota_hero_zuus',
  units = {
    { name = 'npc_dota_hero_lich', team = 3, x = -6473.3, y = 4993.4, hp = 432, max_hp = 698, mp = 176, max_mp = 483, level = 3, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'tango', 'faerie_fire', 'observer_ward', 'blood_grenade', 'sobi_mask', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 2, cd = 0 }, { name = 'lich_frost_shield', level = 1, cd = 0 }, { name = 'lich_sinister_gaze', level = 0, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 3, x = -709.7, y = -565.1, hp = 512, max_hp = 868, mp = 646, max_mp = 745, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', '', 'faerie_fire', 'null_talisman', 'empty_bottle', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 3, cd = 6.2 }, { name = 'lina_light_strike_array', level = 1, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -5708.2, y = 5467.4, hp = 425, max_hp = 780, mp = 6, max_mp = 447, level = 3, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'magic_wand', '', 'wraith_band', '', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 2, cd = 6.7 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 1, cd = 0 }, { name = 'luna_eclipse', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_shadow_shaman', team = 2, x = -6553.9, y = -3640.8, hp = 764, max_hp = 764, mp = 459, max_mp = 459, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'boots_of_speed', 'sobi_mask', '', 'blood_grenade', 'magic_wand', '', '', '' },
      abilities = { { name = 'shadow_shaman_ether_shock', level = 2, cd = 0 }, { name = 'shadow_shaman_voodoo', level = 0, cd = 0 }, { name = 'shadow_shaman_shackles', level = 1, cd = 0 }, { name = 'shadow_shaman_fowl_play', level = 1, cd = 0 }, { name = 'shadow_shaman_mass_serpent_ward', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6970.1, y = 6417.7, hp = 207, max_hp = 802, mp = 170, max_mp = 303, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 5.7 }, { name = 'skeleton_king_bone_guard', level = 2, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 0, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skywrath_mage', team = 2, x = 6237.0, y = -4085.7, hp = 498, max_hp = 758, mp = 51, max_mp = 507, level = 3, alive = true, tp_cd = 0, items = { '', 'tango', 'tranquil_boots', '', 'faerie_fire', 'magic_wand', '', '', '' },
      abilities = { { name = 'skywrath_mage_arcane_bolt', level = 2, cd = 0 }, { name = 'skywrath_mage_concussive_shot', level = 1, cd = 0 }, { name = 'skywrath_mage_ancient_seal', level = 0, cd = 0 }, { name = 'skywrath_mage_mystic_flare', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -6692.4, y = -253.4, hp = 940, max_hp = 940, mp = 351, max_mp = 351, level = 3, alive = true, tp_cd = 0, items = { 'tango', '', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'slardar_sprint', level = 0, cd = 0 }, { name = 'slardar_slithereen_crush', level = 1, cd = 0 }, { name = 'slardar_bash', level = 2, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_spirit_breaker', team = 3, x = 3827.1, y = -4519.7, hp = 964, max_hp = 1050, mp = 238, max_mp = 315, level = 3, alive = true, tp_cd = 0, items = { 'quelling_blade', 'tango', 'wind_lace', 'ironwood_branch', 'bracer', 'clarity', 'ironwood_branch', '', '' },
      abilities = { { name = 'spirit_breaker_charge_of_darkness', level = 1, cd = 1 }, { name = 'spirit_breaker_bulldoze', level = 1, cd = 6.6 }, { name = 'spirit_breaker_greater_bash', level = 1, cd = 0 }, { name = 'spirit_breaker_nether_strike', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 2, x = 3525.6, y = -4586.5, hp = 317, max_hp = 868, mp = 133, max_mp = 339, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'boots_of_speed', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 19.6 }, { name = 'sven_great_cleave', level = 1, cd = 0 }, { name = 'sven_warcry', level = 1, cd = 13.3 }, { name = 'sven_gods_strength', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -1185.1, y = -964.9, hp = 507, max_hp = 780, mp = 148, max_mp = 495, level = 4, alive = true, tp_cd = 0, items = { 'tango', '', '', 'faerie_fire', 'empty_bottle', 'magic_wand', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 2, cd = 0 }, { name = 'zuus_lightning_bolt', level = 1, cd = 5.9 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_lina'] = 105,
    },
    died_after = 53.6,
  },
}
