-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_071859_slot1 @ t=255.0 (4:15), subject oracle.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_071859_slot1', time = 255.0, window = 5.0,
  self = 'npc_dota_hero_oracle',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = -5470.7, y = 5860.7, hp = 783, max_hp = 1073, mp = 232, max_mp = 387, level = 4, alive = true, tp_cd = 0, items = { 'boots_of_speed', '', 'quelling_blade', 'magic_wand', 'bracer', 'tango_single', '', '', '' } },
    { name = 'npc_dota_hero_lich', team = 2, x = 6011.4, y = -5422.9, hp = 658, max_hp = 780, mp = 194, max_mp = 591, level = 5, alive = true, tp_cd = 0, items = { 'ring_of_protection', 'tango', 'circlet', 'sobi_mask', 'observer_ward', 'boots_of_speed', 'clarity', 'blood_grenade', 'faerie_fire' } },
    { name = 'npc_dota_hero_medusa', team = 2, x = 5719.2, y = -5232.5, hp = 230, max_hp = 230, mp = 226, max_mp = 609, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'boots_of_speed', 'null_talisman', 'magic_wand', '', '', '', '' } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = -6072.9, y = 5237.3, hp = 886, max_hp = 1160, mp = 248, max_mp = 515, level = 5, alive = true, tp_cd = 39.8, items = { 'tango', 'blood_grenade', 'magic_wand', 'sobi_mask', '', 'arcane_boots', '', '', '' } },
    { name = 'npc_dota_hero_oracle', team = 3, x = -5471.9, y = 5364.1, hp = 624, max_hp = 736, mp = 438, max_mp = 584, level = 4, alive = true, tp_cd = 0, items = { 'null_talisman', 'clarity', 'tango', 'magic_stick', 'boots_of_speed', 'wind_lace', 'ironwood_branch', 'blood_grenade', 'ironwood_branch' } },
    { name = 'npc_dota_hero_queen_of_pain', team = 2, x = -1287.4, y = -1002.2, hp = 0, max_hp = 0, mp = 96, max_mp = 695, level = 6, alive = false, tp_cd = 0, items = { '', 'magic_wand', '', '', 'null_talisman', 'empty_bottle', '', '', '' } },
    { name = 'npc_dota_hero_sven', team = 3, x = 6574.8, y = -2883.4, hp = 500, max_hp = 1155, mp = 244, max_mp = 351, level = 4, alive = true, tp_cd = 0, items = { 'clarity', 'power_treads', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_tidehunter', team = 2, x = -5923.2, y = 4939.3, hp = 825, max_hp = 1119, mp = 311, max_mp = 423, level = 5, alive = true, tp_cd = 0, items = { 'recipe_soul_ring', 'magic_wand', 'boots_of_speed', 'quelling_blade', 'gauntlets', 'ring_of_protection', 'tango', '', '' } },
    { name = 'npc_dota_hero_viper', team = 3, x = -1475.0, y = 853.6, hp = 811, max_hp = 1000, mp = 326, max_mp = 483, level = 7, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'faerie_fire', 'magic_wand', '', 'wraith_band', '', '', '', '' } },
    { name = 'npc_dota_hero_warlock', team = 3, x = -5239.5, y = 5467.0, hp = 653, max_hp = 824, mp = 390, max_mp = 644, level = 4, alive = true, tp_cd = 35.8, items = { 'tango', '', '', 'arcane_boots', 'magic_wand', '', '', '', '' } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_ogre_magi'] = 116,
    },
    died_after = 224.7,
  },
}
