-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_073148_slot1 @ t=350.0 (5:50), subject zuus.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_073148_slot1', time = 350.0, window = 5.0,
  self = 'npc_dota_hero_zuus',
  units = {
    { name = 'npc_dota_hero_lich', team = 3, x = -5660.4, y = 3266.0, hp = 824, max_hp = 824, mp = 639, max_mp = 639, level = 6, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'tango', 'faerie_fire', 'observer_ward', 'clarity', 'boots_of_speed', '', 'famango', 'blood_grenade' } },
    { name = 'npc_dota_hero_lina', team = 3, x = -62.2, y = 19.8, hp = 1164, max_hp = 1242, mp = 696, max_mp = 1368, level = 12, alive = true, tp_cd = 0, items = { 'orchid_malevolence', 'magic_wand', 'arcane_boots', 'faerie_fire', 'null_talisman', 'empty_bottle', '', 'clarity', '' } },
    { name = 'npc_dota_hero_luna', team = 3, x = -6413.5, y = 2765.2, hp = 270, max_hp = 1200, mp = 225, max_mp = 543, level = 7, alive = true, tp_cd = 0, items = { '', 'magic_wand', 'power_treads', 'wraith_band', '', 'quelling_blade', '', '', '' } },
    { name = 'npc_dota_hero_shadow_shaman', team = 2, x = -6725.7, y = -2646.0, hp = 912, max_hp = 912, mp = 740, max_mp = 740, level = 7, alive = true, tp_cd = 13.6, items = { 'sentry_ward', '', 'arcane_boots', '', '', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 5850.4, y = -5457.7, hp = 785, max_hp = 1044, mp = 224, max_mp = 375, level = 7, alive = true, tp_cd = 25.4, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_skywrath_mage', team = 2, x = 866.1, y = -4634.2, hp = 762, max_hp = 846, mp = 425, max_mp = 603, level = 5, alive = true, tp_cd = 0, items = { 'observer_ward', 'tango', 'shadow_amulet', 'tranquil_boots', 'faerie_fire', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -6311.5, y = 1075.4, hp = 1402, max_hp = 1402, mp = 399, max_mp = 399, level = 6, alive = true, tp_cd = 20.4, items = { '', 'power_treads', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' } },
    { name = 'npc_dota_hero_spirit_breaker', team = 3, x = 5615.2, y = -5509.5, hp = 1046, max_hp = 1314, mp = 80, max_mp = 387, level = 7, alive = true, tp_cd = 24.9, items = { 'quelling_blade', 'tango', 'wind_lace', 'clarity', 'bracer', 'phase_boots', '', 'ironwood_branch', 'ironwood_branch' } },
    { name = 'npc_dota_hero_sven', team = 2, x = 5439.9, y = -5802.9, hp = 1164, max_hp = 1396, mp = 229, max_mp = 411, level = 7, alive = true, tp_cd = 0, items = { '', 'power_treads', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -860.9, y = -547.7, hp = 784, max_hp = 956, mp = 788, max_mp = 788, level = 8, alive = true, tp_cd = 0, items = { 'tango', 'arcane_boots', 'ring_of_health', '', 'empty_bottle', 'magic_wand', '', '', '' } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_lina'] = 613,
    },
    died_after = 5.9,
  },
}
