-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_071903_slot1 @ t=245.0 (4:05), subject sven.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_071903_slot1', time = 245.0, window = 5.0,
  self = 'npc_dota_hero_sven',
  units = {
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = 333.5, y = -743.1, hp = 1139, max_hp = 1160, mp = 447, max_mp = 447, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'empty_bottle', 'magic_wand', 'quelling_blade', 'bracer', 'boots_of_speed', '', '', '' } },
    { name = 'npc_dota_hero_jakiro', team = 2, x = -6393.8, y = 2429.6, hp = 0, max_hp = 0, mp = 291, max_mp = 387, level = 3, alive = false, tp_cd = 0, items = { 'boots_of_speed', 'tango', 'clarity', 'magic_stick', 'ironwood_branch', 'ring_of_basilius', 'blood_grenade', 'ironwood_branch', '' } },
    { name = 'npc_dota_hero_lich', team = 2, x = 6241.9, y = -4308.3, hp = 703, max_hp = 736, mp = 361, max_mp = 555, level = 4, alive = true, tp_cd = 0, items = { 'ring_of_protection', 'tango', 'faerie_fire', 'sobi_mask', 'circlet', 'boots_of_speed', 'clarity', '', 'blood_grenade' } },
    { name = 'npc_dota_hero_luna', team = 3, x = -6023.6, y = 3959.8, hp = 328, max_hp = 934, mp = 41, max_mp = 519, level = 6, alive = true, tp_cd = 0, items = { '', 'magic_wand', 'broadsword', 'wraith_band', 'power_treads', 'quelling_blade', '', '', '' } },
    { name = 'npc_dota_hero_medusa', team = 2, x = 1271.0, y = -4963.1, hp = 0, max_hp = 0, mp = 0, max_mp = 658, level = 5, alive = false, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'boots_of_speed', 'null_talisman', 'magic_wand', '', '', '', '' } },
    { name = 'npc_dota_hero_queen_of_pain', team = 2, x = -933.0, y = -895.5, hp = 808, max_hp = 978, mp = 202, max_mp = 732, level = 7, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'faerie_fire', 'null_talisman', 'empty_bottle', '', '', '' } },
    { name = 'npc_dota_hero_silencer', team = 3, x = -6470.1, y = 3877.8, hp = 430, max_hp = 758, mp = 27, max_mp = 651, level = 5, alive = true, tp_cd = 0, items = { 'tranquil_boots', 'tango', 'observer_ward', 'magic_wand', '', '', '', '', '' } },
    { name = 'npc_dota_hero_skywrath_mage', team = 3, x = 4128.6, y = -3145.4, hp = 648, max_hp = 846, mp = 56, max_mp = 728, level = 5, alive = true, tp_cd = 0, items = { '', 'boots_of_speed', 'ring_of_basilius', 'faerie_fire', 'wizard_hat', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -6289.2, y = 2610.9, hp = 0, max_hp = 0, mp = 218, max_mp = 291, level = 4, alive = false, tp_cd = 0, items = { 'tango', '', 'quelling_blade', 'magic_wand', 'bracer', 'boots_of_speed', '', '', '' } },
    { name = 'npc_dota_hero_sven', team = 3, x = 267.3, y = -3525.8, hp = 722, max_hp = 1066, mp = 172, max_mp = 351, level = 4, alive = true, tp_cd = 0, items = { 'belt_of_strength', 'boots_of_speed', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' } },
  },
  observed = {
    burst = {
    },
    died_after = 170.0,
  },
}
