-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_072738_slot1 @ t=160.4 (2:40), subject zuus.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_072738_slot1', time = 160.4, window = 5.0,
  self = 'npc_dota_hero_zuus',
  units = {
    { name = 'npc_dota_hero_lich', team = 3, x = -6473.3, y = 4993.4, hp = 432, max_hp = 698, mp = 176, max_mp = 483, level = 3, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'tango', 'faerie_fire', 'observer_ward', 'blood_grenade', 'sobi_mask', '', '', '' } },
    { name = 'npc_dota_hero_lina', team = 3, x = -709.7, y = -565.1, hp = 512, max_hp = 868, mp = 646, max_mp = 745, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', '', 'faerie_fire', 'null_talisman', 'empty_bottle', '', '', '' } },
    { name = 'npc_dota_hero_luna', team = 3, x = -5708.2, y = 5467.4, hp = 425, max_hp = 780, mp = 6, max_mp = 447, level = 3, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'magic_wand', '', 'wraith_band', '', 'quelling_blade', '', '', '' } },
    { name = 'npc_dota_hero_shadow_shaman', team = 2, x = -6553.9, y = -3640.8, hp = 764, max_hp = 764, mp = 459, max_mp = 459, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'boots_of_speed', 'sobi_mask', '', 'blood_grenade', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6970.1, y = 6417.7, hp = 207, max_hp = 802, mp = 170, max_mp = 303, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_skywrath_mage', team = 2, x = 6237.0, y = -4085.7, hp = 498, max_hp = 758, mp = 51, max_mp = 507, level = 3, alive = true, tp_cd = 0, items = { '', 'tango', 'tranquil_boots', '', 'faerie_fire', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -6692.4, y = -253.4, hp = 940, max_hp = 940, mp = 351, max_mp = 351, level = 3, alive = true, tp_cd = 0, items = { 'tango', '', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' } },
    { name = 'npc_dota_hero_spirit_breaker', team = 3, x = 3827.1, y = -4519.7, hp = 964, max_hp = 1050, mp = 238, max_mp = 315, level = 3, alive = true, tp_cd = 0, items = { 'quelling_blade', 'tango', 'wind_lace', 'ironwood_branch', 'bracer', 'clarity', 'ironwood_branch', '', '' } },
    { name = 'npc_dota_hero_sven', team = 2, x = 3525.6, y = -4586.5, hp = 317, max_hp = 868, mp = 133, max_mp = 339, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'boots_of_speed', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -1185.1, y = -964.9, hp = 507, max_hp = 780, mp = 148, max_mp = 495, level = 4, alive = true, tp_cd = 0, items = { 'tango', '', '', 'faerie_fire', 'empty_bottle', 'magic_wand', '', '', '' } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_lina'] = 105,
    },
    died_after = 53.6,
  },
}
