-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_071423_slot1 @ t=235.0 (3:55), subject skywrath_mage.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_071423_slot1', time = 235.0, window = 5.0,
  self = 'npc_dota_hero_skywrath_mage',
  units = {
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = 104.0, y = -69.2, hp = 705, max_hp = 1226, mp = 10, max_mp = 471, level = 7, alive = true, tp_cd = 0, items = { '', 'empty_bottle', 'magic_wand', 'quelling_blade', 'bracer', '', '', '', '' } },
    { name = 'npc_dota_hero_jakiro', team = 2, x = -4137.1, y = 5381.4, hp = 561, max_hp = 912, mp = 99, max_mp = 668, level = 5, alive = true, tp_cd = 0, items = { 'ring_of_basilius', 'tango', 'boots_of_speed', 'magic_stick', 'wizard_hat', 'ironwood_branch', 'ironwood_branch', '', '' } },
    { name = 'npc_dota_hero_lich', team = 2, x = -6947.7, y = -6580.1, hp = 543, max_hp = 786, mp = 555, max_mp = 555, level = 4, alive = true, tp_cd = 0, items = { 'observer_ward', 'tango', 'urn_of_shadows', 'boots_of_speed', 'blood_grenade', '', '', '', '' } },
    { name = 'npc_dota_hero_luna', team = 3, x = -3343.6, y = 5819.7, hp = 134, max_hp = 1000, mp = 83, max_mp = 495, level = 5, alive = true, tp_cd = 0, items = { 'flask', 'magic_wand', 'boots_of_speed', 'wraith_band', 'belt_of_strength', 'quelling_blade', 'tango_single', '', '' } },
    { name = 'npc_dota_hero_medusa', team = 2, x = 5469.8, y = -6069.8, hp = 230, max_hp = 230, mp = 423, max_mp = 609, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', '', 'null_talisman', 'magic_wand', '', '', '', '' } },
    { name = 'npc_dota_hero_queen_of_pain', team = 2, x = -501.7, y = -624.5, hp = 341, max_hp = 934, mp = 39, max_mp = 695, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', '', 'faerie_fire', 'null_talisman', 'empty_bottle', '', '', '' } },
    { name = 'npc_dota_hero_silencer', team = 3, x = -5927.5, y = 4404.4, hp = 0, max_hp = 0, mp = 45, max_mp = 459, level = 3, alive = false, tp_cd = 0, items = { 'tranquil_boots', '', 'ironwood_branch', 'ironwood_branch', 'blood_grenade', '', '', '', '' } },
    { name = 'npc_dota_hero_skywrath_mage', team = 3, x = 6726.6, y = 5871.3, hp = 577, max_hp = 896, mp = 529, max_mp = 728, level = 5, alive = true, tp_cd = 0, items = { 'flask', 'blood_grenade', '', 'faerie_fire', 'arcane_boots', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -3757.5, y = 5630.7, hp = 990, max_hp = 1028, mp = 180, max_mp = 363, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'boots_of_speed', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' } },
    { name = 'npc_dota_hero_sven', team = 3, x = 5628.6, y = -5751.5, hp = 702, max_hp = 1022, mp = 385, max_mp = 495, level = 5, alive = true, tp_cd = 0, items = { '', 'power_treads', '', '', 'quelling_blade', 'magic_wand', '', '', '' } },
  },
  observed = {
    burst = {
    },
    died_after = 151.3,
  },
}
