-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_071859_slot1 @ t=272.0 (4:32), subject oracle.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_071859_slot1', time = 272.0, window = 5.0,
  self = 'npc_dota_hero_oracle',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = -6328.8, y = 4459.6, hp = 1086, max_hp = 1138, mp = 143, max_mp = 399, level = 5, alive = true, tp_cd = 0, items = { 'boots_of_speed', '', 'quelling_blade', 'magic_wand', 'bracer', 'tango_single', '', '', '' } },
    { name = 'npc_dota_hero_lich', team = 2, x = 6030.9, y = -3374.3, hp = 719, max_hp = 780, mp = 248, max_mp = 591, level = 5, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'tango', 'clarity', 'faerie_fire', 'observer_ward', 'boots_of_speed', '', '', 'blood_grenade' } },
    { name = 'npc_dota_hero_medusa', team = 2, x = 6500.7, y = -3409.6, hp = 230, max_hp = 230, mp = 302, max_mp = 609, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'boots_of_speed', 'null_talisman', 'magic_wand', '', '', '', '' } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = -5745.3, y = 5065.8, hp = 0, max_hp = 0, mp = 284, max_mp = 515, level = 5, alive = false, tp_cd = 22.6, items = { 'tango', 'blood_grenade', 'magic_wand', 'sobi_mask', '', 'arcane_boots', '', '', '' } },
    { name = 'npc_dota_hero_oracle', team = 3, x = 6970.5, y = 6417.9, hp = 652, max_hp = 846, mp = 567, max_mp = 671, level = 5, alive = true, tp_cd = 0, items = { 'null_talisman', 'flask', 'tango', 'magic_wand', 'boots_of_speed', 'wind_lace', 'clarity', 'blood_grenade', '' } },
    { name = 'npc_dota_hero_queen_of_pain', team = 2, x = -1359.9, y = -1128.8, hp = 832, max_hp = 934, mp = 656, max_mp = 695, level = 6, alive = true, tp_cd = 33.1, items = { 'boots_of_speed', 'magic_wand', '', '', 'null_talisman', 'empty_bottle', '', '', '' } },
    { name = 'npc_dota_hero_sven', team = 3, x = 6464.7, y = -2574.5, hp = 594, max_hp = 1243, mp = 258, max_mp = 375, level = 5, alive = true, tp_cd = 0, items = { 'clarity', 'power_treads', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_tidehunter', team = 2, x = -7210.9, y = -6688.0, hp = 1030, max_hp = 1120, mp = 423, max_mp = 423, level = 5, alive = true, tp_cd = 27.8, items = { 'recipe_soul_ring', 'magic_wand', 'boots_of_speed', 'quelling_blade', 'gauntlets', 'ring_of_protection', 'tango', '', '' } },
    { name = 'npc_dota_hero_viper', team = 3, x = -506.7, y = -254.5, hp = 872, max_hp = 1044, mp = 283, max_mp = 507, level = 8, alive = true, tp_cd = 0, items = { 'power_treads', 'faerie_fire', 'magic_wand', '', 'wraith_band', '', '', '', '' } },
    { name = 'npc_dota_hero_warlock', team = 3, x = -4347.3, y = 4482.7, hp = 558, max_hp = 868, mp = 512, max_mp = 680, level = 5, alive = true, tp_cd = 18.7, items = { '', '', '', 'arcane_boots', 'magic_wand', '', '', '', '' } },
  },
  observed = {
    burst = {
    },
    died_after = 207.7,
  },
}
