-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_071423_slot1 @ t=309.5 (5:09), subject luna.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_071423_slot1', time = 309.5, window = 5.0,
  self = 'npc_dota_hero_luna',
  units = {
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = 836.3, y = 644.4, hp = 1092, max_hp = 1424, mp = 289, max_mp = 483, level = 8, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'empty_bottle', 'magic_wand', 'quelling_blade', 'bracer', 'belt_of_strength', '', '', '' } },
    { name = 'npc_dota_hero_jakiro', team = 2, x = -6026.3, y = 2248.2, hp = 274, max_hp = 1066, mp = 575, max_mp = 704, level = 6, alive = true, tp_cd = 25.5, items = { 'flask', 'ring_of_protection', 'arcane_boots', 'magic_wand', 'circlet', 'sobi_mask', 'tango', '', '' } },
    { name = 'npc_dota_hero_lich', team = 2, x = 6435.5, y = -3280.0, hp = 744, max_hp = 780, mp = 524, max_mp = 591, level = 5, alive = true, tp_cd = 0, items = { 'observer_ward', 'tango', 'urn_of_shadows', 'tranquil_boots', '', '', '', '', '' } },
    { name = 'npc_dota_hero_luna', team = 3, x = -5815.9, y = 2890.5, hp = 354, max_hp = 934, mp = 334, max_mp = 639, level = 6, alive = true, tp_cd = 0, items = { 'flask', 'magic_wand', 'power_treads', 'wraith_band', '', 'quelling_blade', '', '', '' } },
    { name = 'npc_dota_hero_medusa', team = 2, x = 5349.8, y = -3643.9, hp = 362, max_hp = 362, mp = 113, max_mp = 708, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'boots_of_speed', 'null_talisman', 'magic_wand', 'belt_of_strength', '', '', '' } },
    { name = 'npc_dota_hero_queen_of_pain', team = 2, x = -201.9, y = -16.9, hp = 540, max_hp = 1023, mp = 139, max_mp = 769, level = 8, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'magic_wand', '', '', 'null_talisman', 'empty_bottle', '', '', '' } },
    { name = 'npc_dota_hero_silencer', team = 3, x = -5908.0, y = 3028.3, hp = 692, max_hp = 692, mp = 222, max_mp = 543, level = 4, alive = true, tp_cd = 0, items = { 'tranquil_boots', 'flask', 'ironwood_branch', 'ironwood_branch', 'magic_stick', 'observer_ward', '', 'blood_grenade', '' } },
    { name = 'npc_dota_hero_skywrath_mage', team = 3, x = 3321.6, y = 82.0, hp = 890, max_hp = 890, mp = 430, max_mp = 776, level = 6, alive = true, tp_cd = 0, items = { 'flask', 'sentry_ward', '', 'faerie_fire', 'arcane_boots', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -5804.3, y = 2782.4, hp = 1314, max_hp = 1314, mp = 300, max_mp = 387, level = 5, alive = true, tp_cd = 3.1, items = { '', 'power_treads', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' } },
    { name = 'npc_dota_hero_sven', team = 3, x = 7180.9, y = 6296.4, hp = 1308, max_hp = 1308, mp = 331, max_mp = 387, level = 6, alive = true, tp_cd = 39.3, items = { 'broadsword', 'power_treads', '', '', 'quelling_blade', 'magic_wand', '', '', '' } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_slardar'] = 286,
      ['npc_dota_hero_jakiro'] = 58,
    },
    died_after = 4.0,
  },
}
