-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_080225_slot1 @ t=403.0 (6:43), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_080225_slot1', time = 403.0, window = 5.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 2, x = -5305.1, y = -5713.9, hp = 1380, max_hp = 1380, mp = 728, max_mp = 728, level = 10, alive = true, tp_cd = 16.6, items = { 'blade_mail', 'bracer', 'arcane_boots', 'quelling_blade', 'magic_wand', '', '', '', '' } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = -4846.4, y = 1758.1, hp = 1214, max_hp = 1556, mp = 108, max_mp = 531, level = 10, alive = true, tp_cd = 13.4, items = { 'belt_of_strength', 'empty_bottle', 'magic_wand', 'quelling_blade', 'bracer', 'boots_of_speed', 'tango', '', '' } },
    { name = 'npc_dota_hero_earthshaker', team = 3, x = 6930.8, y = 6393.7, hp = 522, max_hp = 1315, mp = 644, max_mp = 644, level = 8, alive = true, tp_cd = 29.4, items = { 'urn_of_shadows', 'blood_grenade', 'magic_wand', 'clarity', 'sentry_ward', 'arcane_boots', '', '', '' } },
    { name = 'npc_dota_hero_juggernaut', team = 2, x = 6428.2, y = -5285.9, hp = 775, max_hp = 890, mp = 223, max_mp = 387, level = 6, alive = true, tp_cd = 0, items = { 'flask', 'magic_wand', 'power_treads', 'wraith_band', '', 'quelling_blade', '', '', '' } },
    { name = 'npc_dota_hero_pudge', team = 3, x = -3025.6, y = 4061.7, hp = 1198, max_hp = 1198, mp = 536, max_mp = 536, level = 6, alive = true, tp_cd = 0, items = { 'observer_ward', '', '', 'arcane_boots', 'wind_lace', 'magic_wand', 'famango', '', '' } },
    { name = 'npc_dota_hero_shadow_shaman', team = 2, x = 6353.3, y = -5386.3, hp = 886, max_hp = 918, mp = 202, max_mp = 579, level = 6, alive = true, tp_cd = 0, items = { 'tranquil_boots', 'blood_grenade', 'observer_ward', '', 'faerie_fire', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6709.9, y = -4994.2, hp = 825, max_hp = 1044, mp = 375, max_mp = 375, level = 7, alive = true, tp_cd = 0, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_storm_spirit', team = 2, x = -931.3, y = -953.8, hp = 746, max_hp = 1288, mp = 472, max_mp = 997, level = 10, alive = true, tp_cd = 0, items = { 'falcon_blade', 'tango', 'clarity', 'null_talisman', 'arcane_boots', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = -5808.3, y = 5466.8, hp = 631, max_hp = 912, mp = 359, max_mp = 423, level = 6, alive = true, tp_cd = 4.7, items = { 'flask', 'power_treads', 'blitz_knuckles', '', 'enchanted_mango', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -6053.6, y = 1338.7, hp = 0, max_hp = 0, mp = 223, max_mp = 812, level = 8, alive = false, tp_cd = 0, items = { 'chain_mail', 'headdress', 'magic_wand', 'urn_of_shadows', 'sentry_ward', 'arcane_boots', '', 'tango', '' } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_juggernaut'] = 232,
      ['npc_dota_hero_shadow_shaman'] = 117,
    },
    died_after = 7.8,
  },
}
