-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260720_080225_slot1 @ t=47.0 (0:47), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260720_080225_slot1', time = 47.0, window = 5.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 2, x = -4923.3, y = 4494.2, hp = 677, max_hp = 714, mp = 147, max_mp = 303, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'circlet', '', 'quelling_blade', 'magic_wand', '', '', '', '' } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = -204.8, y = -102.8, hp = 728, max_hp = 736, mp = 339, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'quelling_blade', 'circlet', 'gauntlets', '', '', '' } },
    { name = 'npc_dota_hero_earthshaker', team = 3, x = 6626.8, y = -3971.9, hp = 612, max_hp = 648, mp = 212, max_mp = 315, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'magic_stick', 'ironwood_branch', 'clarity', '', '', '', '' } },
    { name = 'npc_dota_hero_juggernaut', team = 2, x = 6816.0, y = -3918.0, hp = 641, max_hp = 648, mp = 191, max_mp = 291, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'wraith_band', '', 'quelling_blade', '', '', '' } },
    { name = 'npc_dota_hero_pudge', team = 3, x = -5839.0, y = 3378.8, hp = 404, max_hp = 670, mp = 251, max_mp = 267, level = 1, alive = true, tp_cd = 0, items = { '', 'tango', 'flask', '', 'wind_lace', '', '', '', '' } },
    { name = 'npc_dota_hero_shadow_shaman', team = 2, x = 6738.7, y = -4193.1, hp = 495, max_hp = 626, mp = 311, max_mp = 387, level = 1, alive = true, tp_cd = 0, items = { '', 'tango', 'clarity', '', 'faerie_fire', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6688.6, y = -3655.9, hp = 88, max_hp = 693, mp = 279, max_mp = 279, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_storm_spirit', team = 2, x = -603.8, y = -510.0, hp = 714, max_hp = 714, mp = 415, max_mp = 485, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'null_talisman', '', 'magic_stick', '', '', '' } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = -4629.9, y = 4782.6, hp = 28, max_hp = 622, mp = 339, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', '', '', '', 'enchanted_mango', 'magic_wand', '', '', '' } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -5814.8, y = 3303.4, hp = 33, max_hp = 623, mp = 65, max_mp = 375, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'magic_stick', 'ironwood_branch', 'clarity', '', '', '', '' } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_shadow_shaman'] = 89,
      ['npc_dota_hero_juggernaut'] = 44,
    },
    died_after = 6.1,
  },
}
