-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260723_113203_slot1 @ t=525.0 (8:45), subject pudge.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260723_113203_slot1', time = 525.0, window = 5.0,
  self = 'npc_dota_hero_pudge',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = 6054.4, y = -5221.5, hp = 1622, max_hp = 1622, mp = 359, max_mp = 459, level = 9, alive = true, tp_cd = 0, items = { 'power_treads', 'helm_of_iron_will', 'gloves_of_haste', 'magic_wand', 'bracer', 'blades_of_attack', 'quelling_blade', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 3, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 4, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 3, x = -1640.1, y = -1201.9, hp = 0, max_hp = 0, mp = 59, max_mp = 867, level = 10, alive = false, tp_cd = 0, items = { 'power_treads', 'flask', 'quelling_blade', 'magic_wand', 'bracer', 'ring_of_health', '', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 3, cd = 0 }, { name = 'death_prophet_silence', level = 1, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 4, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 120.3 }, { name = 'special_bonus_h_p200', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 2, x = -6354.9, y = -2819.0, hp = 1578, max_hp = 1578, mp = 627, max_mp = 627, level = 9, alive = true, tp_cd = 14.4, items = { 'oblivion_staff', 'magic_wand', 'power_treads', 'quelling_blade', 'bracer', 'clarity', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 3, cd = 0 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 1, cd = 62.7 } } },
    { name = 'npc_dota_hero_juggernaut', team = 3, x = -3649.8, y = 5617.2, hp = 529, max_hp = 935, mp = 212, max_mp = 399, level = 7, alive = true, tp_cd = 0, items = { '', 'clarity', 'power_treads', 'wraith_band', 'magic_wand', 'quelling_blade', '', '', '' },
      abilities = { { name = 'juggernaut_blade_fury', level = 4, cd = 0 }, { name = 'juggernaut_healing_ward', level = 1, cd = 5.1 }, { name = 'juggernaut_blade_dance', level = 1, cd = 0 }, { name = 'juggernaut_bladeform', level = 1, cd = 0 }, { name = 'juggernaut_omnislash', level = 1, cd = 45.3 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = -764.3, y = -463.3, hp = 1248, max_hp = 1287, mp = 1165, max_mp = 1393, level = 13, alive = true, tp_cd = 0, items = { '', 'magic_wand', 'arcane_boots', 'oblivion_staff', 'null_talisman', 'empty_bottle', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 4, cd = 0.4 }, { name = 'lina_light_strike_array', level = 4, cd = 0 }, { name = 'lina_fiery_soul', level = 2, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 2, cd = 57.4 } } },
    { name = 'npc_dota_hero_oracle', team = 2, x = 261.4, y = -984.7, hp = 639, max_hp = 1380, mp = 942, max_mp = 942, level = 11, alive = true, tp_cd = 15.1, items = { 'null_talisman', 'observer_ward', 'ancient_janggo', 'magic_wand', 'tranquil_boots', 'blood_grenade', '', '', '' },
      abilities = { { name = 'oracle_fortunes_end', level = 1, cd = 2.2 }, { name = 'oracle_fates_edict', level = 4, cd = 0 }, { name = 'oracle_purifying_flames', level = 4, cd = 0 }, { name = 'oracle_false_promise', level = 1, cd = 30.6 }, { name = 'oracle_prognosticate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_pudge', team = 3, x = -4297.3, y = 5945.4, hp = 390, max_hp = 1226, mp = 438, max_mp = 548, level = 7, alive = true, tp_cd = 0, items = { 'observer_ward', '', 'blood_grenade', 'arcane_boots', 'wind_lace', 'magic_wand', '', '', '' },
      abilities = { { name = 'pudge_meat_hook', level = 3, cd = 0 }, { name = 'pudge_rot', level = 2, cd = 0 }, { name = 'pudge_flesh_heap', level = 1, cd = 0 }, { name = 'pudge_dismember', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -219.1, y = 222.1, hp = 0, max_hp = 0, mp = 523, max_mp = 651, level = 12, alive = false, tp_cd = 0, items = { 'dragon_lance', 'broadsword', 'magic_wand', 'power_treads', 'wraith_band', '', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 4, cd = 0 }, { name = 'sniper_headshot', level = 4, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_venomancer', team = 3, x = 5872.7, y = -5455.1, hp = 0, max_hp = 0, mp = 417, max_mp = 620, level = 7, alive = false, tp_cd = 0, items = { 'blood_grenade', 'urn_of_shadows', 'sentry_ward', 'magic_wand', 'arcane_boots', '', '', '', '' },
      abilities = { { name = 'venomancer_venomous_gale', level = 1, cd = 1.5 }, { name = 'venomancer_snakebite', level = 4, cd = 0 }, { name = 'venomancer_plague_ward', level = 1, cd = 0 }, { name = 'venomancer_noxious_plague', level = 1, cd = 21.7 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 2, x = -2404.8, y = -1957.8, hp = 0, max_hp = 0, mp = 902, max_mp = 974, level = 9, alive = false, tp_cd = 31.7, items = { 'essence_distiller', 'sentry_ward', 'shawl', 'arcane_boots', 'enchanted_mango', 'magic_wand', '', '', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 4, cd = 0 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 4, cd = 1.8 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
    },
    died_after = nil,
  },
}
