-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260723_113638_slot1 @ t=256.0 (4:16), subject crystal_maiden.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260723_113638_slot1', time = 256.0, window = 5.0,
  self = 'npc_dota_hero_crystal_maiden',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 2, x = 4107.7, y = -6295.5, hp = 1169, max_hp = 1225, mp = 1, max_mp = 399, level = 4, alive = true, tp_cd = 0, items = { 'power_treads', 'bracer', '', 'quelling_blade', 'magic_wand', '', '', '', '' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 2, cd = 2.2 }, { name = 'bristleback_bristleback', level = 1, cd = 0 }, { name = 'bristleback_warpath', level = 0, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = -6071.0, y = 4742.0, hp = 991, max_hp = 1271, mp = 246, max_mp = 399, level = 5, alive = true, tp_cd = 0, items = { 'belt_of_strength', 'flask', 'quelling_blade', 'magic_wand', 'bracer', 'boots_of_speed', 'tango', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 3.8 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 5.2 }, { name = 'chaos_knight_chaos_strike', level = 3, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 3, x = 6685.5, y = -2840.9, hp = 428, max_hp = 648, mp = 230, max_mp = 560, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'wizard_hat', 'magic_stick', 'ironwood_branch', 'ring_of_basilius', 'boots_of_speed', 'ironwood_branch', '', '' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 0 }, { name = 'crystal_maiden_frostbite', level = 2, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = -5964.0, y = 4639.8, hp = 594, max_hp = 868, mp = 716, max_mp = 812, level = 5, alive = true, tp_cd = 0, items = { 'circlet', 'ring_of_protection', 'magic_wand', 'sobi_mask', 'flask', 'arcane_boots', 'clarity', 'blood_grenade', 'tango' },
      abilities = { { name = 'lina_dragon_slave', level = 1, cd = 1.8 }, { name = 'lina_light_strike_array', level = 1, cd = 0 }, { name = 'lina_fiery_soul', level = 3, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_necrolyte', team = 3, x = -5724.2, y = 5223.4, hp = 1094, max_hp = 1094, mp = 585, max_mp = 627, level = 8, alive = true, tp_cd = 35.3, items = { 'tango', 'bracer', 'boots_of_speed', 'faerie_fire', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'necrolyte_death_pulse', level = 4, cd = 0 }, { name = 'necrolyte_ghost_shroud', level = 1, cd = 0 }, { name = 'necrolyte_heartstopper_aura', level = 2, cd = 0 }, { name = 'necrolyte_reapers_scythe', level = 1, cd = 88.5 } } },
    { name = 'npc_dota_hero_oracle', team = 3, x = 5863.3, y = -5879.8, hp = 0, max_hp = 0, mp = 596, max_mp = 596, level = 4, alive = false, tp_cd = 0, items = { 'null_talisman', 'boots_of_speed', 'tango', 'magic_stick', 'observer_ward', 'ironwood_branch', '', 'blood_grenade', 'ironwood_branch' },
      abilities = { { name = 'oracle_fortunes_end', level = 1, cd = 0 }, { name = 'oracle_fates_edict', level = 1, cd = 0 }, { name = 'oracle_purifying_flames', level = 2, cd = 0 }, { name = 'oracle_false_promise', level = 0, cd = 0 }, { name = 'oracle_prognosticate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skywrath_mage', team = 2, x = 4386.3, y = -6508.8, hp = 568, max_hp = 852, mp = 47, max_mp = 555, level = 4, alive = true, tp_cd = 0, items = { 'blood_grenade', 'observer_ward', 'tranquil_boots', 'tango', 'faerie_fire', 'magic_wand', '', '', '' },
      abilities = { { name = 'skywrath_mage_arcane_bolt', level = 2, cd = 0 }, { name = 'skywrath_mage_concussive_shot', level = 1, cd = 0 }, { name = 'skywrath_mage_ancient_seal', level = 1, cd = 0 }, { name = 'skywrath_mage_mystic_flare', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -4578.6, y = 5762.0, hp = 276, max_hp = 758, mp = 317, max_mp = 387, level = 4, alive = true, tp_cd = 37.1, items = { 'tango', 'boots_of_speed', 'magic_stick', 'ironwood_branch', 'wraith_band', 'ironwood_branch', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 0, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 6.4 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_storm_spirit', team = 2, x = -1171.7, y = -1163.0, hp = 0, max_hp = 0, mp = 85, max_mp = 824, level = 7, alive = false, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'wizard_hat', 'null_talisman', 'boots_of_speed', 'magic_stick', 'ironwood_branch', 'ironwood_branch', '' },
      abilities = { { name = 'storm_spirit_static_remnant', level = 4, cd = 0 }, { name = 'storm_spirit_electric_vortex', level = 1, cd = 0 }, { name = 'storm_spirit_overload', level = 1, cd = 0 }, { name = 'storm_spirit_ball_lightning', level = 1, cd = 0 }, { name = 'storm_spirit_galvanized', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 3, x = 6442.4, y = -2804.2, hp = 513, max_hp = 1153, mp = 249, max_mp = 351, level = 4, alive = true, tp_cd = 0, items = { '', 'power_treads', '', '', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 18.6 }, { name = 'sven_great_cleave', level = 2, cd = 0 }, { name = 'sven_warcry', level = 1, cd = 26.4 }, { name = 'sven_gods_strength', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
    },
    died_after = 11.6,
  },
}
