-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260723_114311_slot1 @ t=411.0 (6:51), subject drow_ranger.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260723_114311_slot1', time = 411.0, window = 5.0,
  self = 'npc_dota_hero_drow_ranger',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = 6593.2, y = -932.8, hp = 1138, max_hp = 1138, mp = 399, max_mp = 399, level = 5, alive = true, tp_cd = 0, items = { 'flask', 'boots_of_speed', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 3, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_drow_ranger', team = 2, x = 5959.6, y = -2754.9, hp = 903, max_hp = 1176, mp = 174, max_mp = 411, level = 7, alive = true, tp_cd = 0, items = { 'blade_of_alacrity', 'power_treads', 'tango_single', 'wraith_band', 'belt_of_strength', 'magic_wand', '', '', '' },
      abilities = { { name = 'drow_ranger_frost_arrows', level = 2, cd = 0 }, { name = 'drow_ranger_wave_of_silence', level = 1, cd = 0 }, { name = 'drow_ranger_multishot', level = 3, cd = 0 }, { name = 'drow_ranger_marksmanship', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_earthshaker', team = 2, x = -6021.3, y = 4790.1, hp = 1131, max_hp = 1154, mp = 596, max_mp = 596, level = 7, alive = true, tp_cd = 13.7, items = { 'ring_of_protection', 'sentry_ward', 'magic_wand', 'sobi_mask', 'arcane_boots', 'flask', 'clarity', 'blood_grenade', 'tango' },
      abilities = { { name = 'earthshaker_fissure', level = 1, cd = 0 }, { name = 'earthshaker_enchant_totem', level = 1, cd = 0 }, { name = 'earthshaker_aftershock', level = 4, cd = 0 }, { name = 'earthshaker_echo_slam', level = 1, cd = 27.6 }, { name = 'earthshaker_slugger', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = -1298.9, y = -732.3, hp = 657, max_hp = 962, mp = 79, max_mp = 711, level = 8, alive = true, tp_cd = 33.8, items = { 'observer_ward', 'tango', 'urn_of_shadows', 'tranquil_boots', 'dustof_appearance', 'blood_grenade', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 4, cd = 0 }, { name = 'lich_frost_shield', level = 2, cd = 0 }, { name = 'lich_sinister_gaze', level = 1, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 1, cd = 23 } } },
    { name = 'npc_dota_hero_phantom_assassin', team = 3, x = -2983.1, y = 5659.0, hp = 780, max_hp = 780, mp = 363, max_mp = 363, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'quelling_blade', 'orb_of_corrosion', '', '', '', '' },
      abilities = { { name = 'phantom_assassin_stifling_dagger', level = 3, cd = 0 }, { name = 'phantom_assassin_phantom_strike', level = 1, cd = 0 }, { name = 'phantom_assassin_blur', level = 1, cd = 0 }, { name = 'phantom_assassin_immaterial', level = 1, cd = 0 }, { name = 'phantom_assassin_coupde_grace', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 2, x = -5594.1, y = 5496.4, hp = 1044, max_hp = 1044, mp = 271, max_mp = 375, level = 7, alive = true, tp_cd = 0, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 4, cd = 32.5 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -246.7, y = -161.7, hp = 488, max_hp = 1087, mp = 229, max_mp = 531, level = 8, alive = true, tp_cd = 0, items = { 'blade_of_alacrity', 'faerie_fire', 'magic_wand', 'power_treads', 'wraith_band', 'belt_of_strength', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 3, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 5.8 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = 6538.2, y = -1611.6, hp = 1011, max_hp = 1081, mp = 322, max_mp = 567, level = 7, alive = true, tp_cd = 21.9, items = { 'fluffy_hat', 'staff_of_wizardry', 'tranquil_boots', '', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 4, cd = 0 }, { name = 'vengeful_spirit_wave_of_terror', level = 2, cd = 0 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_viper', team = 2, x = -2157.2, y = -1694.0, hp = 242, max_hp = 1267, mp = 271, max_mp = 507, level = 8, alive = true, tp_cd = 23.4, items = { '', 'faerie_fire', 'power_treads', 'blade_of_alacrity', 'wraith_band', 'magic_wand', '', '', '' },
      abilities = { { name = 'viper_poison_attack', level = 4, cd = 0 }, { name = 'viper_nethertoxin', level = 2, cd = 0 }, { name = 'viper_corrosive_skin', level = 1, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 3, x = 6656.6, y = -2420.9, hp = 934, max_hp = 934, mp = 740, max_mp = 740, level = 7, alive = true, tp_cd = 34.9, items = { 'enchanted_mango', 'urn_of_shadows', 'sentry_ward', 'clarity', 'arcane_boots', 'magic_wand', '', 'blood_grenade', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 2, cd = 0 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 4, cd = 0 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_vengefulspirit'] = 410,
      ['npc_dota_hero_witch_doctor'] = 381,
      ['npc_dota_hero_chaos_knight'] = 145,
    },
    died_after = 4.3,
  },
}
