-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- B_20260723_163714_slot1 @ t=35.0 (0:35), subject zuus.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = 'B_20260723_163714_slot1', time = 35.0, window = 5.0,
  self = 'npc_dota_hero_zuus',
  units = {
    { name = 'npc_dota_hero_crystal_maiden', team = 2, x = -6340.6, y = 4767.1, hp = 484, max_hp = 538, mp = 228, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'magic_stick', 'ironwood_branch', '', '', '', '', '' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 7.8 }, { name = 'crystal_maiden_frostbite', level = 0, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 0, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = -5989.9, y = 5307.1, hp = 559, max_hp = 714, mp = 240, max_mp = 327, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'magic_stick', 'ironwood_branch', 'quelling_blade', 'circlet', 'gauntlets', 'ironwood_branch', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 1, cd = 11.4 }, { name = 'dragon_knight_dragon_tail', level = 0, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 0, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_necrolyte', team = 2, x = -6044.5, y = 4803.2, hp = 604, max_hp = 604, mp = 321, max_mp = 435, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'circlet', 'mantle', 'magic_stick', '', '', '' },
      abilities = { { name = 'necrolyte_death_pulse', level = 1, cd = 8 }, { name = 'necrolyte_ghost_shroud', level = 0, cd = 0 }, { name = 'necrolyte_heartstopper_aura', level = 0, cd = 0 }, { name = 'necrolyte_reapers_scythe', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = -355.3, y = -285.7, hp = 546, max_hp = 582, mp = 255, max_mp = 315, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'enchanted_mango', '', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 1, cd = 0 }, { name = 'nevermore_shadowraze2', level = 1, cd = 0 }, { name = 'nevermore_shadowraze3', level = 1, cd = 0 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 0, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_oracle', team = 3, x = -5633.2, y = 5339.0, hp = 588, max_hp = 698, mp = 391, max_mp = 471, level = 1, alive = true, tp_cd = 0, items = { 'mantle', 'blood_grenade', 'tango', 'ironwood_branch', 'ironwood_branch', 'circlet', '', '', '' },
      abilities = { { name = 'oracle_fortunes_end', level = 1, cd = 17.8 }, { name = 'oracle_fates_edict', level = 0, cd = 0 }, { name = 'oracle_purifying_flames', level = 0, cd = 0 }, { name = 'oracle_false_promise', level = 0, cd = 0 }, { name = 'oracle_prognosticate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_shadow_shaman', team = 2, x = 5713.6, y = -5400.1, hp = 568, max_hp = 676, mp = 299, max_mp = 387, level = 1, alive = true, tp_cd = 0, items = { 'blood_grenade', 'tango', '', '', 'faerie_fire', 'magic_wand', '', '', '' },
      abilities = { { name = 'shadow_shaman_ether_shock', level = 1, cd = 12.5 }, { name = 'shadow_shaman_voodoo', level = 0, cd = 0 }, { name = 'shadow_shaman_shackles', level = 0, cd = 0 }, { name = 'shadow_shaman_fowl_play', level = 1, cd = 0 }, { name = 'shadow_shaman_mass_serpent_ward', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_storm_spirit', team = 2, x = -929.7, y = -805.3, hp = 515, max_hp = 670, mp = 438, max_mp = 448, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'null_talisman', '', 'magic_stick', '', '', '' },
      abilities = { { name = 'storm_spirit_static_remnant', level = 1, cd = 0 }, { name = 'storm_spirit_electric_vortex', level = 0, cd = 0 }, { name = 'storm_spirit_overload', level = 0, cd = 0 }, { name = 'storm_spirit_ball_lightning', level = 0, cd = 0 }, { name = 'storm_spirit_galvanized', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 2, x = 6072.9, y = -5259.5, hp = 572, max_hp = 714, mp = 195, max_mp = 303, level = 1, alive = true, tp_cd = 0, items = { 'tango', '', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 18.7 }, { name = 'sven_great_cleave', level = 0, cd = 0 }, { name = 'sven_warcry', level = 0, cd = 0 }, { name = 'sven_gods_strength', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_tidehunter', team = 3, x = 6019.4, y = -5269.4, hp = 658, max_hp = 802, mp = 351, max_mp = 351, level = 1, alive = true, tp_cd = 0, items = { 'tango', '', '', 'quelling_blade', 'gauntlets', 'magic_wand', '', '', '' },
      abilities = { { name = 'tidehunter_gush', level = 0, cd = 0 }, { name = 'tidehunter_kraken_shell', level = 0, cd = 0 }, { name = 'tidehunter_anchor_smash', level = 1, cd = 0 }, { name = 'tidehunter_ravage', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 3, x = 6016.4, y = -5080.1, hp = 361, max_hp = 626, mp = 259, max_mp = 375, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'magic_stick', 'ironwood_branch', '', '', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 0, cd = 0 }, { name = 'zuus_lightning_bolt', level = 1, cd = 2.5 }, { name = 'zuus_heavenly_jump', level = 0, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_shadow_shaman'] = 219,
      ['npc_dota_hero_sven'] = 120,
    },
    died_after = 5.7,
  },
}
