-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- A_20260723_163732_slot1 @ t=305.0 (5:05), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = 'A_20260723_163732_slot1', time = 305.0, window = 5.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 3, x = -4220.7, y = 4119.4, hp = 383, max_hp = 1403, mp = 29, max_mp = 495, level = 7, alive = true, tp_cd = 0, items = { 'power_treads', 'bracer', '', 'quelling_blade', 'magic_wand', '', '', '', '' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 4, cd = 0 }, { name = 'bristleback_bristleback', level = 1, cd = 0 }, { name = 'bristleback_warpath', level = 1, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_centaur', team = 2, x = -3041.8, y = 4523.9, hp = 0, max_hp = 0, mp = 189, max_mp = 363, level = 5, alive = false, tp_cd = 25.5, items = { 'blades_of_attack', 'magic_wand', 'helm_of_iron_will', 'quelling_blade', 'ring_of_protection', 'boots_of_speed', 'tango_single', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 2, cd = 0 }, { name = 'centaur_double_edge', level = 3, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 0, cd = 0 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 2, x = -1720.0, y = -175.8, hp = 1132, max_hp = 1132, mp = 546, max_mp = 800, level = 8, alive = true, tp_cd = 20.7, items = { 'tango', 'magic_wand', 'arcane_boots', 'faerie_fire', 'circlet', 'empty_bottle', '', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 4, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 3, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 44.7 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = 1386.9, y = 1286.5, hp = 1160, max_hp = 1160, mp = 447, max_mp = 447, level = 6, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'empty_bottle', 'magic_wand', 'quelling_blade', 'bracer', '', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 2, cd = 0 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 2, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 1, cd = 15.2 } } },
    { name = 'npc_dota_hero_lion', team = 2, x = -3990.0, y = 3323.0, hp = 409, max_hp = 830, mp = 500, max_mp = 632, level = 5, alive = true, tp_cd = 0, items = { 'arcane_boots', 'tango', 'blood_grenade', 'magic_wand', 'sobi_mask', 'clarity', '', '', '' },
      abilities = { { name = 'lion_impale', level = 2, cd = 7.3 }, { name = 'lion_voodoo', level = 1, cd = 0 }, { name = 'lion_mana_drain', level = 2, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = 6095.8, y = -4979.5, hp = 574, max_hp = 1155, mp = 183, max_mp = 414, level = 5, alive = true, tp_cd = 0, items = { 'tranquil_boots', 'blood_grenade', 'magic_wand', 'observer_ward', 'null_talisman', 'gloves_of_haste', '', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 0 }, { name = 'ogre_magi_ignite', level = 3, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 0 }, { name = 'ogre_magi_multicast', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_phantom_assassin', team = 2, x = 4279.8, y = -6024.9, hp = 978, max_hp = 978, mp = 387, max_mp = 387, level = 6, alive = true, tp_cd = 0, items = { 'magic_wand', 'belt_of_strength', 'boots_of_speed', 'quelling_blade', 'orb_of_corrosion', '', '', '', '' },
      abilities = { { name = 'phantom_assassin_stifling_dagger', level = 3, cd = 0 }, { name = 'phantom_assassin_phantom_strike', level = 1, cd = 0 }, { name = 'phantom_assassin_blur', level = 1, cd = 0 }, { name = 'phantom_assassin_immaterial', level = 1, cd = 0 }, { name = 'phantom_assassin_coupde_grace', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6455.5, y = -3327.5, hp = 934, max_hp = 934, mp = 257, max_mp = 339, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 3, cd = 3.5 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = -4163.4, y = 3831.5, hp = 713, max_hp = 830, mp = 270, max_mp = 387, level = 4, alive = true, tp_cd = 17.5, items = { 'blood_grenade', 'tango', 'boots_of_speed', 'wind_lace', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 2, cd = 4.8 }, { name = 'vengeful_spirit_wave_of_terror', level = 2, cd = 0.7 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_warlock', team = 3, x = 6564.8, y = -1012.2, hp = 868, max_hp = 868, mp = 617, max_mp = 680, level = 5, alive = true, tp_cd = 36.5, items = { 'tango', 'dustof_appearance', 'boots_of_speed', 'wizard_hat', 'magic_wand', 'ring_of_basilius', 'blood_grenade', 'clarity', '' },
      abilities = { { name = 'warlock_fatal_bonds', level = 2, cd = 0 }, { name = 'warlock_shadow_word', level = 0, cd = 0 }, { name = 'warlock_upheaval', level = 3, cd = 0 }, { name = 'warlock_eldritch_summoning', level = 1, cd = 0 }, { name = 'warlock_rain_of_chaos', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
    },
    died_after = 18.0,
  },
}
