-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_175703_slot1 @ t=47.4 (0:47), subject sven.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_175703_slot1', time = 47.4, window = 5.0,
  self = 'npc_dota_hero_sven',
  units = {
    { name = 'npc_dota_hero_axe', team = 2, x = -5718.0, y = 4693.1, hp = 595, max_hp = 736, mp = 292, max_mp = 327, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_stick', 'ironwood_branch', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'axe_berserkers_call', level = 0, cd = 0 }, { name = 'axe_battle_hunger', level = 1, cd = 5.4 }, { name = 'axe_counter_helix', level = 0, cd = 0 }, { name = 'axe_culling_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = -5969.8, y = 5003.4, hp = 620, max_hp = 714, mp = 231, max_mp = 327, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_stick', 'ironwood_branch', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0.1 }, { name = 'chaos_knight_reality_rift', level = 0, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 0, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ember_spirit', team = 2, x = -1024.5, y = -892.3, hp = 670, max_hp = 670, mp = 363, max_mp = 363, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'quelling_blade', '', '', '', '' },
      abilities = { { name = 'ember_spirit_searing_chains', level = 0, cd = 0 }, { name = 'ember_spirit_sleight_of_fist', level = 1, cd = 0 }, { name = 'ember_spirit_flame_guard', level = 1, cd = 0 }, { name = 'ember_spirit_activate_fire_remnant', level = 0, cd = 0 }, { name = 'ember_spirit_immolation', level = 1, cd = 0 }, { name = 'ember_spirit_fire_remnant', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = 41.2, y = 96.4, hp = 626, max_hp = 626, mp = 269, max_mp = 339, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'enchanted_mango', '', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 1, cd = 0 }, { name = 'nevermore_shadowraze2', level = 1, cd = 0 }, { name = 'nevermore_shadowraze3', level = 1, cd = 1.3 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 1, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 3, x = -5859.6, y = 4953.5, hp = 680, max_hp = 780, mp = 222, max_mp = 300, level = 1, alive = true, tp_cd = 0, items = { 'clarity', 'tango', 'ironwood_branch', 'ironwood_branch', 'circlet', 'mantle', 'blood_grenade', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 0, cd = 0 }, { name = 'ogre_magi_ignite', level = 1, cd = 14.2 }, { name = 'ogre_magi_bloodlust', level = 0, cd = 0 }, { name = 'ogre_magi_multicast', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_shadow_shaman', team = 3, x = 5914.3, y = -5061.0, hp = 676, max_hp = 676, mp = 387, max_mp = 387, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'clarity', '', 'faerie_fire', 'blood_grenade', 'magic_wand', '', '', '' },
      abilities = { { name = 'shadow_shaman_ether_shock', level = 1, cd = 0 }, { name = 'shadow_shaman_voodoo', level = 0, cd = 0 }, { name = 'shadow_shaman_shackles', level = 0, cd = 0 }, { name = 'shadow_shaman_fowl_play', level = 1, cd = 0 }, { name = 'shadow_shaman_mass_serpent_ward', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = -6234.7, y = 4734.1, hp = 582, max_hp = 582, mp = 279, max_mp = 279, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'magic_stick', 'clarity', 'slippers', 'circlet', 'ironwood_branch', 'ironwood_branch', '' },
      abilities = { { name = 'sniper_shrapnel', level = 0, cd = 0 }, { name = 'sniper_headshot', level = 1, cd = 0 }, { name = 'sniper_take_aim', level = 0, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 2, x = 5889.7, y = -5479.2, hp = 714, max_hp = 714, mp = 194, max_mp = 303, level = 1, alive = true, tp_cd = 0, items = { 'tango', '', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 20.8 }, { name = 'sven_great_cleave', level = 0, cd = 0 }, { name = 'sven_warcry', level = 0, cd = 0 }, { name = 'sven_gods_strength', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_viper', team = 3, x = 6289.5, y = -5327.4, hp = 692, max_hp = 692, mp = 339, max_mp = 339, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'magic_stick', 'ironwood_branch', 'enchanted_mango', 'circlet', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'viper_poison_attack', level = 1, cd = 0 }, { name = 'viper_nethertoxin', level = 0, cd = 0 }, { name = 'viper_corrosive_skin', level = 0, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 2, x = 5458.9, y = -5898.3, hp = 676, max_hp = 676, mp = 375, max_mp = 375, level = 1, alive = true, tp_cd = 0, items = { 'clarity', 'tango', '', '', 'blood_grenade', 'magic_wand', '', '', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 1, cd = 0 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 0, cd = 0 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_viper'] = 124,
      ['npc_dota_hero_shadow_shaman'] = 58,
    },
    died_after = 122.5,
  },
}
