-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_182552_slot1 @ t=626.0 (10:26), subject warlock.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_182552_slot1', time = 626.0, window = 5.0,
  self = 'npc_dota_hero_warlock',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 3, x = 712.1, y = 3874.4, hp = 1314, max_hp = 1314, mp = 614, max_mp = 692, level = 9, alive = true, tp_cd = 26.7, items = { 'blade_mail', 'bracer', 'arcane_boots', 'quelling_blade', 'magic_wand', '', '', '', '' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 4, cd = 2 }, { name = 'bristleback_bristleback', level = 3, cd = 0 }, { name = 'bristleback_warpath', level = 1, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_drow_ranger', team = 3, x = -82.5, y = -79.7, hp = 656, max_hp = 1000, mp = 242, max_mp = 483, level = 11, alive = true, tp_cd = 0, items = { '', 'power_treads', '', 'wraith_band', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'drow_ranger_frost_arrows', level = 4, cd = 0 }, { name = 'drow_ranger_wave_of_silence', level = 1, cd = 0 }, { name = 'drow_ranger_multishot', level = 4, cd = 13.5 }, { name = 'drow_ranger_marksmanship', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 2, x = -1857.2, y = 1158.2, hp = 1352, max_hp = 1352, mp = 932, max_mp = 932, level = 11, alive = true, tp_cd = 0, items = { 'arcane_boots', 'urn_of_shadows', 'sentry_ward', 'magic_wand', 'mekansm', 'flask', 'foragers_mana', '', 'tango' },
      abilities = { { name = 'jakiro_dual_breath', level = 4, cd = 0 }, { name = 'jakiro_ice_path', level = 4, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 1, cd = 31.8 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = -1539.3, y = -5052.9, hp = 1233, max_hp = 1505, mp = 412, max_mp = 513, level = 9, alive = true, tp_cd = 0, items = { 'tranquil_boots', 'observer_ward', 'hand_of_midas', 'shadow_amulet', 'null_talisman', 'magic_wand', 'blood_grenade', 'smoke_of_deceit', 'clarity' },
      abilities = { { name = 'ogre_magi_fireblast', level = 3, cd = 0 }, { name = 'ogre_magi_ignite', level = 3, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 2, cd = 11.3 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_queen_of_pain', team = 3, x = 6260.7, y = 5344.8, hp = 541, max_hp = 1089, mp = 213, max_mp = 1066, level = 9, alive = true, tp_cd = 0, items = { 'clarity', 'magic_wand', 'oblivion_staff', 'power_treads', 'null_talisman', 'empty_bottle', '', '', '' },
      abilities = { { name = 'queen_of_pain_shadow_strike', level = 2, cd = 0 }, { name = 'queen_of_pain_blink', level = 2, cd = 3.7 }, { name = 'queen_of_pain_scream_of_pain', level = 4, cd = 0 }, { name = 'queen_of_pain_innate_seduction', level = 1, cd = 0 }, { name = 'queen_of_pain_sonic_wave', level = 1, cd = 56.2 } } },
    { name = 'npc_dota_hero_silencer', team = 3, x = 3427.5, y = -694.4, hp = 1225, max_hp = 1225, mp = 803, max_mp = 855, level = 10, alive = true, tp_cd = 0, items = { 'tranquil_boots', 'force_staff', 'magic_wand', 'observer_ward', 'blood_grenade', 'smoke_of_deceit', '', '', '' },
      abilities = { { name = 'silencer_curse_of_the_silent', level = 4, cd = 0 }, { name = 'silencer_glaives_of_wisdom', level = 1, cd = 0 }, { name = 'silencer_last_word', level = 3, cd = 0 }, { name = 'silencer_brain_drain', level = 1, cd = 0 }, { name = 'silencer_global_silence', level = 1, cd = 0 }, { name = 'special_bonus_attack_speed25', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = 7420.4, y = -1134.1, hp = 1396, max_hp = 1396, mp = 454, max_mp = 687, level = 13, alive = true, tp_cd = 0, items = { 'dragon_lance', 'mask_of_madness', 'magic_wand', 'power_treads', 'wraith_band', 'infused_raindrop', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 4, cd = 0 }, { name = 'sniper_headshot', level = 4, cd = 0 }, { name = 'sniper_take_aim', level = 3, cd = 0 }, { name = 'sniper_concussive_grenade', level = 1, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_storm_spirit', team = 2, x = -2638.8, y = -2323.2, hp = 1310, max_hp = 1310, mp = 1318, max_mp = 1318, level = 12, alive = true, tp_cd = 0, items = { 'falcon_blade', 'witch_blade', 'staff_of_wizardry', 'null_talisman', 'arcane_boots', 'magic_wand', 'clarity', 'robe_of_magi', '' },
      abilities = { { name = 'storm_spirit_static_remnant', level = 4, cd = 0 }, { name = 'storm_spirit_electric_vortex', level = 1, cd = 0 }, { name = 'storm_spirit_overload', level = 4, cd = 0 }, { name = 'storm_spirit_ball_lightning', level = 2, cd = 0 }, { name = 'storm_spirit_galvanized', level = 1, cd = 0 }, { name = 'special_bonus_m_p_regen150', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_viper', team = 2, x = -7150.3, y = -6541.4, hp = 1308, max_hp = 1308, mp = 615, max_mp = 615, level = 12, alive = true, tp_cd = 0, items = { 'mage_slayer', 'magic_wand', 'wraith_band', 'blade_of_alacrity', 'wraith_band', 'power_treads', 'enchanted_mango', '', '' },
      abilities = { { name = 'viper_poison_attack', level = 4, cd = 0 }, { name = 'viper_nethertoxin', level = 1, cd = 0 }, { name = 'viper_corrosive_skin', level = 4, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 2, cd = 0 } } },
    { name = 'npc_dota_hero_warlock', team = 3, x = 6583.1, y = -1695.9, hp = 546, max_hp = 1022, mp = 788, max_mp = 788, level = 8, alive = true, tp_cd = 0, items = { 'tango', 'arcane_boots', 'sentry_ward', 'shadow_amulet', 'magic_wand', 'shawl', '', '', '' },
      abilities = { { name = 'warlock_fatal_bonds', level = 2, cd = 0 }, { name = 'warlock_shadow_word', level = 4, cd = 0 }, { name = 'warlock_upheaval', level = 1, cd = 0 }, { name = 'warlock_eldritch_summoning', level = 1, cd = 0 }, { name = 'warlock_rain_of_chaos', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_sniper'] = 669,
    },
    died_after = 2.3,
  },
}
