-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_181441_slot1 @ t=524.0 (8:44), subject luna.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_181441_slot1', time = 524.0, window = 5.0,
  self = 'npc_dota_hero_luna',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 3, x = 1704.1, y = -6344.7, hp = 1165, max_hp = 1313, mp = 499, max_mp = 692, level = 9, alive = true, tp_cd = 0, items = { 'blade_mail', 'bracer', 'arcane_boots', 'quelling_blade', 'magic_wand', '', '', '', '' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 4, cd = 1.8 }, { name = 'bristleback_bristleback', level = 3, cd = 0 }, { name = 'bristleback_warpath', level = 1, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_centaur', team = 2, x = -6431.9, y = -353.5, hp = 1352, max_hp = 1352, mp = 399, max_mp = 399, level = 7, alive = true, tp_cd = 0, items = { 'phase_boots', 'magic_wand', 'helm_of_iron_will', 'quelling_blade', 'ring_of_protection', 'tango', '', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 2, cd = 0 }, { name = 'centaur_double_edge', level = 4, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 1, cd = 0 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 2, x = -1162.8, y = -2882.0, hp = 0, max_hp = 0, mp = 284, max_mp = 621, level = 6, alive = false, tp_cd = 0, items = { 'null_talisman', 'tranquil_boots', 'tango', 'magic_wand', 'headdress', 'observer_ward', '', 'blood_grenade', '' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 0 }, { name = 'crystal_maiden_frostbite', level = 3, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 2, x = -1034.3, y = -3778.2, hp = 1767, max_hp = 2195, mp = 321, max_mp = 531, level = 10, alive = true, tp_cd = 16, items = { 'power_treads', 'magic_wand', 'armlet', 'quelling_blade', 'bracer', '', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 3, cd = 0 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 2 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 1, cd = 84.9 } } },
    { name = 'npc_dota_hero_jakiro', team = 3, x = -3443.3, y = 4009.2, hp = 1112, max_hp = 1353, mp = 412, max_mp = 757, level = 8, alive = true, tp_cd = 0, items = { 'null_talisman', 'tranquil_boots', 'ancient_janggo', 'magic_wand', 'tango', 'observer_ward', 'famango', '', '' },
      abilities = { { name = 'jakiro_dual_breath', level = 4, cd = 0 }, { name = 'jakiro_ice_path', level = 2, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -5535.6, y = 1176.7, hp = 849, max_hp = 1067, mp = 72, max_mp = 591, level = 9, alive = true, tp_cd = 0, items = { 'boots_of_elven', 'magic_wand', 'power_treads', 'wraith_band', 'mask_of_madness', 'blade_of_alacrity', 'clarity', 'tango', 'quelling_blade' },
      abilities = { { name = 'luna_lucent_beam', level = 4, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 4, cd = 0 }, { name = 'luna_eclipse', level = 1, cd = 80.9 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = -901.3, y = -2225.6, hp = 0, max_hp = 0, mp = 503, max_mp = 639, level = 13, alive = false, tp_cd = 29, items = { 'dragon_lance', 'magic_wand', 'power_treads', 'mask_of_death', 'lesser_critical', 'empty_bottle', 'tango', '', 'enchanted_mango' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 0 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0 }, { name = 'nevermore_shadowraze3', level = 4, cd = 0 }, { name = 'nevermore_frenzy', level = 2, cd = 0 }, { name = 'nevermore_presence', level = 4, cd = 0 }, { name = 'nevermore_requiem', level = 2, cd = 0 } } },
    { name = 'npc_dota_hero_shadow_shaman', team = 3, x = -480.2, y = -1433.9, hp = 985, max_hp = 1022, mp = 545, max_mp = 824, level = 9, alive = true, tp_cd = 24.1, items = { 'tango', 'glimmer_cape', 'arcane_boots', 'faerie_fire', 'sentry_ward', 'magic_wand', '', '', 'blood_grenade' },
      abilities = { { name = 'shadow_shaman_ether_shock', level = 4, cd = 0 }, { name = 'shadow_shaman_voodoo', level = 2, cd = 0 }, { name = 'shadow_shaman_shackles', level = 2, cd = 0 }, { name = 'shadow_shaman_fowl_play', level = 1, cd = 0 }, { name = 'shadow_shaman_mass_serpent_ward', level = 1, cd = 51.2 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = -6382.3, y = -611.2, hp = 867, max_hp = 1006, mp = 452, max_mp = 531, level = 8, alive = true, tp_cd = 0, items = { 'infused_raindrop', 'power_treads', 'magic_wand', 'blood_grenade', 'wraith_band', 'sentry_ward', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 3, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -1307.0, y = -3544.8, hp = 1132, max_hp = 1310, mp = 553, max_mp = 908, level = 11, alive = true, tp_cd = 0, items = { '', 'arcane_boots', '', '', 'empty_bottle', 'magic_wand', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 4, cd = 1.1 }, { name = 'zuus_lightning_bolt', level = 4, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 15.8 }, { name = 'zuus_thundergods_wrath', level = 1, cd = 0 }, { name = 'special_bonus_h_p200', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_sniper'] = 312,
      ['npc_dota_hero_centaur'] = 147,
    },
    died_after = 6.9,
  },
}
