-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_181441_slot1 @ t=660.0 (11:00), subject zuus.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_181441_slot1', time = 660.0, window = 5.0,
  self = 'npc_dota_hero_zuus',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 3, x = 6693.4, y = 5896.2, hp = 1696, max_hp = 1696, mp = 764, max_mp = 764, level = 11, alive = true, tp_cd = 37.7, items = { 'blade_mail', 'bracer', 'arcane_boots', 'quelling_blade', 'magic_wand', 'vanguard', '', '', '' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 4, cd = 0 }, { name = 'bristleback_bristleback', level = 4, cd = 0 }, { name = 'bristleback_warpath', level = 1, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 }, { name = 'special_bonus_m_p_regen150', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_centaur', team = 2, x = -127.7, y = -176.3, hp = 727, max_hp = 1923, mp = 214, max_mp = 603, level = 11, alive = true, tp_cd = 0, items = { 'phase_boots', 'magic_wand', 'helm_of_iron_will', 'quelling_blade', 'ring_of_protection', 'veil_of_discord', 'clarity', 'tango', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 4, cd = 0 }, { name = 'centaur_double_edge', level = 4, cd = 0 }, { name = 'centaur_return', level = 1, cd = 0 }, { name = 'centaur_stampede', level = 1, cd = 28.9 }, { name = 'centaur_horsepower', level = 1, cd = 0 }, { name = 'special_bonus_h_p_regen4', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 2, x = -3812.7, y = -1032.5, hp = 766, max_hp = 1110, mp = 561, max_mp = 745, level = 9, alive = true, tp_cd = 32.5, items = { 'null_talisman', 'tranquil_boots', 'wind_lace', 'magic_wand', 'headdress', 'belt_of_strength', 'blood_grenade', 'clarity', 'tango' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 3, cd = 6.1 }, { name = 'crystal_maiden_frostbite', level = 4, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 2, x = -152.6, y = -363.5, hp = 1798, max_hp = 1798, mp = 567, max_mp = 567, level = 12, alive = true, tp_cd = 10.2, items = { 'power_treads', 'magic_wand', 'armlet', 'blade_of_alacrity', 'bracer', 'boots_of_elven', 'quelling_blade', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 2, cd = 0 }, { name = 'special_bonus_attack_damage15', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 3, x = -2695.8, y = 4078.6, hp = 1373, max_hp = 1573, mp = 572, max_mp = 905, level = 12, alive = true, tp_cd = 0, items = { 'null_talisman', 'tranquil_boots', 'ancient_janggo', 'magic_wand', 'observer_ward', 'glimmer_cape', 'great_famango', 'famango', '' },
      abilities = { { name = 'jakiro_dual_breath', level = 4, cd = 0 }, { name = 'jakiro_ice_path', level = 4, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 2, cd = 9.2 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -601.8, y = 3612.6, hp = 1162, max_hp = 1241, mp = 589, max_mp = 687, level = 10, alive = true, tp_cd = 0, items = { 'yasha', 'magic_wand', 'power_treads', 'wraith_band', 'mask_of_madness', 'diadem', 'quelling_blade', '', 'tango' },
      abilities = { { name = 'luna_lucent_beam', level = 4, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 4, cd = 0 }, { name = 'luna_eclipse', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = -4375.1, y = -275.5, hp = 940, max_hp = 1836, mp = 259, max_mp = 675, level = 15, alive = true, tp_cd = 0, items = { 'dragon_lance', 'mithril_hammer', 'power_treads', 'mask_of_death', 'lesser_critical', 'ogre_axe', '', 'magic_wand', 'enchanted_mango' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 0 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0 }, { name = 'nevermore_shadowraze3', level = 4, cd = 1.3 }, { name = 'nevermore_frenzy', level = 3, cd = 0 }, { name = 'nevermore_presence', level = 4, cd = 0 }, { name = 'nevermore_requiem', level = 2, cd = 40.7 } } },
    { name = 'npc_dota_hero_shadow_shaman', team = 3, x = 4542.4, y = 3518.3, hp = 1156, max_hp = 1357, mp = 750, max_mp = 1083, level = 11, alive = true, tp_cd = 0, items = { 'point_booster', 'glimmer_cape', 'arcane_boots', 'blood_grenade', 'sentry_ward', 'magic_wand', '', '', '' },
      abilities = { { name = 'shadow_shaman_ether_shock', level = 4, cd = 0 }, { name = 'shadow_shaman_voodoo', level = 2, cd = 0 }, { name = 'shadow_shaman_shackles', level = 3, cd = 0 }, { name = 'shadow_shaman_fowl_play', level = 1, cd = 0 }, { name = 'shadow_shaman_urnaconda', level = 1, cd = 0 }, { name = 'shadow_shaman_mass_serpent_ward', level = 1, cd = 30 }, { name = 'special_bonus_m_p_regen175', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = -4882.0, y = 780.0, hp = 0, max_hp = 0, mp = 591, max_mp = 591, level = 10, alive = false, tp_cd = 3.2, items = { 'infused_raindrop', 'power_treads', 'magic_wand', 'dragon_lance', 'wraith_band', 'sentry_ward', '', 'blood_grenade', '' },
      abilities = { { name = 'sniper_shrapnel', level = 4, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -5645.8, y = -1841.7, hp = 214, max_hp = 1354, mp = 886, max_mp = 944, level = 12, alive = true, tp_cd = 16.6, items = { 'perseverance', 'arcane_boots', '', '', 'empty_bottle', 'magic_wand', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 4, cd = 0 }, { name = 'zuus_lightning_bolt', level = 4, cd = 1.8 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 2, cd = 2.2 }, { name = 'special_bonus_h_p200', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
    },
    died_after = nil,
  },
}
