-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_181544_slot1 @ t=591.0 (9:51), subject storm_spirit.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_181544_slot1', time = 591.0, window = 5.0,
  self = 'npc_dota_hero_storm_spirit',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 3, x = 561.0, y = -4746.6, hp = 1351, max_hp = 1741, mp = 546, max_mp = 788, level = 12, alive = true, tp_cd = 0, items = { 'blade_mail', 'bracer', 'vanguard', 'helm_of_iron_will', 'magic_wand', 'arcane_boots', '', 'tango', 'quelling_blade' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 4, cd = 1.1 }, { name = 'bristleback_bristleback', level = 4, cd = 0 }, { name = 'bristleback_warpath', level = 2, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 }, { name = 'special_bonus_m_p_regen150', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_drow_ranger', team = 3, x = -1670.8, y = 3018.5, hp = 1155, max_hp = 1352, mp = 299, max_mp = 555, level = 11, alive = true, tp_cd = 0, items = { 'yasha', 'power_treads', 'dragon_lance', 'wraith_band', 'diadem', 'magic_wand', '', '', '' },
      abilities = { { name = 'drow_ranger_frost_arrows', level = 4, cd = 0 }, { name = 'drow_ranger_wave_of_silence', level = 1, cd = 0 }, { name = 'drow_ranger_multishot', level = 4, cd = 0 }, { name = 'drow_ranger_marksmanship', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 2, x = -6232.3, y = 3689.2, hp = 1220, max_hp = 1220, mp = 732, max_mp = 800, level = 9, alive = true, tp_cd = 38.4, items = { 'arcane_boots', 'sentry_ward', 'ring_of_protection', 'magic_wand', 'sobi_mask', 'circlet', '', 'blood_grenade', 'flask' },
      abilities = { { name = 'jakiro_dual_breath', level = 4, cd = 0 }, { name = 'jakiro_ice_path', level = 3, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = 11.9, y = -4771.7, hp = 420, max_hp = 1419, mp = 217, max_mp = 488, level = 8, alive = true, tp_cd = 0, items = { 'gloves_of_haste', 'tango', 'magic_wand', 'observer_ward', 'null_talisman', 'tranquil_boots', '', 'clarity', 'blood_grenade' },
      abilities = { { name = 'ogre_magi_fireblast', level = 2, cd = 8.4 }, { name = 'ogre_magi_ignite', level = 3, cd = 4.3 }, { name = 'ogre_magi_bloodlust', level = 2, cd = 0 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_queen_of_pain', team = 3, x = -79.7, y = 221.1, hp = 1078, max_hp = 1286, mp = 484, max_mp = 1449, level = 13, alive = true, tp_cd = 0, items = { 'witch_blade', 'magic_wand', 'power_treads', 'kaya', 'null_talisman', 'empty_bottle', 'tango', '', '' },
      abilities = { { name = 'queen_of_pain_shadow_strike', level = 2, cd = 5.2 }, { name = 'queen_of_pain_blink', level = 4, cd = 1.8 }, { name = 'queen_of_pain_scream_of_pain', level = 4, cd = 2.4 }, { name = 'queen_of_pain_innate_seduction', level = 1, cd = 0 }, { name = 'queen_of_pain_sonic_wave', level = 2, cd = 44.3 } } },
    { name = 'npc_dota_hero_silencer', team = 3, x = 2750.8, y = -1878.6, hp = 1175, max_hp = 1175, mp = 951, max_mp = 951, level = 10, alive = true, tp_cd = 0, items = { 'magic_wand', 'shawl', 'tranquil_boots', 'clarity', 'force_staff', 'shadow_amulet', '', '', '' },
      abilities = { { name = 'silencer_curse_of_the_silent', level = 4, cd = 0 }, { name = 'silencer_glaives_of_wisdom', level = 1, cd = 0 }, { name = 'silencer_last_word', level = 3, cd = 0 }, { name = 'silencer_brain_drain', level = 1, cd = 0 }, { name = 'silencer_global_silence', level = 1, cd = 1.6 }, { name = 'special_bonus_attack_speed25', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = 4110.4, y = -6234.8, hp = 1308, max_hp = 1308, mp = 478, max_mp = 627, level = 11, alive = true, tp_cd = 3.3, items = { 'dragon_lance', 'broadsword', 'magic_wand', 'power_treads', 'wraith_band', 'infused_raindrop', 'tango', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 4, cd = 0 }, { name = 'sniper_headshot', level = 3, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 8.5 } } },
    { name = 'npc_dota_hero_storm_spirit', team = 2, x = -726.3, y = -669.8, hp = 615, max_hp = 1420, mp = 1173, max_mp = 1405, level = 13, alive = true, tp_cd = 0, items = { 'falcon_blade', 'witch_blade', 'staff_of_wizardry', 'null_talisman', 'arcane_boots', 'magic_wand', '', 'tango', 'robe_of_magi' },
      abilities = { { name = 'storm_spirit_static_remnant', level = 4, cd = 0 }, { name = 'storm_spirit_electric_vortex', level = 2, cd = 0 }, { name = 'storm_spirit_overload', level = 4, cd = 0 }, { name = 'storm_spirit_ball_lightning', level = 2, cd = 0 }, { name = 'storm_spirit_galvanized', level = 1, cd = 0 }, { name = 'special_bonus_m_p_regen150', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_viper', team = 2, x = -6349.2, y = 3972.8, hp = 1154, max_hp = 1154, mp = 443, max_mp = 507, level = 9, alive = true, tp_cd = 0, items = { 'power_treads', 'magic_wand', 'wraith_band', 'enchanted_mango', 'wraith_band', 'perseverance', '', '', '' },
      abilities = { { name = 'viper_poison_attack', level = 4, cd = 0 }, { name = 'viper_nethertoxin', level = 1, cd = 0 }, { name = 'viper_corrosive_skin', level = 3, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 1, cd = 0.5 } } },
    { name = 'npc_dota_hero_warlock', team = 3, x = -20.0, y = 621.6, hp = 1110, max_hp = 1131, mp = 713, max_mp = 860, level = 10, alive = true, tp_cd = 0, items = { 'tango', 'headdress', 'arcane_boots', 'sentry_ward', 'magic_wand', 'glimmer_cape', '', 'blood_grenade', '' },
      abilities = { { name = 'warlock_fatal_bonds', level = 4, cd = 17.2 }, { name = 'warlock_shadow_word', level = 0, cd = 0 }, { name = 'warlock_upheaval', level = 4, cd = 0 }, { name = 'warlock_eldritch_summoning', level = 1, cd = 0 }, { name = 'warlock_rain_of_chaos', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_queenofpain'] = 496,
      ['npc_dota_hero_warlock'] = 76,
    },
    died_after = 5.1,
  },
}
