-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260721_222428_slot1 @ t=314.0 (5:14), subject lion.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 8s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260721_222428_slot1', time = 314.0, window = 8.0,
  self = 'npc_dota_hero_lion',
  units = {
    { name = 'npc_dota_hero_axe', team = 3, x = 4787.4, y = -5464.3, hp = 629, max_hp = 1719, mp = 151, max_mp = 459, level = 7, alive = true, tp_cd = 0, items = { 'power_treads', 'vitality_booster', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'axe_berserkers_call', level = 1, cd = 6.7 }, { name = 'axe_battle_hunger', level = 1, cd = 16.8 }, { name = 'axe_counter_helix', level = 4, cd = 0 }, { name = 'axe_culling_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = -6985.2, y = -6340.1, hp = 1138, max_hp = 1138, mp = 352, max_mp = 399, level = 5, alive = true, tp_cd = 39, items = { 'clarity', 'flask', 'quelling_blade', 'magic_wand', 'bracer', 'boots_of_speed', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 3, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 2, x = -1103.0, y = -1082.1, hp = 1132, max_hp = 1132, mp = 440, max_mp = 800, level = 8, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'arcane_boots', 'faerie_fire', 'circlet', 'empty_bottle', '', '', 'clarity' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 4, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 3, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 38.3 } } },
    { name = 'npc_dota_hero_drow_ranger', team = 3, x = -6060.3, y = 3575.4, hp = 0, max_hp = 0, mp = 319, max_mp = 363, level = 4, alive = false, tp_cd = 0, items = { 'power_treads', 'flask', '', 'wraith_band', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'drow_ranger_frost_arrows', level = 2, cd = 0 }, { name = 'drow_ranger_wave_of_silence', level = 1, cd = 0 }, { name = 'drow_ranger_multishot', level = 1, cd = 0 }, { name = 'drow_ranger_marksmanship', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 3, x = 4954.3, y = -5799.6, hp = 701, max_hp = 896, mp = 328, max_mp = 776, level = 6, alive = true, tp_cd = 0, items = { 'arcane_boots', 'sobi_mask', 'tango', 'blood_grenade', 'magic_wand', '', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 3, cd = 6.4 }, { name = 'lich_frost_shield', level = 1, cd = 6.6 }, { name = 'lich_sinister_gaze', level = 1, cd = 1.1 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 2, x = 4322.5, y = -6041.2, hp = 354, max_hp = 823, mp = 485, max_mp = 584, level = 5, alive = true, tp_cd = 0, items = { 'null_talisman', 'tranquil_boots', 'observer_ward', 'magic_wand', 'headdress', 'flask', '', 'blood_grenade', 'tango' },
      abilities = { { name = 'lion_impale', level = 2, cd = 4.8 }, { name = 'lion_voodoo', level = 1, cd = 6.9 }, { name = 'lion_mana_drain', level = 2, cd = 11 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_necrolyte', team = 3, x = 6928.4, y = 6372.0, hp = 429, max_hp = 1094, mp = 31, max_mp = 627, level = 8, alive = true, tp_cd = 36.5, items = { 'tango', 'magic_wand', 'bracer', 'faerie_fire', 'boots_of_speed', '', '', '', '' },
      abilities = { { name = 'necrolyte_death_pulse', level = 4, cd = 4.7 }, { name = 'necrolyte_ghost_shroud', level = 1, cd = 23 }, { name = 'necrolyte_heartstopper_aura', level = 2, cd = 0 }, { name = 'necrolyte_reapers_scythe', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_silencer', team = 3, x = -6384.8, y = 3609.7, hp = 0, max_hp = 0, mp = 144, max_mp = 519, level = 4, alive = false, tp_cd = 0, items = { 'tranquil_boots', 'blood_grenade', 'magic_wand', 'observer_ward', 'flask', '', '', '', '' },
      abilities = { { name = 'silencer_curse_of_the_silent', level = 2, cd = 6.1 }, { name = 'silencer_glaives_of_wisdom', level = 1, cd = 0 }, { name = 'silencer_last_word', level = 1, cd = 9 }, { name = 'silencer_brain_drain', level = 1, cd = 0 }, { name = 'silencer_global_silence', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_viper', team = 2, x = -6463.3, y = 3405.2, hp = 368, max_hp = 1000, mp = 471, max_mp = 471, level = 6, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'magic_wand', 'wraith_band', 'enchanted_mango', 'wraith_band', '', '', '', '' },
      abilities = { { name = 'viper_poison_attack', level = 3, cd = 0 }, { name = 'viper_nethertoxin', level = 0, cd = 0 }, { name = 'viper_corrosive_skin', level = 2, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 2, x = -6135.7, y = 3317.6, hp = 438, max_hp = 934, mp = 513, max_mp = 740, level = 7, alive = true, tp_cd = 0, items = { 'arcane_boots', 'urn_of_shadows', 'clarity', '', 'enchanted_mango', 'magic_wand', '', '', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 2, cd = 4.9 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 4, cd = 8.4 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 1, cd = 87.5 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_lich'] = 436,
      ['npc_dota_hero_axe'] = 84,
    },
    died_after = 6.9,
  },
}
