-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260721_225947 @ t=367.0 (6:07), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 6s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260721_225947', time = 367.0, window = 6.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = -5980.8, y = 2865.5, hp = 1426, max_hp = 1490, mp = 255, max_mp = 435, level = 7, alive = true, tp_cd = 0, items = { '', '', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 0.4 }, { name = 'chaos_knight_chaos_strike', level = 4, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 3, x = -5638.8, y = 3233.5, hp = 477, max_hp = 890, mp = 135, max_mp = 584, level = 4, alive = true, tp_cd = 39.2, items = { 'null_talisman', 'boots_of_speed', 'tango', 'magic_stick', 'observer_ward', 'ironwood_branch', '', 'ironwood_branch', 'blood_grenade' },
      abilities = { { name = 'jakiro_dual_breath', level = 2, cd = 0 }, { name = 'jakiro_ice_path', level = 1, cd = 18.2 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = 262.5, y = 273.4, hp = 299, max_hp = 824, mp = 473, max_mp = 639, level = 6, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'observer_ward', '', '', '', 'boots_of_speed', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 3, cd = 0 }, { name = 'lich_frost_shield', level = 1, cd = 7.1 }, { name = 'lich_sinister_gaze', level = 1, cd = 1.7 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 3, x = 528.1, y = 226.8, hp = 0, max_hp = 0, mp = 940, max_mp = 1022, level = 8, alive = false, tp_cd = 0, items = { 'faerie_fire', 'magic_wand', 'arcane_boots', 'tango', 'null_talisman', 'empty_bottle', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 4, cd = 0 }, { name = 'lina_light_strike_array', level = 2, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -4095.0, y = 2347.8, hp = 0, max_hp = 0, mp = 71, max_mp = 519, level = 6, alive = false, tp_cd = 0, items = { '', 'magic_wand', 'power_treads', 'wraith_band', '', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 3, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 2, cd = 0 }, { name = 'luna_eclipse', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 2, x = 342.7, y = 514.2, hp = 982, max_hp = 1285, mp = 379, max_mp = 531, level = 9, alive = true, tp_cd = 0, items = { 'tango_single', 'magic_wand', 'power_treads', 'faerie_fire', 'mask_of_death', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 8.2 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0.1 }, { name = 'nevermore_shadowraze3', level = 4, cd = 0 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 4, cd = 0 }, { name = 'nevermore_requiem', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 3, x = 437.1, y = 342.8, hp = 994, max_hp = 1242, mp = 293, max_mp = 551, level = 6, alive = true, tp_cd = 32.3, items = { 'urn_of_shadows', 'sentry_ward', 'magic_wand', 'tango', 'flask', 'arcane_boots', '', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 9 }, { name = 'ogre_magi_ignite', level = 3, cd = 15.6 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 19.3 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 389.6, y = 122.5, hp = 1043, max_hp = 1044, mp = 222, max_mp = 375, level = 7, alive = true, tp_cd = 31.2, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 13.4 }, { name = 'skeleton_king_bone_guard', level = 4, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 2.1 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = -6083.5, y = 2134.8, hp = 682, max_hp = 912, mp = 311, max_mp = 615, level = 7, alive = true, tp_cd = 0, items = { 'sentry_ward', 'blade_of_alacrity', 'magic_wand', 'infused_raindrop', 'wraith_band', 'power_treads', '', 'clarity', 'flask' },
      abilities = { { name = 'sniper_shrapnel', level = 2, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 2, x = 4991.5, y = -6059.6, hp = 1308, max_hp = 1308, mp = 387, max_mp = 387, level = 6, alive = true, tp_cd = 0, items = { 'broadsword', 'power_treads', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 0 }, { name = 'sven_great_cleave', level = 3, cd = 0 }, { name = 'sven_warcry', level = 1, cd = 0 }, { name = 'sven_gods_strength', level = 1, cd = 62.8 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_lich'] = 750,
      ['npc_dota_hero_nevermore'] = 232,
    },
    died_after = 4.6,
  },
}
