-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260721_232320 @ t=380.0 (6:20), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 8s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260721_232320', time = 380.0, window = 8.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = 5603.3, y = -5469.3, hp = 1438, max_hp = 1490, mp = 351, max_mp = 435, level = 7, alive = true, tp_cd = 19, items = { 'helm_of_iron_will', '', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 12.2 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 4, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 21.5 } } },
    { name = 'npc_dota_hero_lina', team = 3, x = 5851.8, y = -4685.5, hp = 824, max_hp = 824, mp = 714, max_mp = 800, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'magic_stick', 'sentry_ward', 'wizard_hat', 'boots_of_speed', 'ironwood_branch', 'ironwood_branch', 'clarity' },
      abilities = { { name = 'lina_dragon_slave', level = 1, cd = 10.1 }, { name = 'lina_light_strike_array', level = 1, cd = 0 }, { name = 'lina_fiery_soul', level = 3, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 3, x = -5735.0, y = 5389.4, hp = 1180, max_hp = 1374, mp = 1555, max_mp = 1844, level = 11, alive = true, tp_cd = 35.7, items = { 'null_talisman', 'magic_wand', 'witch_blade', 'faerie_fire', 'null_talisman', 'power_treads', '', '', '' },
      abilities = { { name = 'obsidian_destroyer_arcane_orb', level = 1, cd = 0 }, { name = 'obsidian_destroyer_astral_imprisonment', level = 4, cd = 11.4 }, { name = 'obsidian_destroyer_objurgation', level = 0, cd = 0 }, { name = 'obsidian_destroyer_sanity_eclipse', level = 1, cd = 97.6 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 2, x = -5885.5, y = 5043.6, hp = 870, max_hp = 1000, mp = 272, max_mp = 272, level = 6, alive = true, tp_cd = 38.2, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 3, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 2.4 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skywrath_mage', team = 2, x = -3140.8, y = -6292.3, hp = 846, max_hp = 846, mp = 603, max_mp = 603, level = 5, alive = true, tp_cd = 5.5, items = { 'tranquil_boots', 'observer_ward', 'shadow_amulet', 'tango', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'skywrath_mage_arcane_bolt', level = 2, cd = 0 }, { name = 'skywrath_mage_concussive_shot', level = 2, cd = 0 }, { name = 'skywrath_mage_ancient_seal', level = 1, cd = 0 }, { name = 'skywrath_mage_mystic_flare', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -771.4, y = 4065.3, hp = 985, max_hp = 1175, mp = 531, max_mp = 531, level = 8, alive = true, tp_cd = 0, items = { 'infused_raindrop', 'dragon_lance', 'magic_wand', 'power_treads', 'wraith_band', 'flask', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 3, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_tidehunter', team = 3, x = 6089.0, y = -4773.3, hp = 1226, max_hp = 1295, mp = 251, max_mp = 471, level = 7, alive = true, tp_cd = 38.1, items = { 'recipe_soul_ring', 'boots_of_speed', 'ring_of_protection', 'quelling_blade', 'gauntlets', 'magic_wand', 'clarity', '', '' },
      abilities = { { name = 'tidehunter_gush', level = 1, cd = 0 }, { name = 'tidehunter_kraken_shell', level = 1, cd = 0 }, { name = 'tidehunter_anchor_smash', level = 4, cd = 0 }, { name = 'tidehunter_ravage', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = -1074.5, y = 4364.7, hp = 912, max_hp = 912, mp = 543, max_mp = 543, level = 6, alive = true, tp_cd = 0, items = { 'tranquil_boots', 'tango', 'observer_ward', 'staff_of_wizardry', '', 'magic_wand', 'famango', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 3, cd = 0 }, { name = 'vengeful_spirit_wave_of_terror', level = 2, cd = 0 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 2, x = -6197.0, y = 4666.8, hp = 896, max_hp = 896, mp = 601, max_mp = 680, level = 6, alive = true, tp_cd = 23, items = { 'tango', 'sentry_ward', 'blood_grenade', 'arcane_boots', 'enchanted_mango', 'magic_wand', '', '', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 2, cd = 9.7 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 3, cd = 0 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -869.3, y = -641.8, hp = 1000, max_hp = 1000, mp = 513, max_mp = 824, level = 9, alive = true, tp_cd = 0, items = { 'tango', 'arcane_boots', 'faerie_fire', 'perseverance', 'empty_bottle', 'magic_wand', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 4, cd = 1.5 }, { name = 'zuus_lightning_bolt', level = 3, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 1, cd = 19.3 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_obsidian_destroyer'] = 915,
    },
    died_after = 5.8,
  },
}
