-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_232228_slot1 @ t=340.0 (5:40), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_232228_slot1', time = 340.0, window = 5.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 3, x = 6111.3, y = -5008.0, hp = 793, max_hp = 1072, mp = 461, max_mp = 560, level = 5, alive = true, tp_cd = 0, items = { '', 'bracer', 'arcane_boots', 'quelling_blade', 'magic_wand', '', '', '', '' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 3, cd = 0.3 }, { name = 'bristleback_bristleback', level = 1, cd = 0 }, { name = 'bristleback_warpath', level = 0, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 2, x = -6719.3, y = -5467.5, hp = 714, max_hp = 714, mp = 547, max_mp = 547, level = 5, alive = true, tp_cd = 23.9, items = { 'null_talisman', 'tranquil_boots', 'tango', 'magic_stick', 'observer_ward', 'clarity', 'ironwood_branch', 'blood_grenade', 'ironwood_branch' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 0 }, { name = 'crystal_maiden_frostbite', level = 3, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_earthshaker', team = 3, x = 5263.2, y = -2767.3, hp = 681, max_hp = 962, mp = 428, max_mp = 524, level = 4, alive = true, tp_cd = 0, items = { '', 'sobi_mask', 'magic_wand', '', 'blood_grenade', 'arcane_boots', '', '', '' },
      abilities = { { name = 'earthshaker_fissure', level = 1, cd = 5 }, { name = 'earthshaker_enchant_totem', level = 1, cd = 0 }, { name = 'earthshaker_aftershock', level = 2, cd = 0 }, { name = 'earthshaker_echo_slam', level = 0, cd = 0 }, { name = 'earthshaker_slugger', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 3, x = 1697.8, y = 584.6, hp = 1066, max_hp = 1066, mp = 132, max_mp = 683, level = 6, alive = true, tp_cd = 12.2, items = { 'null_talisman', 'tango', 'flask', 'magic_wand', 'ring_of_regeneration', 'tranquil_boots', 'clarity', 'blood_grenade', 'dustof_appearance' },
      abilities = { { name = 'jakiro_dual_breath', level = 3, cd = 0 }, { name = 'jakiro_ice_path', level = 1, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_juggernaut', team = 3, x = -6264.2, y = 3988.8, hp = 614, max_hp = 890, mp = 161, max_mp = 387, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'power_treads', '', 'wraith_band', 'magic_wand', 'quelling_blade', '', '', '' },
      abilities = { { name = 'juggernaut_blade_fury', level = 3, cd = 0 }, { name = 'juggernaut_healing_ward', level = 1, cd = 0 }, { name = 'juggernaut_blade_dance', level = 1, cd = 0 }, { name = 'juggernaut_bladeform', level = 1, cd = 0 }, { name = 'juggernaut_omnislash', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_phantom_assassin', team = 2, x = -5820.6, y = -6128.9, hp = 846, max_hp = 846, mp = 387, max_mp = 387, level = 6, alive = true, tp_cd = 22.3, items = { 'boots_of_speed', 'magic_wand', '', 'quelling_blade', 'orb_of_corrosion', '', '', '', '' },
      abilities = { { name = 'phantom_assassin_stifling_dagger', level = 3, cd = 0 }, { name = 'phantom_assassin_phantom_strike', level = 1, cd = 0 }, { name = 'phantom_assassin_blur', level = 1, cd = 24.8 }, { name = 'phantom_assassin_immaterial', level = 1, cd = 0 }, { name = 'phantom_assassin_coupde_grace', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 2, x = -6256.0, y = 2933.7, hp = 934, max_hp = 934, mp = 339, max_mp = 339, level = 5, alive = true, tp_cd = 0, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 2, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 1, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 2, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = -6349.4, y = 2895.9, hp = 792, max_hp = 802, mp = 435, max_mp = 435, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'magic_stick', 'boots_of_elven', 'wraith_band', 'boots_of_speed', 'ironwood_branch', 'ironwood_branch', 'clarity' },
      abilities = { { name = 'sniper_shrapnel', level = 1, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_viper', team = 2, x = -860.7, y = -696.6, hp = 413, max_hp = 1000, mp = 483, max_mp = 483, level = 7, alive = true, tp_cd = 0, items = { 'tango', 'clarity', 'magic_wand', 'power_treads', 'wraith_band', 'faerie_fire', '', '', '' },
      abilities = { { name = 'viper_poison_attack', level = 4, cd = 0 }, { name = 'viper_nethertoxin', level = 1, cd = 0 }, { name = 'viper_corrosive_skin', level = 1, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 3, x = -686.9, y = 2011.8, hp = 956, max_hp = 956, mp = 106, max_mp = 788, level = 8, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'arcane_boots', 'perseverance', 'empty_bottle', '', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 4, cd = 0 }, { name = 'zuus_lightning_bolt', level = 2, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 1, cd = 21.2 } } },
  },
  observed = {
    burst = {
    },
    died_after = 86.7,
  },
}
