-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_230952_slot1 @ t=567.0 (9:27), subject zuus.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_230952_slot1', time = 567.0, window = 5.0,
  self = 'npc_dota_hero_zuus',
  units = {
    { name = 'npc_dota_hero_death_prophet', team = 2, x = -6543.9, y = 2157.4, hp = 596, max_hp = 1183, mp = 580, max_mp = 759, level = 7, alive = true, tp_cd = 0, items = { '', 'power_treads', 'quelling_blade', 'magic_wand', 'bracer', 'clarity', '', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 2, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 4, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 42.2 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = -317.2, y = 205.8, hp = 1578, max_hp = 1578, mp = 621, max_mp = 627, level = 9, alive = true, tp_cd = 21.7, items = { 'oblivion_staff', 'magic_wand', 'power_treads', 'quelling_blade', 'bracer', '', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 3, cd = 0 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -4960.0, y = 5488.8, hp = 1022, max_hp = 1022, mp = 567, max_mp = 567, level = 8, alive = true, tp_cd = 0, items = { 'power_treads', 'magic_wand', 'mask_of_madness', 'wraith_band', '', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 4, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 3, cd = 0 }, { name = 'luna_eclipse', level = 1, cd = 29.1 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = -378.6, y = -78.1, hp = 1132, max_hp = 1132, mp = 352, max_mp = 555, level = 10, alive = true, tp_cd = 0, items = { 'mask_of_death', 'magic_wand', 'power_treads', 'faerie_fire', 'blade_of_alacrity', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 0 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0 }, { name = 'nevermore_shadowraze3', level = 4, cd = 4.6 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 4, cd = 0 }, { name = 'nevermore_requiem', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 2, x = -1414.2, y = -1085.5, hp = 747, max_hp = 1373, mp = 1282, max_mp = 1441, level = 11, alive = true, tp_cd = 0, items = { 'witch_blade', 'null_talisman', 'power_treads', 'faerie_fire', 'null_talisman', 'magic_wand', '', '', '' },
      abilities = { { name = 'obsidian_destroyer_arcane_orb', level = 1, cd = 0 }, { name = 'obsidian_destroyer_astral_imprisonment', level = 4, cd = 0 }, { name = 'obsidian_destroyer_objurgation', level = 0, cd = 0 }, { name = 'obsidian_destroyer_sanity_eclipse', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 3, x = -5603.7, y = 3594.8, hp = 1176, max_hp = 1593, mp = 84, max_mp = 538, level = 10, alive = true, tp_cd = 0, items = { 'null_talisman', 'observer_ward', 'tranquil_boots', 'shadow_amulet', 'hand_of_midas', 'magic_wand', '', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 3, cd = 0 }, { name = 'ogre_magi_ignite', level = 3, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 2, cd = 0 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_oracle', team = 2, x = 872.8, y = -6646.9, hp = 1132, max_hp = 1132, mp = 757, max_mp = 757, level = 7, alive = true, tp_cd = 0, items = { 'null_talisman', 'ancient_janggo', 'observer_ward', 'magic_wand', 'tranquil_boots', 'tango', '', 'clarity', 'blood_grenade' },
      abilities = { { name = 'oracle_fortunes_end', level = 1, cd = 0 }, { name = 'oracle_fates_edict', level = 1, cd = 0 }, { name = 'oracle_purifying_flames', level = 4, cd = 0 }, { name = 'oracle_false_promise', level = 1, cd = 0 }, { name = 'oracle_prognosticate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 2, x = 1698.8, y = -6331.7, hp = 934, max_hp = 1756, mp = 325, max_mp = 435, level = 8, alive = true, tp_cd = 0, items = { 'power_treads', 'clarity', 'quelling_blade', 'magic_wand', 'bracer', 'ogre_axe', '', '', '' },
      abilities = { { name = 'slardar_sprint', level = 2, cd = 24.1 }, { name = 'slardar_slithereen_crush', level = 1, cd = 3.2 }, { name = 'slardar_bash', level = 4, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 1, cd = 0.4 } } },
    { name = 'npc_dota_hero_venomancer', team = 2, x = -5223.2, y = 1196.7, hp = 598, max_hp = 1130, mp = 773, max_mp = 819, level = 8, alive = true, tp_cd = 0, items = { 'pavise', 'urn_of_shadows', 'sentry_ward', 'magic_wand', 'arcane_boots', 'tango', '', '', '' },
      abilities = { { name = 'venomancer_venomous_gale', level = 1, cd = 0 }, { name = 'venomancer_snakebite', level = 4, cd = 0 }, { name = 'venomancer_plague_ward', level = 2, cd = 0 }, { name = 'venomancer_noxious_plague', level = 1, cd = 36.7 } } },
    { name = 'npc_dota_hero_zuus', team = 3, x = 1859.1, y = -6296.4, hp = 443, max_hp = 1045, mp = 608, max_mp = 848, level = 9, alive = true, tp_cd = 0, items = { 'sentry_ward', 'urn_of_shadows', 'magic_wand', 'headdress', 'arcane_boots', 'chain_mail', '', 'blood_grenade', 'tango' },
      abilities = { { name = 'zuus_arc_lightning', level = 3, cd = 1.2 }, { name = 'zuus_lightning_bolt', level = 4, cd = 5.2 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_oracle'] = 321,
      ['npc_dota_hero_slardar'] = 241,
    },
    died_after = 1.8,
  },
}
