-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260721_231411 @ t=192.0 (3:12), subject chaos_knight.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 8s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260721_231411', time = 192.0, window = 8.0,
  self = 'npc_dota_hero_chaos_knight',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = 4711.8, y = -4539.6, hp = 126, max_hp = 1068, mp = 45, max_mp = 387, level = 4, alive = true, tp_cd = 0, items = { '', '', 'quelling_blade', 'magic_wand', 'bracer', 'boots_of_speed', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 7 }, { name = 'chaos_knight_chaos_strike', level = 2, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 3, x = 5381.0, y = -4010.4, hp = 508, max_hp = 670, mp = 463, max_mp = 543, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'sobi_mask', 'magic_stick', 'ironwood_branch', 'clarity', 'boots_of_speed', 'ironwood_branch', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 0, cd = 0 }, { name = 'lina_light_strike_array', level = 1, cd = 5.7 }, { name = 'lina_fiery_soul', level = 2, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 3, x = 2.8, y = -78.2, hp = 575, max_hp = 957, mp = 817, max_mp = 817, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'null_talisman', 'ironwood_branch', 'faerie_fire', 'null_talisman', 'ironwood_branch', '', '', '' },
      abilities = { { name = 'obsidian_destroyer_arcane_orb', level = 1, cd = 0 }, { name = 'obsidian_destroyer_astral_imprisonment', level = 3, cd = 0 }, { name = 'obsidian_destroyer_objurgation', level = 0, cd = 0 }, { name = 'obsidian_destroyer_sanity_eclipse', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 2, x = -6908.3, y = -6133.6, hp = 648, max_hp = 802, mp = 303, max_mp = 303, level = 3, alive = true, tp_cd = 0, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 2, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 0, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skywrath_mage', team = 2, x = 6131.8, y = -4390.8, hp = 698, max_hp = 758, mp = 55, max_mp = 507, level = 3, alive = true, tp_cd = 0, items = { 'wind_lace', 'tango', '', 'boots_of_speed', 'faerie_fire', 'magic_wand', '', '', '' },
      abilities = { { name = 'skywrath_mage_arcane_bolt', level = 2, cd = 0 }, { name = 'skywrath_mage_concussive_shot', level = 1, cd = 6.4 }, { name = 'skywrath_mage_ancient_seal', level = 0, cd = 0 }, { name = 'skywrath_mage_mystic_flare', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -5437.5, y = 5502.7, hp = 127, max_hp = 756, mp = 290, max_mp = 387, level = 4, alive = true, tp_cd = 0, items = { 'ironwood_branch', 'boots_of_elven', 'magic_stick', 'boots_of_speed', 'wraith_band', 'ironwood_branch', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 0, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 6 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_tidehunter', team = 3, x = 5019.1, y = -4729.9, hp = 538, max_hp = 959, mp = 121, max_mp = 387, level = 3, alive = true, tp_cd = 0, items = { '', 'magic_wand', 'boots_of_speed', 'quelling_blade', 'gauntlets', 'ring_of_protection', '', '', '' },
      abilities = { { name = 'tidehunter_gush', level = 1, cd = 3.1 }, { name = 'tidehunter_kraken_shell', level = 1, cd = 0 }, { name = 'tidehunter_anchor_smash', level = 1, cd = 0 }, { name = 'tidehunter_ravage', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 3, x = -5953.6, y = 3994.1, hp = 663, max_hp = 786, mp = 189, max_mp = 375, level = 3, alive = true, tp_cd = 0, items = { 'blood_grenade', 'tango', 'clarity', 'boots_of_speed', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 2, cd = 1.2 }, { name = 'vengeful_spirit_wave_of_terror', level = 1, cd = 2.5 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 2, x = -6054.5, y = 3701.2, hp = 399, max_hp = 808, mp = 88, max_mp = 483, level = 4, alive = true, tp_cd = 37.6, items = { 'tango', 'blood_grenade', 'ring_of_basilius', 'boots_of_speed', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 2, cd = 14.4 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 2, cd = 9.4 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -791.9, y = -550.7, hp = 824, max_hp = 824, mp = 56, max_mp = 543, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'faerie_fire', 'empty_bottle', 'ring_of_basilius', '', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 3, cd = 0 }, { name = 'zuus_lightning_bolt', level = 1, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_lina'] = 80,
    },
    died_after = nil,
  },
}
