-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260721_230545 @ t=244.0 (4:04), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 8s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260721_230545', time = 244.0, window = 8.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = -6077.8, y = 4317.7, hp = 1273, max_hp = 1359, mp = 174, max_mp = 399, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', 'clarity', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 3, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 3, x = -3138.2, y = 5844.8, hp = 890, max_hp = 890, mp = 584, max_mp = 584, level = 4, alive = true, tp_cd = 27.3, items = { 'null_talisman', 'clarity', 'tango', 'magic_stick', 'ironwood_branch', 'observer_ward', 'ironwood_branch', 'famango', 'blood_grenade' },
      abilities = { { name = 'jakiro_dual_breath', level = 2, cd = 0 }, { name = 'jakiro_ice_path', level = 1, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = 6245.2, y = -3259.3, hp = 557, max_hp = 780, mp = 127, max_mp = 591, level = 5, alive = true, tp_cd = 0, items = { 'urn_of_shadows', 'tango', 'faerie_fire', 'tranquil_boots', 'observer_ward', '', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 3, cd = 0 }, { name = 'lich_frost_shield', level = 1, cd = 0 }, { name = 'lich_sinister_gaze', level = 1, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 3, x = 7183.3, y = 6549.6, hp = 252, max_hp = 977, mp = 884, max_mp = 972, level = 7, alive = true, tp_cd = 33.5, items = { 'faerie_fire', 'magic_wand', 'arcane_boots', 'tango', 'null_talisman', 'empty_bottle', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 4, cd = 0.4 }, { name = 'lina_light_strike_array', level = 1, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -5330.2, y = 4949.0, hp = 780, max_hp = 780, mp = 447, max_mp = 447, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'wraith_band', 'clarity', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 2, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 1, cd = 0 }, { name = 'luna_eclipse', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 2, x = -530.3, y = -473.1, hp = 346, max_hp = 1021, mp = 207, max_mp = 459, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'faerie_fire', 'belt_of_strength', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 3, cd = 0 }, { name = 'nevermore_shadowraze2', level = 3, cd = 5.3 }, { name = 'nevermore_shadowraze3', level = 3, cd = 1.8 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 3, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 3, x = 6532.3, y = -2450.8, hp = 926, max_hp = 978, mp = 223, max_mp = 354, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'magic_stick', 'clarity', 'ironwood_branch', 'boots_of_speed', 'ironwood_branch', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 0 }, { name = 'ogre_magi_ignite', level = 2, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 19.4 }, { name = 'ogre_magi_multicast', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6455.7, y = -3032.7, hp = 868, max_hp = 868, mp = 234, max_mp = 327, level = 4, alive = true, tp_cd = 18.6, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 13.2 }, { name = 'skeleton_king_bone_guard', level = 2, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 0.5 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = -6465.1, y = 4138.6, hp = 541, max_hp = 823, mp = 435, max_mp = 435, level = 5, alive = true, tp_cd = 0, items = { 'power_treads', 'flask', 'magic_wand', '', 'wraith_band', '', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 1, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 2, x = 5930.7, y = -3784.9, hp = 927, max_hp = 1154, mp = 175, max_mp = 375, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'boots_of_speed', 'belt_of_strength', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 0 }, { name = 'sven_great_cleave', level = 3, cd = 0 }, { name = 'sven_warcry', level = 1, cd = 0 }, { name = 'sven_gods_strength', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_sven'] = 223,
      ['npc_dota_hero_lich'] = 42,
    },
    died_after = 37.0,
  },
}
