-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_233217_slot1 @ t=58.1 (0:58), subject lina.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 8s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_233217_slot1', time = 58.1, window = 8.0,
  self = 'npc_dota_hero_lina',
  units = {
    { name = 'npc_dota_hero_juggernaut', team = 3, x = -4953.3, y = 5433.8, hp = 648, max_hp = 648, mp = 291, max_mp = 291, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'wraith_band', '', 'quelling_blade', '', '', '' },
      abilities = { { name = 'juggernaut_blade_fury', level = 1, cd = 0 }, { name = 'juggernaut_healing_ward', level = 0, cd = 0 }, { name = 'juggernaut_blade_dance', level = 0, cd = 0 }, { name = 'juggernaut_bladeform', level = 1, cd = 0 }, { name = 'juggernaut_omnislash', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = 5813.3, y = -4982.1, hp = 593, max_hp = 654, mp = 213, max_mp = 447, level = 2, alive = true, tp_cd = 0, items = { 'clarity', 'tango', 'faerie_fire', '', 'blood_grenade', '', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 1, cd = 3.1 }, { name = 'lich_frost_shield', level = 1, cd = 28.9 }, { name = 'lich_sinister_gaze', level = 0, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 3, x = -267.9, y = -124.5, hp = 692, max_hp = 692, mp = 510, max_mp = 584, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'faerie_fire', 'null_talisman', '', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 1, cd = 1 }, { name = 'lina_light_strike_array', level = 0, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_necrolyte', team = 2, x = -6085.9, y = 5006.6, hp = 648, max_hp = 648, mp = 459, max_mp = 459, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'ironwood_branch', 'circlet', 'mantle', 'magic_stick', '', '', '' },
      abilities = { { name = 'necrolyte_death_pulse', level = 1, cd = 0 }, { name = 'necrolyte_ghost_shroud', level = 0, cd = 0 }, { name = 'necrolyte_heartstopper_aura', level = 1, cd = 0 }, { name = 'necrolyte_reapers_scythe', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 2, x = -1150.7, y = -1047.3, hp = 695, max_hp = 736, mp = 633, max_mp = 633, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'mantle', 'ironwood_branch', 'faerie_fire', 'null_talisman', 'circlet', 'ironwood_branch', '', '' },
      abilities = { { name = 'obsidian_destroyer_arcane_orb', level = 1, cd = 0 }, { name = 'obsidian_destroyer_astral_imprisonment', level = 1, cd = 0 }, { name = 'obsidian_destroyer_objurgation', level = 0, cd = 0 }, { name = 'obsidian_destroyer_sanity_eclipse', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 2, x = 5946.4, y = -4301.0, hp = 751, max_hp = 780, mp = 221, max_mp = 315, level = 2, alive = true, tp_cd = 0, items = { 'tango', '', '', 'gauntlets', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 13.1 }, { name = 'skeleton_king_bone_guard', level = 1, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 0, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = 6073.1, y = -4450.3, hp = 412, max_hp = 582, mp = 279, max_mp = 279, level = 1, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'magic_stick', 'clarity', 'slippers', 'circlet', 'ironwood_branch', 'ironwood_branch', '' },
      abilities = { { name = 'sniper_shrapnel', level = 0, cd = 0 }, { name = 'sniper_headshot', level = 1, cd = 0 }, { name = 'sniper_take_aim', level = 0, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 3, x = 5622.3, y = -4441.4, hp = 508, max_hp = 714, mp = 204, max_mp = 303, level = 1, alive = true, tp_cd = 0, items = { 'tango', '', '', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 9.7 }, { name = 'sven_great_cleave', level = 0, cd = 0 }, { name = 'sven_warcry', level = 0, cd = 0 }, { name = 'sven_gods_strength', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_venomancer', team = 3, x = -4945.2, y = 5593.4, hp = 632, max_hp = 632, mp = 327, max_mp = 327, level = 1, alive = true, tp_cd = 0, items = { 'clarity', 'tango', 'ironwood_branch', 'ironwood_branch', 'blood_grenade', '', '', '', '' },
      abilities = { { name = 'venomancer_venomous_gale', level = 1, cd = 0 }, { name = 'venomancer_snakebite', level = 0, cd = 0 }, { name = 'venomancer_plague_ward', level = 0, cd = 0 }, { name = 'venomancer_noxious_plague', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_warlock', team = 2, x = -6228.2, y = 4769.1, hp = 764, max_hp = 764, mp = 447, max_mp = 447, level = 2, alive = true, tp_cd = 0, items = { 'tango', 'clarity', '', 'blood_grenade', 'magic_wand', '', '', '', '' },
      abilities = { { name = 'warlock_fatal_bonds', level = 1, cd = 0 }, { name = 'warlock_shadow_word', level = 0, cd = 0 }, { name = 'warlock_upheaval', level = 1, cd = 0 }, { name = 'warlock_eldritch_summoning', level = 1, cd = 0 }, { name = 'warlock_rain_of_chaos', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
    },
    died_after = 528.9,
  },
}
