-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_230124_slot1 @ t=630.0 (10:30), subject viper.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_230124_slot1', time = 630.0, window = 5.0,
  self = 'npc_dota_hero_viper',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = -5654.0, y = 3678.3, hp = 1622, max_hp = 1622, mp = 370, max_mp = 459, level = 9, alive = true, tp_cd = 0, items = { '', '', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 3, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 4, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = 824.4, y = 5240.4, hp = 2084, max_hp = 2084, mp = 591, max_mp = 591, level = 13, alive = true, tp_cd = 8.3, items = { 'maelstrom', 'empty_bottle', 'magic_wand', 'dragon_lance', 'bracer', 'power_treads', 'quelling_blade', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_tail', level = 2, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 2, cd = 0 }, { name = 'special_bonus_attack_damage15', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_ember_spirit', team = 2, x = -298.2, y = -201.8, hp = 1066, max_hp = 1088, mp = 555, max_mp = 555, level = 9, alive = true, tp_cd = 10.1, items = { 'tango', 'magic_wand', 'phase_boots', '', 'quelling_blade', 'empty_bottle', '', '', '' },
      abilities = { { name = 'ember_spirit_searing_chains', level = 2, cd = 0 }, { name = 'ember_spirit_sleight_of_fist', level = 4, cd = 0 }, { name = 'ember_spirit_flame_guard', level = 2, cd = 0 }, { name = 'ember_spirit_activate_fire_remnant', level = 1, cd = 0 }, { name = 'ember_spirit_immolation', level = 1, cd = 0 }, { name = 'ember_spirit_fire_remnant', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 3, x = -2269.3, y = 2401.5, hp = 570, max_hp = 1154, mp = 908, max_mp = 908, level = 11, alive = true, tp_cd = 0, items = { 'arcane_boots', 'urn_of_shadows', 'sentry_ward', 'magic_wand', 'headdress', 'chain_mail', '', 'blood_grenade', '' },
      abilities = { { name = 'lion_impale', level = 4, cd = 0 }, { name = 'lion_voodoo', level = 1, cd = 0 }, { name = 'lion_mana_drain', level = 4, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 1, cd = 1.2 } } },
    { name = 'npc_dota_hero_luna', team = 2, x = -5001.1, y = -4501.7, hp = 1066, max_hp = 1066, mp = 591, max_mp = 591, level = 9, alive = true, tp_cd = 0, items = { 'broadsword', 'magic_wand', 'power_treads', 'wraith_band', '', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 4, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 4, cd = 0 }, { name = 'luna_eclipse', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skywrath_mage', team = 2, x = 830.3, y = -4656.5, hp = 978, max_hp = 978, mp = 663, max_mp = 747, level = 8, alive = true, tp_cd = 8.5, items = { 'tranquil_boots', 'tango', 'observer_ward', 'shadow_amulet', 'faerie_fire', 'magic_wand', '', 'smoke_of_deceit', '' },
      abilities = { { name = 'skywrath_mage_arcane_bolt', level = 4, cd = 0 }, { name = 'skywrath_mage_concussive_shot', level = 2, cd = 13.8 }, { name = 'skywrath_mage_ancient_seal', level = 1, cd = 0 }, { name = 'skywrath_mage_mystic_flare', level = 1, cd = 1.5 } } },
    { name = 'npc_dota_hero_slardar', team = 3, x = 1623.4, y = -3886.9, hp = 2430, max_hp = 2566, mp = 537, max_mp = 682, level = 12, alive = true, tp_cd = 0, items = { 'echo_sabre', 'point_booster', 'ogre_axe', 'magic_wand', 'bracer', 'power_treads', 'quelling_blade', '', '' },
      abilities = { { name = 'slardar_sprint', level = 4, cd = 0 }, { name = 'slardar_slithereen_crush', level = 1, cd = 3.2 }, { name = 'slardar_bash', level = 4, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 2, cd = 1 } } },
    { name = 'npc_dota_hero_viper', team = 3, x = -3144.0, y = 2372.3, hp = 781, max_hp = 1375, mp = 510, max_mp = 555, level = 9, alive = true, tp_cd = 0, items = { 'mage_slayer', 'magic_wand', 'wraith_band', 'dragon_lance', 'wraith_band', 'power_treads', 'tango', 'enchanted_mango', '' },
      abilities = { { name = 'viper_poison_attack', level = 4, cd = 0 }, { name = 'viper_nethertoxin', level = 1, cd = 11.4 }, { name = 'viper_corrosive_skin', level = 3, cd = 0 }, { name = 'viper_predator', level = 1, cd = 0 }, { name = 'viper_viper_strike', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_warlock', team = 2, x = -6234.2, y = 3994.9, hp = 1088, max_hp = 1088, mp = 824, max_mp = 824, level = 9, alive = true, tp_cd = 0, items = { 'chain_mail', 'sentry_ward', 'headdress', 'glimmer_cape', 'magic_wand', 'arcane_boots', '', 'blood_grenade', 'tango' },
      abilities = { { name = 'warlock_fatal_bonds', level = 3, cd = 0 }, { name = 'warlock_shadow_word', level = 4, cd = 0 }, { name = 'warlock_upheaval', level = 1, cd = 0 }, { name = 'warlock_eldritch_summoning', level = 1, cd = 0 }, { name = 'warlock_rain_of_chaos', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 3, x = -3199.5, y = 2371.0, hp = 1088, max_hp = 1088, mp = 695, max_mp = 695, level = 7, alive = true, tp_cd = 0, items = { 'null_talisman', 'tranquil_boots', 'belt_of_strength', 'magic_wand', 'headdress', 'observer_ward', 'clarity', 'blood_grenade', 'tango' },
      abilities = { { name = 'zuus_arc_lightning', level = 1, cd = 0 }, { name = 'zuus_lightning_bolt', level = 4, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 1, cd = 22.6 } } },
  },
  observed = {
    burst = {
    },
    died_after = 15.2,
  },
}
