-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260721_230545 @ t=306.0 (5:06), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 8s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260721_230545', time = 306.0, window = 8.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 2, x = -6390.5, y = 4535.3, hp = 1424, max_hp = 1424, mp = 343, max_mp = 423, level = 6, alive = true, tp_cd = 0, items = { '', 'flask', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 3, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_jakiro', team = 3, x = -5436.9, y = 5426.6, hp = 724, max_hp = 891, mp = 538, max_mp = 584, level = 4, alive = true, tp_cd = 0, items = { 'null_talisman', 'clarity', 'tango', 'magic_stick', 'ironwood_branch', 'observer_ward', 'ironwood_branch', 'famango', 'blood_grenade' },
      abilities = { { name = 'jakiro_dual_breath', level = 2, cd = 0 }, { name = 'jakiro_ice_path', level = 1, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = 5467.1, y = -5858.4, hp = 824, max_hp = 824, mp = 475, max_mp = 639, level = 6, alive = true, tp_cd = 36.3, items = { 'urn_of_shadows', 'tango', 'clarity', 'tranquil_boots', 'observer_ward', '', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 3, cd = 0 }, { name = 'lich_frost_shield', level = 1, cd = 0.7 }, { name = 'lich_sinister_gaze', level = 1, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 1, cd = 99.7 } } },
    { name = 'npc_dota_hero_lina', team = 3, x = -705.9, y = -649.8, hp = 862, max_hp = 1023, mp = 1022, max_mp = 1022, level = 8, alive = true, tp_cd = 0, items = { 'faerie_fire', 'magic_wand', 'arcane_boots', 'tango', 'null_talisman', 'empty_bottle', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 4, cd = 0 }, { name = 'lina_light_strike_array', level = 2, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -4974.0, y = 5738.3, hp = 912, max_hp = 912, mp = 447, max_mp = 447, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'wraith_band', 'belt_of_strength', 'quelling_blade', 'clarity', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 2, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 1, cd = 0 }, { name = 'luna_eclipse', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 2, x = -2149.3, y = -1779.6, hp = 594, max_hp = 957, mp = 403, max_mp = 483, level = 7, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'power_treads', 'faerie_fire', '', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 0 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0 }, { name = 'nevermore_shadowraze3', level = 4, cd = 0 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 3, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 3, x = 5958.7, y = -5592.5, hp = 1166, max_hp = 1248, mp = 314, max_mp = 539, level = 6, alive = true, tp_cd = 21.8, items = { 'tango', 'flask', 'magic_wand', 'blood_grenade', 'clarity', 'arcane_boots', '', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 0 }, { name = 'ogre_magi_ignite', level = 3, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 0 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = 6245.0, y = -5488.6, hp = 868, max_hp = 868, mp = 327, max_mp = 327, level = 4, alive = true, tp_cd = 29, items = { '', 'quelling_blade', 'gauntlets', 'magic_stick', 'ironwood_branch', 'recipe_magic_wand', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 2, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 0 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 2, x = -5956.1, y = 4499.3, hp = 744, max_hp = 868, mp = 306, max_mp = 471, level = 6, alive = true, tp_cd = 0, items = { 'power_treads', 'flask', 'magic_wand', 'infused_raindrop', 'wraith_band', 'blade_of_alacrity', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 1, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 2, x = 5801.7, y = -5979.7, hp = 915, max_hp = 1220, mp = 142, max_mp = 387, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'boots_of_speed', 'belt_of_strength', 'faerie_fire', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 4 }, { name = 'sven_great_cleave', level = 3, cd = 0 }, { name = 'sven_warcry', level = 1, cd = 11.8 }, { name = 'sven_gods_strength', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_sven'] = 603,
      ['npc_dota_hero_lich'] = 396,
    },
    died_after = 9.9,
  },
}
