-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260722_230510_slot1 @ t=230.0 (3:50), subject death_prophet.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260722_230510_slot1', time = 230.0, window = 5.0,
  self = 'npc_dota_hero_death_prophet',
  units = {
    { name = 'npc_dota_hero_death_prophet', team = 2, x = -6312.8, y = 3082.4, hp = 607, max_hp = 918, mp = 243, max_mp = 495, level = 3, alive = true, tp_cd = 0, items = { '', '', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 1, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 2, cd = 0 }, { name = 'death_prophet_exorcism', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = 6100.8, y = -4708.8, hp = 1226, max_hp = 1226, mp = 110, max_mp = 411, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'power_treads', 'quelling_blade', 'bracer', '', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 1, cd = 2.2 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 2, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 3, x = -6295.4, y = 4112.0, hp = 573, max_hp = 824, mp = 49, max_mp = 471, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'wraith_band', '', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 2, cd = 0 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 2, cd = 0 }, { name = 'luna_eclipse', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = -94.5, y = -72.4, hp = 890, max_hp = 890, mp = 459, max_mp = 459, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'power_treads', 'faerie_fire', 'enchanted_mango', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 3, cd = 0 }, { name = 'nevermore_shadowraze2', level = 3, cd = 0 }, { name = 'nevermore_shadowraze3', level = 3, cd = 0 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 3, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_obsidian_destroyer', team = 2, x = -1176.7, y = -961.2, hp = 956, max_hp = 956, mp = 817, max_mp = 817, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'null_talisman', 'ironwood_branch', 'faerie_fire', 'null_talisman', 'ironwood_branch', '', '', '' },
      abilities = { { name = 'obsidian_destroyer_arcane_orb', level = 1, cd = 0 }, { name = 'obsidian_destroyer_astral_imprisonment', level = 3, cd = 0 }, { name = 'obsidian_destroyer_objurgation', level = 0, cd = 0 }, { name = 'obsidian_destroyer_sanity_eclipse', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 3, x = 3155.6, y = 5650.8, hp = 1022, max_hp = 1022, mp = 377, max_mp = 377, level = 4, alive = true, tp_cd = 0, items = { 'wind_lace', 'tango', 'magic_stick', 'ironwood_branch', 'null_talisman', 'boots_of_speed', 'blood_grenade', 'ironwood_branch', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 0 }, { name = 'ogre_magi_ignite', level = 2, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 0 }, { name = 'ogre_magi_multicast', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_oracle', team = 2, x = 5948.3, y = -5306.2, hp = 714, max_hp = 736, mp = 572, max_mp = 572, level = 3, alive = true, tp_cd = 0, items = { 'null_talisman', 'clarity', 'tango', 'magic_stick', 'ironwood_branch', 'ironwood_branch', '', '', 'blood_grenade' },
      abilities = { { name = 'oracle_fortunes_end', level = 1, cd = 0 }, { name = 'oracle_fates_edict', level = 0, cd = 0 }, { name = 'oracle_purifying_flames', level = 2, cd = 0 }, { name = 'oracle_false_promise', level = 0, cd = 0 }, { name = 'oracle_prognosticate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 2, x = 5140.4, y = -5016.9, hp = 1028, max_hp = 1028, mp = 361, max_mp = 363, level = 4, alive = true, tp_cd = 0, items = { 'tango', '', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'slardar_sprint', level = 1, cd = 14.2 }, { name = 'slardar_slithereen_crush', level = 1, cd = 0 }, { name = 'slardar_bash', level = 2, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_venomancer', team = 2, x = -6258.3, y = 3101.7, hp = 453, max_hp = 741, mp = 247, max_mp = 375, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'blood_grenade', 'sobi_mask', 'magic_wand', 'boots_of_speed', 'clarity', '', '', '' },
      abilities = { { name = 'venomancer_venomous_gale', level = 1, cd = 0 }, { name = 'venomancer_snakebite', level = 2, cd = 0 }, { name = 'venomancer_plague_ward', level = 0, cd = 0 }, { name = 'venomancer_noxious_plague', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 3, x = 6240.6, y = -4675.4, hp = 758, max_hp = 758, mp = 61, max_mp = 483, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'magic_stick', 'ironwood_branch', 'sobi_mask', 'boots_of_speed', 'blood_grenade', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 1, cd = 0 }, { name = 'zuus_lightning_bolt', level = 2, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_luna'] = 35,
    },
    died_after = 79.0,
  },
}
