-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- timeline @ t=373.4 (6:13), subject crystal_maiden.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 6s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = 'timeline', time = 373.4, window = 6.5,
  self = 'npc_dota_hero_crystal_maiden',
  units = {
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = 4697.0, y = -4517.0, hp = 1490, max_hp = 1490, mp = 160, max_mp = 435, level = 7, alive = true, tp_cd = 0, net_worth = 3806, items = { '', '', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 10 }, { name = 'chaos_knight_reality_rift', level = 1, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 4, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 63.6 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 2, x = 824.5, y = -1249.8, hp = 815, max_hp = 846, mp = 375, max_mp = 621, level = 6, alive = true, tp_cd = 1.1, net_worth = 3010, items = { 'null_talisman', 'tranquil_boots', 'observer_ward', 'flask', 'headdress', 'magic_wand', 'clarity', 'tango', 'blood_grenade' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 9.5 }, { name = 'crystal_maiden_frostbite', level = 3, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 2, x = -6204.2, y = 2246.4, hp = 1116, max_hp = 1116, mp = 723, max_mp = 723, level = 6, alive = true, tp_cd = 0.6, net_worth = 3754, items = { 'ring_of_health', 'tango', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 2, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 3, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 26.3 } } },
    { name = 'npc_dota_hero_jakiro', team = 3, x = 1445.0, y = -295.1, hp = 930, max_hp = 1067, mp = 729, max_mp = 764, level = 7, alive = true, tp_cd = 0, net_worth = 2750, items = { 'ring_of_protection', 'sentry_ward', 'arcane_boots', 'magic_wand', 'flask', 'sobi_mask', '', 'tango', 'blood_grenade' },
      abilities = { { name = 'jakiro_dual_breath', level = 4, cd = 0 }, { name = 'jakiro_ice_path', level = 1, cd = 0 }, { name = 'jakiro_liquid_fire', level = 1, cd = 0 }, { name = 'jakiro_liquid_ice', level = 1, cd = 0 }, { name = 'jakiro_double_trouble', level = 1, cd = 0 }, { name = 'jakiro_macropyre', level = 1, cd = 5.4 } } },
    { name = 'npc_dota_hero_juggernaut', team = 2, x = 4285.3, y = -4513.2, hp = 346, max_hp = 889, mp = 57, max_mp = 507, level = 6, alive = true, tp_cd = 0, net_worth = 3078, items = { '', 'power_treads', '', 'wraith_band', 'magic_wand', 'quelling_blade', '', '', '' },
      abilities = { { name = 'juggernaut_blade_fury', level = 3, cd = 19 }, { name = 'juggernaut_healing_ward', level = 1, cd = 49.7 }, { name = 'juggernaut_blade_dance', level = 1, cd = 0 }, { name = 'juggernaut_bladeform', level = 1, cd = 0 }, { name = 'juggernaut_omnislash', level = 1, cd = 105.6 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = -5250.4, y = 1286.1, hp = 898, max_hp = 934, mp = 701, max_mp = 836, level = 7, alive = true, tp_cd = 37.6, net_worth = 3015, items = { 'arcane_boots', 'sobi_mask', 'circlet', 'sentry_ward', 'magic_wand', 'ring_of_protection', '', 'tango', 'flask' },
      abilities = { { name = 'lich_frost_nova', level = 4, cd = 0 }, { name = 'lich_frost_shield', level = 1, cd = 0 }, { name = 'lich_sinister_gaze', level = 1, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = 689.8, y = -1483.3, hp = 688, max_hp = 1022, mp = 1022, max_mp = 1022, level = 8, alive = true, tp_cd = 0, net_worth = 3420, items = { 'arcane_boots', 'magic_wand', 'faerie_fire', '', 'null_talisman', 'empty_bottle', '', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 4, cd = 0 }, { name = 'lina_light_strike_array', level = 2, cd = 0 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = 1031.9, y = -751.8, hp = 972, max_hp = 1066, mp = 573, max_mp = 651, level = 9, alive = true, tp_cd = 0, net_worth = 4585, items = { '', 'power_treads', 'mask_of_death', 'faerie_fire', 'magic_wand', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 0 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0 }, { name = 'nevermore_shadowraze3', level = 4, cd = 6.3 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 4, cd = 0 }, { name = 'nevermore_requiem', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_pudge', team = 3, x = 3131.4, y = 87.1, hp = 1044, max_hp = 1044, mp = 367, max_mp = 387, level = 5, alive = true, tp_cd = 15.9, net_worth = 1495, items = { 'observer_ward', 'sobi_mask', 'boots_of_speed', '', 'wind_lace', 'magic_wand', '', '', '' },
      abilities = { { name = 'pudge_meat_hook', level = 2, cd = 0 }, { name = 'pudge_rot', level = 2, cd = 0 }, { name = 'pudge_flesh_heap', level = 1, cd = 0 }, { name = 'pudge_dismember', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 3, x = -6207.4, y = 3620.3, hp = 875, max_hp = 978, mp = 280, max_mp = 363, level = 5, alive = true, tp_cd = 0, net_worth = 2242, items = { '', 'magic_wand', 'blades_of_attack', 'gauntlets', 'quelling_blade', 'boots_of_speed', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 0 }, { name = 'skeleton_king_bone_guard', level = 3, cd = 0 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 0.9 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_jakiro'] = 336,
      ['npc_dota_hero_nevermore'] = 277,
    },
    died_after = 5.9,
  },
}
