-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- spot_20260725_102532_1_main__20260725_105305_slot1.timeline @ t=373.5 (6:13), subject skeleton_king.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 15s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = 'spot_20260725_102532_1_main__20260725_105305_slot1.timeline', time = 373.5, window = 15.0,
  self = 'npc_dota_hero_skeleton_king',
  units = {
    { name = 'npc_dota_hero_bristleback', team = 3, x = 6184.9, y = -4607.6, hp = 962, max_hp = 1138, mp = 532, max_mp = 596, level = 6, alive = true, tp_cd = 0, items = { '', 'bracer', '', 'quelling_blade', 'magic_wand', 'arcane_boots', '', '', '' },
      abilities = { { name = 'bristleback_viscous_nasal_goo', level = 1, cd = 0 }, { name = 'bristleback_quill_spray', level = 3, cd = 0.9 }, { name = 'bristleback_bristleback', level = 1, cd = 0 }, { name = 'bristleback_warpath', level = 1, cd = 0 }, { name = 'bristleback_prickly', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = -1344.1, y = 706.2, hp = 1578, max_hp = 1578, mp = 302, max_mp = 507, level = 9, alive = true, tp_cd = 0, items = { 'tango', 'empty_bottle', 'magic_wand', 'quelling_blade', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 3, cd = 0 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 0 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 1, cd = 24.2 } } },
    { name = 'npc_dota_hero_earthshaker', team = 2, x = -5633.8, y = 2083.8, hp = 934, max_hp = 934, mp = 479, max_mp = 524, level = 5, alive = true, tp_cd = 32.6, items = { 'wizard_hat', 'sentry_ward', 'magic_stick', 'ironwood_branch', 'ring_of_basilius', 'boots_of_speed', '', 'ironwood_branch', '' },
      abilities = { { name = 'earthshaker_fissure', level = 1, cd = 14.7 }, { name = 'earthshaker_enchant_totem', level = 1, cd = 0 }, { name = 'earthshaker_aftershock', level = 3, cd = 0 }, { name = 'earthshaker_echo_slam', level = 0, cd = 0 }, { name = 'earthshaker_slugger', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_medusa', team = 3, x = -5263.1, y = 3344.3, hp = 450, max_hp = 450, mp = 77, max_mp = 745, level = 7, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'power_treads', 'null_talisman', 'magic_wand', 'boots_of_elven', '', '', '' },
      abilities = { { name = 'medusa_split_shot', level = 2, cd = 0 }, { name = 'medusa_mystic_snake', level = 4, cd = 0 }, { name = 'medusa_gorgon_grasp', level = 1, cd = 21.1 }, { name = 'medusa_stone_gaze', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_necrolyte', team = 2, x = -6619.1, y = -6269.2, hp = 1028, max_hp = 1028, mp = 603, max_mp = 603, level = 7, alive = true, tp_cd = 17.3, items = { 'tango', 'magic_wand', 'bracer', '', 'boots_of_speed', '', '', '', '' },
      abilities = { { name = 'necrolyte_death_pulse', level = 4, cd = 0 }, { name = 'necrolyte_ghost_shroud', level = 0, cd = 0 }, { name = 'necrolyte_heartstopper_aura', level = 2, cd = 0 }, { name = 'necrolyte_reapers_scythe', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 3, x = -5349.0, y = 2265.6, hp = 353, max_hp = 1243, mp = 80, max_mp = 439, level = 6, alive = true, tp_cd = 0, items = { 'magic_wand', 'observer_ward', 'tranquil_boots', 'tango', 'null_talisman', 'gloves_of_haste', 'famango', '', 'blood_grenade' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 2.3 }, { name = 'ogre_magi_ignite', level = 3, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 5.3 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_oracle', team = 2, x = -5868.2, y = 2613.8, hp = 571, max_hp = 956, mp = 86, max_mp = 757, level = 7, alive = true, tp_cd = 2.1, items = { 'null_talisman', 'ring_of_regeneration', 'tranquil_boots', 'magic_wand', 'observer_ward', 'flask', 'blood_grenade', '', '' },
      abilities = { { name = 'oracle_fortunes_end', level = 1, cd = 5.2 }, { name = 'oracle_fates_edict', level = 1, cd = 10.8 }, { name = 'oracle_purifying_flames', level = 4, cd = 0 }, { name = 'oracle_false_promise', level = 1, cd = 75.7 }, { name = 'oracle_prognosticate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_skeleton_king', team = 2, x = 5902.4, y = -4894.8, hp = 789, max_hp = 1044, mp = 189, max_mp = 387, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', '', 'gauntlets', 'quelling_blade', 'phase_boots', '', '', '' },
      abilities = { { name = 'skeleton_king_hellfire_blast', level = 1, cd = 13.1 }, { name = 'skeleton_king_bone_guard', level = 3, cd = 40.2 }, { name = 'skeleton_king_mortal_strike', level = 1, cd = 2.9 }, { name = 'skeleton_king_innate_vampiric_spirit', level = 1, cd = 0 }, { name = 'skeleton_king_reincarnation', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_sven', team = 2, x = -6162.2, y = 1399.1, hp = 225, max_hp = 1023, mp = 310, max_mp = 375, level = 5, alive = true, tp_cd = 0, items = { '', 'boots_of_speed', '', '', 'quelling_blade', 'magic_wand', '', '', '' },
      abilities = { { name = 'sven_storm_bolt', level = 1, cd = 3.9 }, { name = 'sven_great_cleave', level = 3, cd = 0 }, { name = 'sven_warcry', level = 1, cd = 32.2 }, { name = 'sven_gods_strength', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_warlock', team = 3, x = 6150.0, y = -4118.1, hp = 984, max_hp = 984, mp = 591, max_mp = 716, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'sentry_ward', 'arcane_boots', 'blood_grenade', 'magic_wand', 'shadow_amulet', '', '', '' },
      abilities = { { name = 'warlock_fatal_bonds', level = 2, cd = 32.6 }, { name = 'warlock_shadow_word', level = 0, cd = 0 }, { name = 'warlock_upheaval', level = 3, cd = 0 }, { name = 'warlock_eldritch_summoning', level = 1, cd = 0 }, { name = 'warlock_rain_of_chaos', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_warlock'] = 639,
      ['npc_dota_hero_bristleback'] = 378,
    },
    died_after = 13.3,
  },
}
