-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- timeline_004858 @ t=423.4 (7:03), subject crystal_maiden.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = 'timeline_004858', time = 423.4, window = 5.0,
  self = 'npc_dota_hero_crystal_maiden',
  units = {
    { name = 'npc_dota_hero_centaur', team = 2, x = -6170.8, y = 1807.5, hp = 387, max_hp = 1265, mp = 387, max_mp = 387, level = 6, alive = true, tp_cd = 21.8, net_worth = 2776, items = { 'blades_of_attack', 'magic_wand', 'helm_of_iron_will', 'quelling_blade', 'ring_of_protection', '', '', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 2, cd = 0 }, { name = 'centaur_double_edge', level = 3, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 1, cd = 49.6 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = 4638.3, y = -4817.8, hp = 0, max_hp = 0, mp = 205, max_mp = 447, level = 8, alive = false, tp_cd = 0, net_worth = 3168, items = { 'power_treads', 'flask', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 2, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 4, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 40.7 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 3, x = -6142.3, y = 3133.3, hp = 427, max_hp = 890, mp = 200, max_mp = 658, level = 7, alive = true, tp_cd = 0, net_worth = 2712, items = { 'null_talisman', 'tranquil_boots', 'headdress', 'magic_wand', 'flask', 'observer_ward', 'tango', '', 'blood_grenade' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 9.1 }, { name = 'crystal_maiden_frostbite', level = 4, cd = 5 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = -5812.6, y = 2642.7, hp = 1142, max_hp = 1513, mp = 382, max_mp = 483, level = 8, alive = true, tp_cd = 0, net_worth = 4284, items = { 'helm_of_iron_will', 'magic_wand', 'power_treads', 'quelling_blade', 'bracer', 'gloves_of_haste', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 2, cd = 2.1 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 5.7 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 1, cd = 48.1 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = 3204.3, y = -5796.2, hp = 701, max_hp = 868, mp = 242, max_mp = 675, level = 7, alive = true, tp_cd = 5.2, net_worth = 2838, items = { 'urn_of_shadows', 'observer_ward', 'tranquil_boots', 'tango', '', '', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 4, cd = 0 }, { name = 'lich_frost_shield', level = 1, cd = 0 }, { name = 'lich_sinister_gaze', level = 1, cd = 0.8 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 1, cd = 71.1 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = -155.0, y = -406.8, hp = 0, max_hp = 0, mp = 411, max_mp = 1343, level = 12, alive = false, tp_cd = 0, net_worth = 6684, items = { 'tango', 'magic_wand', 'arcane_boots', 'oblivion_staff', 'null_talisman', 'empty_bottle', 'faerie_fire', '', '' },
      abilities = { { name = 'lina_dragon_slave', level = 4, cd = 0 }, { name = 'lina_light_strike_array', level = 4, cd = 3.7 }, { name = 'lina_fiery_soul', level = 1, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 2, cd = 60.6 } } },
    { name = 'npc_dota_hero_luna', team = 2, x = 6246.7, y = -4329.0, hp = 828, max_hp = 1066, mp = 125, max_mp = 591, level = 9, alive = true, tp_cd = 0, net_worth = 4916, items = { 'power_treads', 'magic_wand', 'mask_of_madness', 'wraith_band', '', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 4, cd = 2.2 }, { name = 'luna_lunar_orbit', level = 0, cd = 0 }, { name = 'luna_moon_glaive', level = 4, cd = 0 }, { name = 'luna_eclipse', level = 1, cd = 9.1 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = -6264.7, y = 2810.2, hp = 588, max_hp = 1330, mp = 442, max_mp = 575, level = 7, alive = true, tp_cd = 19.9, net_worth = 4214, items = { 'tango', 'urn_of_shadows', 'magic_wand', 'sentry_ward', 'arcane_boots', 'gloves_of_haste', '', 'blood_grenade', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 4 }, { name = 'ogre_magi_ignite', level = 3, cd = 7 }, { name = 'ogre_magi_bloodlust', level = 2, cd = 1.6 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_storm_spirit', team = 3, x = 320.8, y = 450.0, hp = 0, max_hp = 0, mp = 167, max_mp = 948, level = 9, alive = false, tp_cd = 24.7, net_worth = 4682, items = { '', 'falcon_blade', '', 'null_talisman', 'arcane_boots', 'magic_wand', '', '', '' },
      abilities = { { name = 'storm_spirit_static_remnant', level = 4, cd = 0 }, { name = 'storm_spirit_electric_vortex', level = 1, cd = 0 }, { name = 'storm_spirit_overload', level = 3, cd = 0 }, { name = 'storm_spirit_ball_lightning', level = 1, cd = 0 }, { name = 'storm_spirit_galvanized', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 3, x = -554.8, y = -27.0, hp = 512, max_hp = 1067, mp = 514, max_mp = 848, level = 10, alive = true, tp_cd = 0, net_worth = 4533, items = { 'urn_of_shadows', 'arcane_boots', 'sentry_ward', '', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 3, cd = 11.4 }, { name = 'witch_doctor_voodoo_restoration', level = 0, cd = 0 }, { name = 'witch_doctor_maledict', level = 4, cd = 11 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 1, cd = 94.5 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_ogre_magi'] = 179,
    },
    died_after = 44.1,
  },
}
