-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- timeline @ t=631.4 (10:31), subject dragon_knight.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 5s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = 'timeline', time = 631.4, window = 5.0,
  self = 'npc_dota_hero_dragon_knight',
  units = {
    { name = 'npc_dota_hero_centaur', team = 2, x = -4233.0, y = -3600.2, hp = 180, max_hp = 1875, mp = 433, max_mp = 555, level = 11, alive = true, tp_cd = 0, net_worth = 4601, items = { 'phase_boots', 'helm_of_iron_will', 'voodoo_mask', 'robe_of_magi', 'fluffy_hat', 'magic_wand', '', 'quelling_blade', 'ring_of_protection' },
      abilities = { { name = 'centaur_hoof_stomp', level = 4, cd = 0 }, { name = 'centaur_double_edge', level = 4, cd = 0 }, { name = 'centaur_return', level = 1, cd = 0 }, { name = 'centaur_stampede', level = 1, cd = 0 }, { name = 'centaur_horsepower', level = 1, cd = 0 }, { name = 'special_bonus_h_p_regen4', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_chaos_knight', team = 3, x = 6039.9, y = 1237.9, hp = 2026, max_hp = 2026, mp = 495, max_mp = 495, level = 11, alive = true, tp_cd = 0, net_worth = 5818, items = { 'vanguard', '', 'quelling_blade', 'magic_wand', 'bracer', 'power_treads', '', '', '' },
      abilities = { { name = 'chaos_knight_chaos_bolt', level = 1, cd = 0 }, { name = 'chaos_knight_reality_rift', level = 4, cd = 0 }, { name = 'chaos_knight_chaos_strike', level = 4, cd = 0 }, { name = 'chaos_knight_fundamental_forging', level = 1, cd = 0 }, { name = 'chaos_knight_phantasm', level = 1, cd = 4.6 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 3, x = -3004.7, y = -240.6, hp = 635, max_hp = 1463, mp = 25, max_mp = 831, level = 11, alive = true, tp_cd = 0, net_worth = 6192, items = { 'null_talisman', 'tranquil_boots', 'ancient_janggo', 'smoke_of_deceit', 'glimmer_cape', 'magic_wand', 'famango', '', '' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 4, cd = 0 }, { name = 'crystal_maiden_frostbite', level = 4, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 1, cd = 3.2 }, { name = 'special_bonus_h_p200', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_dragon_knight', team = 3, x = -4230.6, y = -499.4, hp = 1556, max_hp = 2282, mp = 456, max_mp = 555, level = 11, alive = true, tp_cd = 0, net_worth = 5978, items = { 'armlet', 'magic_wand', 'power_treads', 'quelling_blade', 'bracer', 'boots_of_elven', '', '', '' },
      abilities = { { name = 'dragon_knight_breathe_fire', level = 4, cd = 3.1 }, { name = 'dragon_knight_dragon_tail', level = 1, cd = 11.9 }, { name = 'dragon_knight_wyrms_wrath', level = 4, cd = 0 }, { name = 'dragon_knight_dragon_blood', level = 1, cd = 0 }, { name = 'dragon_knight_elder_dragon_form', level = 1, cd = 95.7 }, { name = 'special_bonus_attack_damage15', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lich', team = 2, x = -1437.9, y = -1120.9, hp = 1066, max_hp = 1066, mp = 711, max_mp = 843, level = 11, alive = true, tp_cd = 0, net_worth = 3174, items = { 'urn_of_shadows', 'tango', 'smoke_of_deceit', 'observer_ward', 'tranquil_boots', '', '', '', '' },
      abilities = { { name = 'lich_frost_nova', level = 4, cd = 2.5 }, { name = 'lich_frost_shield', level = 4, cd = 0 }, { name = 'lich_sinister_gaze', level = 1, cd = 0 }, { name = 'lich_death_charge', level = 1, cd = 0 }, { name = 'lich_chain_frost', level = 1, cd = 19.1 } } },
    { name = 'npc_dota_hero_lina', team = 2, x = -4610.8, y = 122.9, hp = 1524, max_hp = 1639, mp = 893, max_mp = 1689, level = 17, alive = true, tp_cd = 22.7, net_worth = 11683, items = { 'orchid_malevolence', 'maelstrom', 'arcane_boots', 'magic_wand', 'null_talisman', 'empty_bottle', 'clarity', '', 'tango' },
      abilities = { { name = 'lina_dragon_slave', level = 4, cd = 4.4 }, { name = 'lina_light_strike_array', level = 4, cd = 0 }, { name = 'lina_fiery_soul', level = 3, cd = 0 }, { name = 'lina_slow_burn', level = 1, cd = 0 }, { name = 'lina_laguna_blade', level = 2, cd = 0 } } },
    { name = 'npc_dota_hero_luna', team = 2, x = -4016.6, y = -754.8, hp = 664, max_hp = 1221, mp = 255, max_mp = 651, level = 12, alive = true, tp_cd = 20, net_worth = 6892, items = { 'mask_of_madness', 'magic_wand', 'power_treads', 'wraith_band', 'yasha', 'quelling_blade', '', '', '' },
      abilities = { { name = 'luna_lucent_beam', level = 4, cd = 4.6 }, { name = 'luna_lunar_orbit', level = 1, cd = 0 }, { name = 'luna_moon_glaive', level = 4, cd = 0 }, { name = 'luna_eclipse', level = 2, cd = 51.7 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = -2880.0, y = 2085.3, hp = 1682, max_hp = 1682, mp = 486, max_mp = 671, level = 11, alive = true, tp_cd = 0, net_worth = 4212, items = { 'urn_of_shadows', 'gloves_of_haste', 'magic_wand', 'tango', 'sentry_ward', 'arcane_boots', '', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 4, cd = 0 }, { name = 'ogre_magi_ignite', level = 3, cd = 8.5 }, { name = 'ogre_magi_bloodlust', level = 2, cd = 0 }, { name = 'ogre_magi_multicast', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_storm_spirit', team = 3, x = -75.5, y = -110.5, hp = 1074, max_hp = 1333, mp = 1077, max_mp = 1170, level = 11, alive = true, tp_cd = 0, net_worth = 5554, items = { 'falcon_blade', 'oblivion_staff', '', 'null_talisman', 'arcane_boots', 'magic_wand', '', '', '' },
      abilities = { { name = 'storm_spirit_static_remnant', level = 4, cd = 3 }, { name = 'storm_spirit_electric_vortex', level = 1, cd = 0 }, { name = 'storm_spirit_overload', level = 4, cd = 0 }, { name = 'storm_spirit_ball_lightning', level = 1, cd = 0 }, { name = 'storm_spirit_galvanized', level = 1, cd = 0 }, { name = 'special_bonus_m_p_regen150', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_witch_doctor', team = 3, x = 2496.4, y = -4776.3, hp = 1398, max_hp = 1398, mp = 1094, max_mp = 1094, level = 12, alive = true, tp_cd = 24.6, net_worth = 7506, items = { 'enchanted_mango', 'essence_distiller', 'arcane_boots', 'sentry_ward', 'glimmer_cape', 'magic_wand', '', '', 'blood_grenade' },
      abilities = { { name = 'witch_doctor_paralyzing_cask', level = 4, cd = 0 }, { name = 'witch_doctor_voodoo_restoration', level = 1, cd = 0 }, { name = 'witch_doctor_maledict', level = 4, cd = 0 }, { name = 'witch_doctor_gris_gris', level = 1, cd = 0 }, { name = 'witch_doctor_death_ward', level = 2, cd = 0 }, { name = 'special_bonus_h_p200', level = 1, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_lina'] = 1299,
      ['npc_dota_hero_dragon_knight'] = 189,
      ['npc_dota_hero_luna'] = 131,
    },
    died_after = 4.2,
  },
}
