-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260723_051728_slot1 @ t=231.0 (3:51), subject slardar.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 8s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260723_051728_slot1', time = 231.0, window = 8.0,
  self = 'npc_dota_hero_slardar',
  units = {
    { name = 'npc_dota_hero_centaur', team = 3, x = 6682.5, y = 5807.9, hp = 1066, max_hp = 1066, mp = 339, max_mp = 339, level = 4, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'magic_wand', 'helm_of_iron_will', 'quelling_blade', 'ring_of_protection', 'blades_of_attack', '', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 2, cd = 0 }, { name = 'centaur_double_edge', level = 2, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 0, cd = 0 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 3, x = 5971.9, y = -5158.9, hp = 666, max_hp = 670, mp = 261, max_mp = 447, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'sobi_mask', 'magic_stick', 'ironwood_branch', 'ironwood_branch', 'boots_of_speed', '', 'blood_grenade', '' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 0 }, { name = 'crystal_maiden_frostbite', level = 2, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 2, x = 4850.9, y = -5530.1, hp = 1000, max_hp = 1000, mp = 349, max_mp = 603, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'faerie_fire', 'circlet', 'empty_bottle', '', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 3, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 2, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 3, x = -6146.2, y = 3872.0, hp = 510, max_hp = 736, mp = 510, max_mp = 510, level = 4, alive = true, tp_cd = 0, items = { 'null_talisman', 'observer_ward', 'tango', 'magic_stick', 'ironwood_branch', 'boots_of_speed', 'blood_grenade', 'famango', 'ironwood_branch' },
      abilities = { { name = 'lion_impale', level = 2, cd = 0 }, { name = 'lion_voodoo', level = 1, cd = 0 }, { name = 'lion_mana_drain', level = 1, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = -29.5, y = 94.2, hp = 787, max_hp = 956, mp = 462, max_mp = 483, level = 7, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'power_treads', 'faerie_fire', '', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 0 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0 }, { name = 'nevermore_shadowraze3', level = 4, cd = 0 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 3, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = 4990.3, y = -5827.4, hp = 529, max_hp = 1021, mp = 208, max_mp = 377, level = 4, alive = true, tp_cd = 0, items = { 'clarity', 'ironwood_branch', 'magic_stick', 'observer_ward', 'null_talisman', 'ironwood_branch', '', '', 'blood_grenade' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 0 }, { name = 'ogre_magi_ignite', level = 2, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 9 }, { name = 'ogre_magi_multicast', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -6278.3, y = 3014.2, hp = 753, max_hp = 940, mp = 351, max_mp = 351, level = 3, alive = true, tp_cd = 0, items = { 'tango', '', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'slardar_sprint', level = 0, cd = 0 }, { name = 'slardar_slithereen_crush', level = 1, cd = 0 }, { name = 'slardar_bash', level = 2, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -6268.8, y = 3858.2, hp = 590, max_hp = 780, mp = 399, max_mp = 399, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'magic_wand', 'power_treads', 'wraith_band', 'infused_raindrop', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 0, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 2, x = 5093.8, y = -6044.9, hp = 515, max_hp = 780, mp = 249, max_mp = 387, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'power_treads', '', 'faerie_fire', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 2, cd = 0 }, { name = 'vengeful_spirit_wave_of_terror', level = 2, cd = 0.8 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -6308.7, y = 2776.9, hp = 692, max_hp = 692, mp = 342, max_mp = 435, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'sobi_mask', 'magic_stick', 'ironwood_branch', 'clarity', 'boots_of_speed', 'blood_grenade', 'ironwood_branch', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 1, cd = 0 }, { name = 'zuus_lightning_bolt', level = 2, cd = 0 }, { name = 'zuus_heavenly_jump', level = 0, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_sniper'] = 488,
      ['npc_dota_hero_lion'] = 195,
    },
    died_after = 5.7,
  },
}
