-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260723_051728_slot1 @ t=318.0 (5:18), subject ogre_magi.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 13s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260723_051728_slot1', time = 318.0, window = 13.0,
  self = 'npc_dota_hero_ogre_magi',
  units = {
    { name = 'npc_dota_hero_centaur', team = 3, x = 6564.6, y = -1110.0, hp = 1066, max_hp = 1066, mp = 339, max_mp = 339, level = 4, alive = true, tp_cd = 3.2, items = { 'boots_of_speed', 'magic_wand', 'helm_of_iron_will', 'quelling_blade', 'ring_of_protection', 'blades_of_attack', '', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 2, cd = 0 }, { name = 'centaur_double_edge', level = 2, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 0, cd = 0 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 3, x = 6562.9, y = -2343.5, hp = 692, max_hp = 692, mp = 452, max_mp = 608, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'ring_of_basilius', 'magic_stick', 'wizard_hat', 'ironwood_branch', 'boots_of_speed', 'ironwood_branch', 'blood_grenade', '' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 0 }, { name = 'crystal_maiden_frostbite', level = 3, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 2, x = -3752.3, y = -168.9, hp = 1000, max_hp = 1000, mp = 385, max_mp = 603, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'sobi_mask', 'circlet', 'empty_bottle', 'faerie_fire', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 3, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 2, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 3, x = -6232.8, y = 2812.8, hp = 100, max_hp = 893, mp = 176, max_mp = 621, level = 6, alive = true, tp_cd = 37.4, items = { 'null_talisman', 'observer_ward', 'tango', 'magic_wand', 'blood_grenade', 'tranquil_boots', '', 'famango', '' },
      abilities = { { name = 'lion_impale', level = 2, cd = 3.2 }, { name = 'lion_voodoo', level = 1, cd = 0 }, { name = 'lion_mana_drain', level = 2, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 1, cd = 83 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = 6617.8, y = -2610.1, hp = 1000, max_hp = 1000, mp = 369, max_mp = 507, level = 8, alive = true, tp_cd = 36.8, items = { 'tango', 'magic_wand', 'power_treads', 'faerie_fire', 'mask_of_death', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 4, cd = 0 }, { name = 'nevermore_shadowraze2', level = 4, cd = 0 }, { name = 'nevermore_shadowraze3', level = 4, cd = 0 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 4, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = 6286.1, y = -3837.1, hp = 1001, max_hp = 1132, mp = 368, max_mp = 408, level = 5, alive = true, tp_cd = 0, items = { 'ironwood_branch', 'boots_of_speed', 'magic_stick', 'observer_ward', 'null_talisman', 'ironwood_branch', '', '', 'blood_grenade' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 0 }, { name = 'ogre_magi_ignite', level = 3, cd = 0 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 0 }, { name = 'ogre_magi_multicast', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -7254.8, y = -6739.8, hp = 565, max_hp = 1027, mp = 363, max_mp = 363, level = 4, alive = true, tp_cd = 30.4, items = { 'tango', '', 'quelling_blade', 'magic_wand', 'bracer', '', '', '', '' },
      abilities = { { name = 'slardar_sprint', level = 1, cd = 21.7 }, { name = 'slardar_slithereen_crush', level = 1, cd = 0 }, { name = 'slardar_bash', level = 2, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -6408.4, y = 2905.8, hp = 513, max_hp = 1132, mp = 371, max_mp = 495, level = 7, alive = true, tp_cd = 0, items = { 'dragon_lance', 'tango_single', 'magic_wand', 'power_treads', 'wraith_band', 'infused_raindrop', '', '', '' },
      abilities = { { name = 'sniper_shrapnel', level = 2, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 2, x = 6312.4, y = -3982.0, hp = 846, max_hp = 846, mp = 379, max_mp = 411, level = 5, alive = true, tp_cd = 0, items = { 'tango', 'power_treads', '', 'faerie_fire', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 3, cd = 0 }, { name = 'vengeful_spirit_wave_of_terror', level = 2, cd = 0 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -6323.2, y = 680.2, hp = 0, max_hp = 0, mp = 282, max_mp = 471, level = 4, alive = false, tp_cd = 18.5, items = { 'tango', 'sobi_mask', 'magic_stick', 'clarity', 'ironwood_branch', 'boots_of_speed', 'ironwood_branch', 'blood_grenade', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 1, cd = 0 }, { name = 'zuus_lightning_bolt', level = 2, cd = 0 }, { name = 'zuus_heavenly_jump', level = 1, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_centaur'] = 608,
      ['npc_dota_hero_nevermore'] = 458,
    },
    died_after = 11.0,
  },
}
