-- GENERATED by tools/batch_test/replayscope/make_fixture.py -- do not hand-edit.
-- 20260723_052241_slot1 @ t=210.0 (3:30), subject sniper.
-- observed.burst = damage each enemy hero ACTUALLY dealt to the subject in the
-- following 9s; observed.died_after = seconds until the subject died (ground truth).
return {
  game = '20260723_052241_slot1', time = 210.0, window = 9.0,
  self = 'npc_dota_hero_sniper',
  units = {
    { name = 'npc_dota_hero_centaur', team = 3, x = 6348.8, y = -2918.3, hp = 675, max_hp = 978, mp = 327, max_mp = 327, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', '', 'quelling_blade', 'ring_of_protection', '', '', '', '' },
      abilities = { { name = 'centaur_hoof_stomp', level = 1, cd = 0 }, { name = 'centaur_double_edge', level = 2, cd = 0 }, { name = 'centaur_return', level = 0, cd = 0 }, { name = 'centaur_stampede', level = 0, cd = 0 }, { name = 'centaur_horsepower', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_crystal_maiden', team = 3, x = 6398.7, y = -2985.1, hp = 342, max_hp = 604, mp = 223, max_mp = 399, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'clarity', 'magic_stick', 'ironwood_branch', 'sobi_mask', 'boots_of_speed', 'blood_grenade', 'ironwood_branch', '' },
      abilities = { { name = 'crystal_maiden_crystal_nova', level = 1, cd = 0 }, { name = 'crystal_maiden_frostbite', level = 1, cd = 0 }, { name = 'crystal_maiden_brilliance_aura', level = 1, cd = 0 }, { name = 'crystal_maiden_freezing_field', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_death_prophet', team = 2, x = -641.9, y = -643.5, hp = 1000, max_hp = 1000, mp = 437, max_mp = 603, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'ring_of_basilius', 'circlet', 'empty_bottle', 'faerie_fire', '', '' },
      abilities = { { name = 'death_prophet_carrion_swarm', level = 3, cd = 0 }, { name = 'death_prophet_silence', level = 0, cd = 0 }, { name = 'death_prophet_spirit_siphon', level = 2, cd = 0 }, { name = 'death_prophet_exorcism', level = 1, cd = 0 } } },
    { name = 'npc_dota_hero_lion', team = 3, x = -6408.7, y = 3112.5, hp = 418, max_hp = 759, mp = 439, max_mp = 522, level = 4, alive = true, tp_cd = 0, items = { 'null_talisman', 'clarity', 'tango', 'magic_stick', 'ironwood_branch', 'ironwood_branch', '', '', 'blood_grenade' },
      abilities = { { name = 'lion_impale', level = 2, cd = 3.1 }, { name = 'lion_voodoo', level = 1, cd = 15.9 }, { name = 'lion_mana_drain', level = 1, cd = 0 }, { name = 'lion_innate_to_hell_and_back', level = 1, cd = 0 }, { name = 'lion_finger_of_death', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_nevermore', team = 3, x = 3913.1, y = -470.7, hp = 890, max_hp = 890, mp = 413, max_mp = 459, level = 6, alive = true, tp_cd = 0, items = { 'tango', 'magic_wand', 'boots_of_speed', 'faerie_fire', '', 'empty_bottle', '', '', '' },
      abilities = { { name = 'nevermore_shadowraze1', level = 3, cd = 0 }, { name = 'nevermore_shadowraze2', level = 3, cd = 0 }, { name = 'nevermore_shadowraze3', level = 3, cd = 0 }, { name = 'nevermore_frenzy', level = 0, cd = 0 }, { name = 'nevermore_presence', level = 3, cd = 0 }, { name = 'nevermore_requiem', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_ogre_magi', team = 2, x = -5364.9, y = 1362.2, hp = 1044, max_hp = 1044, mp = 136, max_mp = 383, level = 4, alive = true, tp_cd = 0, items = { 'boots_of_speed', 'tango', 'magic_stick', 'ironwood_branch', 'null_talisman', 'ironwood_branch', 'blood_grenade', '', '' },
      abilities = { { name = 'ogre_magi_fireblast', level = 1, cd = 0 }, { name = 'ogre_magi_ignite', level = 2, cd = 2.3 }, { name = 'ogre_magi_bloodlust', level = 1, cd = 5.9 }, { name = 'ogre_magi_multicast', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_slardar', team = 2, x = -6391.8, y = 3012.9, hp = 960, max_hp = 1071, mp = 247, max_mp = 351, level = 3, alive = true, tp_cd = 0, items = { 'belt_of_strength', 'flask', 'quelling_blade', 'magic_wand', 'bracer', 'boots_of_speed', 'tango', '', '' },
      abilities = { { name = 'slardar_sprint', level = 0, cd = 0 }, { name = 'slardar_slithereen_crush', level = 1, cd = 5.3 }, { name = 'slardar_bash', level = 2, cd = 0 }, { name = 'slardar_slardar_seaborn_sentinel', level = 1, cd = 0 }, { name = 'slardar_amplify_damage', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_sniper', team = 3, x = -6177.4, y = 3096.1, hp = 596, max_hp = 714, mp = 363, max_mp = 363, level = 4, alive = true, tp_cd = 0, items = { 'tango', 'flask', 'magic_stick', 'boots_of_speed', 'wraith_band', 'boots_of_elven', 'ironwood_branch', 'ironwood_branch', '' },
      abilities = { { name = 'sniper_shrapnel', level = 0, cd = 0 }, { name = 'sniper_headshot', level = 2, cd = 0 }, { name = 'sniper_take_aim', level = 2, cd = 0 }, { name = 'sniper_keen_scope', level = 1, cd = 0 }, { name = 'sniper_assassinate', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_vengeful_spirit', team = 2, x = 6116.8, y = -3638.8, hp = 711, max_hp = 912, mp = 8, max_mp = 387, level = 4, alive = true, tp_cd = 0, items = { 'belt_of_strength', 'boots_of_speed', '', 'faerie_fire', '', 'magic_wand', '', '', '' },
      abilities = { { name = 'vengeful_spirit_magic_missile', level = 2, cd = 11.9 }, { name = 'vengeful_spirit_wave_of_terror', level = 2, cd = 12.2 }, { name = 'vengeful_spirit_command_aura', level = 0, cd = 0 }, { name = 'vengeful_spirit_revenge', level = 1, cd = 0 }, { name = 'vengeful_spirit_nether_swap', level = 0, cd = 0 } } },
    { name = 'npc_dota_hero_zuus', team = 2, x = -6539.7, y = 2241.5, hp = 119, max_hp = 713, mp = 83, max_mp = 447, level = 3, alive = true, tp_cd = 0, items = { 'tango', 'ironwood_branch', 'magic_stick', 'ironwood_branch', 'boots_of_speed', 'sobi_mask', 'blood_grenade', '', '' },
      abilities = { { name = 'zuus_arc_lightning', level = 1, cd = 0 }, { name = 'zuus_lightning_bolt', level = 2, cd = 0 }, { name = 'zuus_heavenly_jump', level = 0, cd = 0 }, { name = 'zuus_thundergods_wrath', level = 0, cd = 0 } } },
  },
  observed = {
    burst = {
      ['npc_dota_hero_ogre_magi'] = 335,
      ['npc_dota_hero_slardar'] = 155,
    },
    died_after = 8.2,
  },
}
