-- GENERATED by tools/agent/ability_damage_census.py -- do not hand-edit.
--
-- Which abilities, of every hero this repo ships, declare a NONZERO top-level
-- `AbilityDamage` in the game's own hero KV.  `CAbility:GetAbilityDamage()`
-- reads that field and nothing else, so every ability absent from this table
-- answers 0 -- silently (hero charter, axis `0DMG`).
--
-- Used as a ratchet: tests/test_ability_damage_reads.lua fails when a hero
-- file's GetAbilityDamage() read stops being provably zero, or when a new one
-- appears.  Regenerate after a patch:
--
--     python3 tools/agent/ability_damage_census.py --snapshot

local X = {}

-- hero (bots/BotLib/hero_<key>.lua) -> ability name -> per-level AbilityDamage.
X.NONZERO = {
    ['ancient_apparition'] = { ['ancient_apparition_ice_blast'] = '250 325 400' },
    ['kunkka'] = { ['kunkka_ghostship'] = '350 475 600' },
    ['leshrac'] = { ['leshrac_split_earth'] = '115 170 225 280' },
    ['mirana'] = { ['mirana_arrow'] = '60 160 260 360' },
    ['morphling'] = { ['morphling_waveform'] = '75 150 225 300' },
    ['muerta'] = { ['muerta_parting_shot'] = '300' },
    ['necrolyte'] = { ['necrolyte_death_pulse'] = '100 160 220 280' },
    ['nevermore'] = { ['nevermore_requiem'] = '80 120 160' },
    ['pangolier'] = { ['pangolier_gyroshell'] = '100 200 300' },
    ['sand_king'] = { ['sandking_burrowstrike'] = '80 150 220 290' },
    ['storm_spirit'] = { ['storm_spirit_ball_lightning'] = '6 10 14' },
    ['sven'] = { ['sven_storm_bolt'] = '80 160 240 320' },
    ['tidehunter'] = { ['tidehunter_ravage'] = '275 375 475' },
    ['ursa'] = { ['ursa_earthshock'] = '75 125 175 225' },
    ['void_spirit'] = { ['void_spirit_dissimilate'] = '105 185 265 345' },
    ['witch_doctor'] = { ['witch_doctor_maledict'] = '18 22 26 30' },
}

return X
