--- GENERATED by tools/agent/ability_value_key_census.py -- do not hand-edit.
---
--- Every live `<abilityHandle>:GetSpecialValue*('value')` call site in
--- bots/, with the ability its variable is bound to and whether that
--- ability owns an AbilityValues entry NAMED `value`.
---
--- READS-ZERO  the ability has no entry named `value`; the read is a
---             silent 0.  Unlike GH #228's talent sites there is no
---             fold to make this harmless -- the read IS the number.
--- ANSWERS     the ability really owns an entry named `value`.
---
--- `sign` is what the surrounding arithmetic does with the 0, recorded
--- by hand in the census and NOT derived: UNDER = a kill/threshold
--- branch that can never fire, OVER = a cost read as free, FOLD = the
--- talent-bonus term of #228's harmless kind (repair is deletion).
---
--- This is a CONSISTENCY ratchet, not a correctness one: it goes red
--- when the shipped call sites and this table stop agreeing.
--- Correctness is owned by the source -- rerun the census.

return {
    totals = { sites = 8, abilities = 7, reads_zero = 8 },
    signs = { fold = 2, over = 1, under = 5 },
    sites = {
        { file = 'bots/BotLib/hero_enchantress.lua', line = 440, var = 'Impetus', nth = 1, ability = 'enchantress_impetus', hero = 'enchantress', verdict = 'READS-ZERO', sign = 'UNDER', intended = 'distance_damage_pct' },
        { file = 'bots/BotLib/hero_enigma.lua', line = 277, var = 'Malefice', nth = 1, ability = 'enigma_malefice', hero = 'enigma', verdict = 'READS-ZERO', sign = 'UNDER', intended = 'stun_instances' },
        { file = 'bots/BotLib/hero_enigma.lua', line = 281, var = 'Malefice', nth = 2, ability = 'enigma_malefice', hero = 'enigma', verdict = 'READS-ZERO', sign = 'FOLD', intended = '' },
        { file = 'bots/BotLib/hero_enigma.lua', line = 585, var = 'MidnightPulse', nth = 1, ability = 'enigma_midnight_pulse', hero = 'enigma', verdict = 'READS-ZERO', sign = 'FOLD', intended = '' },
        { file = 'bots/BotLib/hero_enigma.lua', line = 675, var = 'BlackHole', nth = 1, ability = 'enigma_black_hole', hero = 'enigma', verdict = 'READS-ZERO', sign = 'UNDER', intended = 'damage' },
        { file = 'bots/BotLib/hero_gyrocopter.lua', line = 139, var = 'RocketBarrage', nth = 1, ability = 'gyrocopter_rocket_barrage', hero = 'gyrocopter', verdict = 'READS-ZERO', sign = 'UNDER', intended = 'rocket_damage' },
        { file = 'bots/BotLib/hero_terrorblade.lua', line = 406, var = 'DemonZeal', nth = 1, ability = 'terrorblade_demon_zeal', hero = 'terrorblade', verdict = 'READS-ZERO', sign = 'OVER', intended = 'health_cost_pct' },
        { file = 'bots/BotLib/hero_tiny.lua', line = 232, var = 'Avalanche', nth = 1, ability = 'tiny_avalanche', hero = 'tiny', verdict = 'READS-ZERO', sign = 'UNDER', intended = 'avalanche_damage' },
    },
}
