-- GENERATED by tools/agent/fixture_talent_census.py --snapshot -- do not hand-edit.
--
-- What the frozen real-frame corpus (tests/fixtures/*.lua) can and
-- cannot show about TRAINED talents.  Generic rows appear by name;
-- hero-unique (`special_bonus_unique_*`) rows appear ZERO times, on
-- any hero, at any level -- including a level-19 frame that holds
-- three trained talents by the game's own rules.
--
-- This is a BLINDNESS registry, not a claim about what bots train.
-- See tools/agent/fixture_talent_census.py for the two accounts
-- (dumper filter / never trained) the corpus cannot separate.
--
-- Regenerate:
--   python3 tools/agent/fixture_talent_census.py --snapshot

local X = {}

X.CORPUS = {
    fixtures = 105,
    hero_frames = 960,
    frames_lv10 = 228,
    frames_lv15 = 9,
    frames_lv20 = 0,
    max_level = 19,
    sightings = 67,
    unique_sightings = 0,
    sightings_lv15 = 0,
    max_talents_on_one_frame = 1,
    zero_talent_frames_lv10 = 161,
    deficit_frames_lv10 = 79,
    split_fixtures = 27,
}

-- hero -> talent name -> number of fixture frames showing it
X.SIGHTINGS = {
    ['bristleback'] = {
        ['special_bonus_m_p_regen150'] = 6,
    },
    ['centaur'] = {
        ['special_bonus_h_p_regen4'] = 2,
    },
    ['crystal_maiden'] = {
        ['special_bonus_h_p200'] = 15,
    },
    ['death_prophet'] = {
        ['special_bonus_h_p200'] = 6,
    },
    ['dragon_knight'] = {
        ['special_bonus_attack_damage15'] = 5,
    },
    ['lina'] = {
        ['special_bonus_attack_damage25'] = 2,
    },
    ['lion'] = {
        ['special_bonus_movement_speed20'] = 1,
    },
    ['shadow_shaman'] = {
        ['special_bonus_m_p_regen175'] = 4,
    },
    ['silencer'] = {
        ['special_bonus_attack_speed25'] = 3,
    },
    ['skywrath_mage'] = {
        ['special_bonus_m_p_regen150'] = 2,
    },
    ['spirit_breaker'] = {
        ['special_bonus_night_vision500'] = 1,
    },
    ['storm_spirit'] = {
        ['special_bonus_m_p_regen150'] = 5,
    },
    ['witch_doctor'] = {
        ['special_bonus_h_p200'] = 5,
    },
    ['zuus'] = {
        ['special_bonus_h_p200'] = 10,
    },
}

-- focus five: the t10 row their shipped tTalentTreeList picks,
-- decoded by aba_skill.X.GetTalentBuild ({0,10} -> slot 1,
-- {10,0} -> slot 2), and how often the corpus shows that hero any
-- talent at all.  rows = number of role tables (1 = role-blind).
X.FOCUS_T10 = {
    ['axe'] = { slot = 2, rows = 1, name = 'special_bonus_unique_axe_8', kind = 'unique', sightings = 0, frames_lv10 = 10, deficit_lv10 = 10 },
    ['zuus'] = { slot = 2, rows = 1, name = 'special_bonus_hp_200', kind = 'generic', sightings = 10, frames_lv10 = 10, deficit_lv10 = 1 },
    ['skeleton_king'] = { slot = 2, rows = 1, name = 'special_bonus_unique_wraith_king_facet_1', kind = 'unique', sightings = 0, frames_lv10 = 5, deficit_lv10 = 5 },
    ['lion'] = { slot = 2, rows = 1, name = 'special_bonus_movement_speed_20', kind = 'generic', sightings = 1, frames_lv10 = 5, deficit_lv10 = 4 },
    ['crystal_maiden'] = { slot = 1, rows = 1, name = 'special_bonus_hp_200', kind = 'generic', sightings = 15, frames_lv10 = 15, deficit_lv10 = 0 },
}

-- Fixtures where ONE frozen instant both SHOWS a trained talent on
-- one hero and shows none on another hero who is level >= 10 and
-- cannot account for all his skill points.  A dumper cannot be
-- blind and not-blind inside the same frame, so these are where
-- the instrument story and the never-trained story come apart.
X.SPLIT = {
    { fixture = 'f_050713_es_defend_1v3.lua', shows = { 'death_prophet' }, blind = { 'axe', 'obsidian_destroyer' } },
    { fixture = 'f_181441_zuus_lowhp_limbo.lua', shows = { 'bristleback', 'centaur', 'dragon_knight', 'shadow_shaman', 'zuus' }, blind = { 'luna' } },
    { fixture = 'f_181544_storm_escape_tp.lua', shows = { 'bristleback', 'silencer', 'storm_spirit' }, blind = { 'drow_ranger', 'queen_of_pain' } },
    { fixture = 'f_182552_warlock_ult_hoard.lua', shows = { 'silencer', 'storm_spirit' }, blind = { 'drow_ranger' } },
    { fixture = 'f_212636_tide_ancient.lua', shows = { 'crystal_maiden', 'lion', 'zuus' }, blind = { 'luna', 'necrolyte', 'obsidian_destroyer', 'ogre_magi', 'tidehunter' } },
    { fixture = 'f_230124_viper_roshan_abort.lua', shows = { 'dragon_knight' }, blind = { 'lion' } },
    { fixture = 'f_260819_123012_dk_rescue_far.lua', shows = { 'storm_spirit' }, blind = { 'medusa', 'obsidian_destroyer' } },
    { fixture = 'f_260819_123012_dp_landed_dead.lua', shows = { 'storm_spirit' }, blind = { 'medusa', 'obsidian_destroyer' } },
    { fixture = 'f_260819_222559_od_eclipse_pair.lua', shows = { 'crystal_maiden', 'dragon_knight', 'lina', 'witch_doctor' }, blind = { 'juggernaut', 'medusa', 'obsidian_destroyer', 'queen_of_pain', 'viper' } },
    { fixture = 'f_260819_222559_od_eclipse_solo.lua', shows = { 'crystal_maiden', 'dragon_knight', 'lina', 'witch_doctor' }, blind = { 'medusa', 'obsidian_destroyer', 'queen_of_pain', 'viper' } },
    { fixture = 'f_260819_223607_sniper_rooted.lua', shows = { 'crystal_maiden' }, blind = { 'necrolyte', 'obsidian_destroyer', 'ogre_magi' } },
    { fixture = 'f_260820_042009_cm_cask_far.lua', shows = { 'shadow_shaman' }, blind = { 'drow_ranger' } },
    { fixture = 'f_260820_042612_axe_blink_init_573.lua', shows = { 'death_prophet', 'witch_doctor' }, blind = { 'axe' } },
    { fixture = 'f_260820_043120_viper_defend_paired.lua', shows = { 'spirit_breaker', 'zuus' }, blind = { 'axe', 'drow_ranger', 'lion', 'tidehunter', 'viper' } },
    { fixture = 'f_260820_043124_axe_blink_flee_555.lua', shows = { 'crystal_maiden', 'skywrath_mage' }, blind = { 'axe', 'obsidian_destroyer', 'skeleton_king' } },
    { fixture = 'f_260820_043140_luna_ring_bid.lua', shows = { 'death_prophet', 'silencer', 'witch_doctor' }, blind = { 'axe', 'luna' } },
    { fixture = 'f_260820_043524_wd_defend_alone.lua', shows = { 'crystal_maiden', 'shadow_shaman' }, blind = { 'drow_ranger', 'tidehunter' } },
    { fixture = 'f_260820_043637_axe_ring_alone.lua', shows = { 'crystal_maiden', 'shadow_shaman', 'skywrath_mage' }, blind = { 'axe', 'obsidian_destroyer', 'viper' } },
    { fixture = 'f_260820_102030_tide_illusion_burst.lua', shows = { 'crystal_maiden', 'zuus' }, blind = { 'lion', 'necrolyte', 'obsidian_destroyer', 'ogre_magi' } },
    { fixture = 'f_260820_103630_lina_tower_ring.lua', shows = { 'zuus' }, blind = { 'lina' } },
    { fixture = 'f_260820_103644_necro_pinned_dying.lua', shows = { 'crystal_maiden' }, blind = { 'necrolyte', 'skeleton_king' } },
    { fixture = 'f_260820_162859_es_blink_flee_615.lua', shows = { 'bristleback', 'crystal_maiden', 'zuus' }, blind = { 'skeleton_king', 'viper' } },
    { fixture = 'f_260820_163429_es_blink_init_621.lua', shows = { 'bristleback', 'crystal_maiden', 'zuus' }, blind = { 'juggernaut', 'skeleton_king', 'viper' } },
    { fixture = 'f_260820_182906_lion_drain_survived.lua', shows = { 'crystal_maiden' }, blind = { 'obsidian_destroyer' } },
    { fixture = 'f_260822_063559_slardar_tp_forward.lua', shows = { 'crystal_maiden' }, blind = { 'lion', 'necrolyte', 'obsidian_destroyer', 'ogre_magi' } },
    { fixture = 'f_260823_002103_wk_ancient_camp_634.lua', shows = { 'bristleback', 'crystal_maiden', 'zuus' }, blind = { 'skeleton_king', 'sniper', 'viper' } },
    { fixture = 'f_631400_dragon_knight_snowballtarget.lua', shows = { 'centaur', 'crystal_maiden', 'dragon_knight', 'storm_spirit', 'witch_doctor' }, blind = { 'lina', 'luna', 'ogre_magi' } },
}

return X
