-- GENERATED by tools/agent/facet_census.py --snapshot -- do not hand-edit.
--
-- Read off the game's own npc_heroes.txt (the same file
-- tools/agent/talent_slot_census.py takes slot order from).  It answers the
-- question hero_skeleton_king.lua parked in its own source: can a FACET
-- change which talent sits in a slot, so that a t20/t25 price is an argument
-- about a row the game does not always ship?
--
-- Two answers, kept apart on purpose:
--   NAMES_TALENT_ROW  -- roster-wide, how many facet blocks name a
--                        special_bonus_* row or an AbilityIndex inside the
--                        talent run (10..17).  Zero means no facet can move
--                        a talent slot for ANY hero.
--   per-hero FACETS   -- whether this hero has a facet that can be rolled
--                        at all.  A `Deprecated true` entry cannot.
--
-- NOT a substitute for the KV value census: a facet can still gate a
-- talent's VALUE via `required_facet` inside AbilityValues.  Different
-- question, different tool (special_value_key_census.py).
--
-- Regenerate after a patch:
--   python3 tools/agent/facet_census.py --snapshot

local X = {}

-- Roster-wide counters, over every hero in npc_heroes.txt.
X.ROSTER = {
    facet_entries      = 339,
    deprecated         = 307,
    live               = 32,
    names_talent_row   = 0,
}

-- Heroes with at least one LIVE (rollable) facet.  Recorded because the
-- convenient shortcut 'facets are dead everywhere now' is FALSE, and three
-- of these are in this project's candidate hero pool.
X.LIVE_FACET_HEROES = {
    ['chaos_knight'] = { 'chaos_knight_strong_illusions' },
    ['huskar'] = { 'huskar_bloodbath', 'huskar_nothl_transfusion', 'huskar_cauterize', 'huskar_nothl_conflagration' },
    ['lich'] = { 'lich_frostbound', 'lich_growing_cold', 'lich_cryophobia' },
    ['lone_druid'] = { 'lone_druid_bear_with_me', 'lone_druid_unbearable', 'lone_druid_bear_necessities' },
    ['meepo'] = { 'meepo_pack_rat' },
    ['phantom_assassin'] = { 'phantom_assassin_veiled_one', 'phantom_assassin_methodical', 'phantom_assassin_sweet_release' },
    ['silencer'] = { 'silencer_irrepressible', 'silencer_reverberating_silence', 'silencer_spread_the_knowledge', 'silencer_oppressive_silence' },
    ['storm_spirit'] = { 'storm_spirit_shock_collar', 'storm_spirit_static_slide' },
    ['tidehunter'] = { 'tidehunter_kraken_swell', 'tidehunter_sizescale' },
    ['treant'] = { 'treant_primeval_power', 'treant_sapling', 'treant_treant' },
    ['viper'] = { 'viper_poison_burst', 'viper_caustic_bath' },
    ['witch_doctor'] = { 'witch_doctor_headhunter', 'witch_doctor_voodoo_festeration', 'witch_doctor_cleft_death', 'witch_doctor_malpractice' },
}

-- Focus five, in full.
X.FOCUS = {
    ['axe'] = {
        { name = 'axe_one_man_army', deprecated = true, grants = {  } },
        { name = 'axe_call_out', deprecated = true, grants = {  } },
    },
    ['zuus'] = {
        { name = 'zuus_livewire', deprecated = true, grants = {  } },
        { name = 'zuus_divine_rampage', deprecated = true, grants = {  } },
    },
    ['skeleton_king'] = {
        { name = 'skeleton_king_facet_bone_guard', deprecated = true, grants = { 'skeleton_king_bone_guard' } },
        { name = 'skeleton_king_facet_cursed_blade', deprecated = true, grants = { 'skeleton_king_spectral_blade' } },
    },
    ['lion'] = {
        { name = 'lion_essence_eater', deprecated = true, grants = {  } },
        { name = 'lion_fist_of_death', deprecated = true, grants = {  } },
    },
    ['crystal_maiden'] = {
        { name = 'crystal_maiden_frozen_expanse', deprecated = true, grants = {  } },
        { name = 'crystal_maiden_cold_comfort', deprecated = true, grants = {  } },
        { name = 'crystal_maiden_glacial_guard', deprecated = true, grants = {  } },
        { name = 'crystal_maiden_arcane_overflow', deprecated = true, grants = {  } },
    },
}

return X
