-- GENERATED by tools/agent/special_value_key_census.py --snapshot -- do not hand-edit.
--
-- Every key name a GetSpecialValue* call can legally resolve on one of
-- the five focus heroes' abilities, read out of the game's own KV
-- (npc_dota_hero_<name>.txt on the d2vpkr mirror, the same source
-- gen_ability_meta.py uses).  A key NOT in this set answers 0 in game,
-- silently.  tests/test_lion_r_splash_radius_key.lua asserts that no
-- read in the five hero files falls outside it.
--
-- Regenerate after a patch:
--   python3 tools/agent/special_value_key_census.py --snapshot

local X = {}

-- hero unit short name -> set of legal AbilityValues / Ability* keys.
X.KEYS = {
    ['axe'] = {
        ['AbilityCastPoint'] = true, ['AbilityCastRange'] = true, ['AbilityCooldown'] = true,
        ['AbilityDamage'] = true, ['AbilityManaCost'] = true,
        ['AbilityModifierSupportValue'] = true, ['applies_battle_hunger'] = true,
        ['armor_bonus'] = true, ['armor_pct_as_strength'] = true, ['armor_per_stack'] = true,
        ['attacks_increase_counter'] = true, ['bonus_armor'] = true,
        ['bonus_attack_speed'] = true, ['bonus_linger_duration'] = true,
        ['charge_speed'] = true, ['current_max_str_bonus'] = true, ['damage'] = true,
        ['damage_per_second'] = true, ['damage_reduction'] = true, ['debuff_duration'] = true,
        ['duration'] = true, ['helix_lifesteal'] = true, ['max_stacks'] = true,
        ['radius'] = true, ['should_stack'] = true, ['slow'] = true, ['speed_aoe'] = true,
        ['speed_bonus'] = true, ['speed_duration'] = true, ['trigger_attacks'] = true,
    },
    ['zuus'] = {
        ['AbilityCastPoint'] = true, ['AbilityCastRange'] = true,
        ['AbilityChargeRestoreTime'] = true, ['AbilityCharges'] = true,
        ['AbilityCooldown'] = true, ['AbilityManaCost'] = true,
        ['AbilityModifierSupportValue'] = true, ['aoe_radius'] = true, ['arc_damage'] = true,
        ['arc_lightning_damage_illusion_pct'] = true, ['arc_lightning_damage_pct'] = true,
        ['aspd_slow'] = true, ['attack_speed_bonus'] = true, ['cloud_bolt_interval'] = true,
        ['cloud_bounty_tooltip'] = true, ['cloud_duration'] = true, ['cloud_radius'] = true,
        ['creep_damage_bonus_pct'] = true, ['creep_hits_to_kill_tooltip'] = true,
        ['damage'] = true, ['damage_health_pct'] = true, ['duration'] = true,
        ['has_unlimited_jumps'] = true, ['hits_to_kill_tooltip'] = true,
        ['hop_distance'] = true, ['hop_duration'] = true, ['hop_height'] = true,
        ['jump_count'] = true, ['jump_delay'] = true, ['ministun_duration'] = true,
        ['move_slow'] = true, ['radius'] = true, ['range'] = true, ['sight_duration'] = true,
        ['sight_radius_day'] = true, ['sight_radius_night'] = true, ['spread_aoe'] = true,
        ['targets'] = true, ['true_sight_radius'] = true, ['vision_duration'] = true,
        ['vision_radius'] = true,
    },
    ['skeleton_king'] = {
        ['AbilityCastPoint'] = true, ['AbilityCastRange'] = true, ['AbilityCooldown'] = true,
        ['AbilityManaCost'] = true, ['AbilityModifierSupportValue'] = true,
        ['attackslow'] = true, ['blast_dot_damage'] = true, ['blast_dot_duration'] = true,
        ['blast_slow'] = true, ['blast_speed'] = true, ['blast_stun_duration'] = true,
        ['clear_curse'] = true, ['crit_mult'] = true, ['curse_cooldown'] = true,
        ['curse_cooldown_creep'] = true, ['curse_damage_pct'] = true, ['curse_delay'] = true,
        ['cursed_damage'] = true, ['cursed_damage_pct'] = true, ['damage'] = true,
        ['duration'] = true, ['gold_bounty'] = true, ['max_skeleton_charges'] = true,
        ['min_skeleton_spawn'] = true, ['movespeed'] = true, ['reincarnate_time'] = true,
        ['scepter_attack_speed'] = true, ['scepter_aura_radius'] = true,
        ['scepter_move_speed_pct'] = true, ['shard_skeleton_count'] = true,
        ['skeleton_bonus_hero_damage'] = true, ['skeleton_building_damage_reduction'] = true,
        ['skeleton_charges_per_hero_multiplier'] = true, ['skeleton_damage_tooltip'] = true,
        ['skeleton_duration'] = true, ['slow_duration'] = true, ['slow_radius'] = true,
        ['spawn_interval'] = true, ['talent_skeleton_damage'] = true,
        ['trigger_wraithfire_blast'] = true, ['vampiric_aura'] = true,
        ['wraith_cd_mult'] = true, ['xp_bounty'] = true,
    },
    ['lion'] = {
        ['AbilityCastPoint'] = true, ['AbilityCastRange'] = true, ['AbilityChannelTime'] = true,
        ['AbilityCooldown'] = true, ['AbilityManaCost'] = true,
        ['AbilityModifierSupportValue'] = true, ['ally_pct'] = true, ['break_distance'] = true,
        ['cleave_damage'] = true, ['cleave_distance'] = true, ['cleave_ending_width'] = true,
        ['cleave_starting_width'] = true, ['cone_shaped'] = true, ['damage'] = true,
        ['damage_delay'] = true, ['damage_pct'] = true, ['damage_per_kill'] = true,
        ['damage_window'] = true, ['debuff_amp'] = true, ['duration'] = true,
        ['grace_period'] = true, ['length_buffer'] = true, ['magic_resist'] = true,
        ['mana_per_second'] = true, ['movespeed'] = true,
        ['movespeed_bonus_when_empty_pct'] = true, ['pierces_immunity'] = true,
        ['punch_attack_range'] = true, ['punch_bonus_damage_base'] = true,
        ['punch_bonus_movespeed'] = true, ['punch_duration'] = true, ['radius'] = true,
        ['shard_bonus_targets'] = true, ['speed'] = true, ['spell_amp'] = true,
        ['splash_radius'] = true, ['tick_interval'] = true, ['width'] = true,
    },
    ['crystal_maiden'] = {
        ['AbilityCastPoint'] = true, ['AbilityCastRange'] = true, ['AbilityChannelTime'] = true,
        ['AbilityCooldown'] = true, ['AbilityDuration'] = true, ['AbilityManaCost'] = true,
        ['AbilityModifierSupportValue'] = true, ['anim_delay'] = true, ['aoe_bonus'] = true,
        ['attack_slow'] = true, ['attackspeed_slow'] = true, ['barrier_duration'] = true,
        ['base_mana_regen'] = true, ['can_move'] = true, ['clone_duration'] = true,
        ['clone_health'] = true, ['creep_multiplier'] = true, ['damage'] = true,
        ['damage_per_second'] = true, ['duration'] = true, ['explosion_interval'] = true,
        ['explosion_max_dist'] = true, ['explosion_min_dist'] = true,
        ['explosion_radius'] = true, ['frostbite_delay'] = true, ['frostbite_radius'] = true,
        ['hop_distance'] = true, ['hop_duration'] = true, ['mana_multiplier'] = true,
        ['mana_regen_amp'] = true, ['movespeed_slow'] = true, ['nova_damage'] = true,
        ['path_radius'] = true, ['physical_barrier_amount'] = true,
        ['physical_barrier_duration'] = true, ['physical_barrier_self_amount'] = true,
        ['proximity_bonus_factor'] = true, ['proximity_bonus_radius'] = true,
        ['proximity_mana_regen_tooltip'] = true, ['radius'] = true,
        ['self_cast_range_bonus'] = true, ['shard_bonus_explosion'] = true,
        ['shard_self_movement_speed_slow_pct'] = true, ['slow'] = true,
        ['slow_duration'] = true, ['speed'] = true, ['tick_interval'] = true,
        ['vision_duration'] = true,
    },
}

return X
