-- GENERATED by tools/agent/talent_name_binding_census.py --snapshot -- do not hand-edit.
--
-- Every place a hero file binds a talent by LITERAL NAME, and whether
-- the game still gives that hero a talent by that name.  Slot order and
-- membership are read out of npc_heroes.txt (the contiguous run of
-- "AbilityN" "special_bonus_*" entries) -- the same source GH #214
-- moved the talent census to after odota's display list was measured a
-- patch behind.
--
-- `present = false` is a PROOF that bot:GetAbilityByName answers nil in
-- game.  `present = true` proves only non-nil; what the talent actually
-- modifies is `mods`, and an empty `mods` proves nothing (generic rows
-- live in npc_abilities.txt, which the census does not read).
--
-- Regenerate after a patch:
--   python3 tools/agent/talent_name_binding_census.py --snapshot

local X = {}

X.SITES = {
    {
        file = 'bots/BotLib/hero_ancient_apparition.lua',
        hero = 'ancient_apparition',
        var = 'ColdFeetAoETalent',
        talent = 'special_bonus_unique_ancient_apparition_7',
        present = true,
        slot = 1,
        mods = {
            'ancient_apparition_chilling_touch/attack_range_bonus = +300',
        },
    },
    {
        file = 'bots/BotLib/hero_dawnbreaker.lua',
        hero = 'dawnbreaker',
        var = 'CelestialHammerCastRangeTalent',
        talent = 'special_bonus_unique_dawnbreaker_celestial_hammer_cast_range',
        present = true,
        slot = 8,
        mods = {
            'dawnbreaker_celestial_hammer/projectile_speed = +80%',
            'dawnbreaker_celestial_hammer/range = +80%',
        },
    },
    {
        file = 'bots/BotLib/hero_doom_bringer.lua',
        hero = 'doom_bringer',
        var = 'DevourAncientTalent',
        talent = 'special_bonus_unique_doom_2',
        present = false,
        slot = 0,
        mods = {},
    },
    {
        file = 'bots/BotLib/hero_earth_spirit.lua',
        hero = 'earth_spirit',
        var = 'GripAllies',
        talent = 'special_bonus_unique_earth_spirit_2',
        present = true,
        slot = 7,
        mods = {
            'earth_spirit_magnetize/magnetize_self = 1',
        },
    },
    {
        file = 'bots/BotLib/hero_enigma.lua',
        hero = 'enigma',
        var = 'MaleficeAdditionalInstanceTalent',
        talent = 'special_bonus_unique_enigma_2',
        present = true,
        slot = 7,
        mods = {
            'enigma_malefice/stun_instances = +4',
        },
    },
    {
        file = 'bots/BotLib/hero_enigma.lua',
        hero = 'enigma',
        var = 'MidnightPulseRadiusTalent',
        talent = 'special_bonus_unique_enigma_6',
        present = true,
        slot = 2,
        mods = {
            'enigma_black_hole/damage = +50',
        },
    },
    {
        file = 'bots/BotLib/hero_rubick.lua',
        hero = 'rubick',
        var = 'nTalent8',
        talent = 'special_bonus_unique_rubick_8',
        present = true,
        slot = 6,
        mods = {
            'rubick_telekinesis/landing_damage = 300',
        },
    },
    {
        file = 'bots/BotLib/hero_silencer.lua',
        hero = 'silencer',
        var = 'talent20Left',
        talent = 'special_bonus_unique_silencer_4',
        present = true,
        slot = 6,
        mods = {
            'silencer_last_word/radius = +250',
        },
    },
}

return X
