-- GENERATED by tools/agent/talent_slot_census.py --snapshot -- do not hand-edit.
--
-- What `sTalentList[N]` resolves to for each focus hero, and what that
-- talent modifies in the game's own hero KV.  Slot order is READ OUT of
-- npc_heroes.txt (the contiguous run of "AbilityN" "special_bonus_*"
-- entries, N being the same slot bot:GetAbilityInSlot indexes), so
-- 1 = t10 left, 2 = t10 right, ... 8 = t25 right -- the order
-- aba_skill.X.GetTalentList builds its list in.  Until 2026-08-26 this
-- came from odota's display list instead, which was a patch behind on
-- Wraith King's slot 4 (GH #214).
--
-- `mods` is a PROOF of what the talent changes (it is an override key
-- inside that ability's AbilityValues block).  An EMPTY `mods` proves
-- nothing: generic rows and facet rows live in npc_abilities.txt,
-- which the census does not read.
--
-- Regenerate after a patch:
--   python3 tools/agent/talent_slot_census.py --snapshot

local X = {}

-- hero unit short name -> { [slot] = { name = ..., mods = { ... } } }
X.SLOTS = {
    ['axe'] = {
        [1] = { name = 'special_bonus_unique_axe_culling_blade_speed_duration', mods = {
            'axe_culling_blade/speed_duration = +3',
        } },
        [2] = { name = 'special_bonus_unique_axe_8', mods = {
            'axe_battle_hunger/speed_bonus = +8',
        } },
        [3] = { name = 'special_bonus_unique_axe', mods = {
            'axe_battle_hunger/damage_per_second = +8',
        } },
        [4] = { name = 'special_bonus_unique_axe_7', mods = {
            'axe_berserkers_call/bonus_armor = +10',
        } },
        [5] = { name = 'special_bonus_strength_15', mods = {
        } },
        [6] = { name = 'special_bonus_unique_axe_4', mods = {
            'axe_counter_helix/damage = +40',
        } },
        [7] = { name = 'special_bonus_unique_axe_2', mods = {
            'axe_berserkers_call/radius = +85',
        } },
        [8] = { name = 'special_bonus_unique_axe_5', mods = {
            'axe_culling_blade/damage = +150',
        } },
    },
    ['zuus'] = {
        [1] = { name = 'special_bonus_unique_zeus', mods = {
            'zuus_heavenly_jump/targets = +1',
        } },
        [2] = { name = 'special_bonus_hp_200', mods = {
        } },
        [3] = { name = 'special_bonus_unique_zeus_4', mods = {
            'zuus_thundergods_wrath/damage = +75',
        } },
        [4] = { name = 'special_bonus_unique_zeus_6', mods = {
            'zuus_arc_lightning/AbilityCooldown = -20%',
            'zuus_arc_lightning/AbilityManaCost = -20%',
        } },
        [5] = { name = 'special_bonus_unique_zeus_2', mods = {
            'zuus_arc_lightning/arc_damage = +60',
        } },
        [6] = { name = 'special_bonus_unique_zeus_3', mods = {
            'zuus_lightning_bolt/ministun_duration = +0.5',
        } },
        [7] = { name = 'special_bonus_unique_zeus_5', mods = {
            'zuus_lightning_bolt/aoe_radius = 325',
        } },
        [8] = { name = 'special_bonus_unique_zeus_jump_charges', mods = {
            'zuus_heavenly_jump/AbilityCharges = +3',
        } },
    },
    ['skeleton_king'] = {
        [1] = { name = 'special_bonus_unique_wraith_king_2', mods = {
            'skeleton_king_vampiric_spirit/vampiric_aura = +8',
        } },
        [2] = { name = 'special_bonus_unique_wraith_king_facet_1', mods = {
            'skeleton_king_hellfire_blast/blast_dot_duration = +2',
            'skeleton_king_spectral_blade/cursed_damage_pct = +15',
        } },
        [3] = { name = 'special_bonus_unique_wraith_king_11', mods = {
            'skeleton_king_hellfire_blast/blast_stun_duration = +0.75',
        } },
        [4] = { name = 'special_bonus_hp_300', mods = {
        } },
        [5] = { name = 'special_bonus_attack_speed_50', mods = {
        } },
        [6] = { name = 'special_bonus_unique_wraith_king_facet_3', mods = {
            'skeleton_king_bone_guard/min_skeleton_spawn = +5',
            'skeleton_king_spectral_blade/curse_cooldown = -25%',
            'skeleton_king_spectral_blade/curse_cooldown_creep = -25%',
        } },
        [7] = { name = 'special_bonus_unique_wraith_king_10', mods = {
            'skeleton_king_mortal_strike/AbilityCooldown = -2',
        } },
        [8] = { name = 'special_bonus_unique_wraith_king_4', mods = {
            'skeleton_king_reincarnation/trigger_wraithfire_blast = =1',
        } },
    },
    ['lion'] = {
        [1] = { name = 'special_bonus_unique_lion_6', mods = {
            'lion_mana_drain/movespeed = +10',
        } },
        [2] = { name = 'special_bonus_movement_speed_20', mods = {
        } },
        [3] = { name = 'special_bonus_unique_lion_5', mods = {
            'lion_voodoo/AbilityCooldown = -2.0',
        } },
        [4] = { name = 'special_bonus_unique_lion_11', mods = {
            'lion_to_hell_and_back/debuff_amp = +15',
            'lion_to_hell_and_back/spell_amp = +15',
        } },
        [5] = { name = 'special_bonus_unique_lion_8', mods = {
            'lion_finger_of_death/damage_per_kill = +20',
        } },
        [6] = { name = 'special_bonus_unique_lion_10', mods = {
            'lion_impale/cone_shaped = +1',
        } },
        [7] = { name = 'special_bonus_unique_lion_4', mods = {
            'lion_voodoo/radius = +250',
        } },
        [8] = { name = 'special_bonus_unique_lion_2', mods = {
            'lion_impale/AbilityCastRange = +600',
        } },
    },
    ['crystal_maiden'] = {
        [1] = { name = 'special_bonus_hp_200', mods = {
        } },
        [2] = { name = 'special_bonus_intelligence_12', mods = {
        } },
        [3] = { name = 'special_bonus_unique_crystal_maiden_frostbite_castrange', mods = {
            'crystal_maiden_frostbite/AbilityCastRange = +100',
        } },
        [4] = { name = 'special_bonus_unique_crystal_maiden_5', mods = {
            'crystal_maiden_crystal_nova/AbilityCooldown = -4.5',
        } },
        [5] = { name = 'special_bonus_unique_crystal_maiden_glacial_guard_mana_multiplier', mods = {
            'crystal_maiden_glacial_guard/mana_multiplier = +20',
        } },
        [6] = { name = 'special_bonus_unique_crystal_maiden_3', mods = {
            'crystal_maiden_freezing_field/damage = +50',
        } },
        [7] = { name = 'special_bonus_unique_crystal_maiden_1', mods = {
            'crystal_maiden_frostbite/duration = +1.0',
        } },
        [8] = { name = 'special_bonus_unique_crystal_maiden_2', mods = {
            'crystal_maiden_crystal_nova/nova_damage = +300',
        } },
    },
}

return X
