--- GENERATED by tools/agent/talent_value_read_census.py -- do not hand-edit.
---
--- Every live `talentN:GetSpecialValue*('value')` call site in bots/BotLib,
--- with the talent that sTalentList[N] names (npc_heroes.txt order) and
--- whether that talent owns a KV block that could answer 'value'.
---
--- UNIQUE-READS-ZERO      the talent has no KV block at all; the read is 0.
---                        Its bonus lives as a `special_bonus_*` sub-key inside
---                        the ability it modifies, which is where the engine
---                        folds it -- so the base read already carries it and
---                        repointing this term would DOUBLE-COUNT.
--- GENERIC-READS-A-NUMBER the talent owns a block with `value`; the read is real
---                        (and belongs to no ability, so adding it to an ability
---                        quantity is a category error worth a second look).
---
--- This is a CONSISTENCY ratchet, not a correctness one: it goes red when the
--- shipped call sites and this table stop agreeing.  Correctness is owned by the
--- source -- rerun the census against the live KV to move the table.

return {
    roster = { talents = 974, with_own_kv_block = 65 },
    sites = {
        { hero = 'axe', file = 'bots/BotLib/hero_axe.lua', line = 376, var = 'talent7', slot = 7, talent = 'special_bonus_unique_axe_2', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'axe', file = 'bots/BotLib/hero_axe.lua', line = 830, var = 'talent8', slot = 8, talent = 'special_bonus_unique_axe_5', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'bane', file = 'bots/BotLib/hero_bane.lua', line = 221, var = 'talent7', slot = 7, talent = 'special_bonus_unique_bane_2', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'bounty_hunter', file = 'bots/BotLib/hero_bounty_hunter.lua', line = 258, var = 'talent3', slot = 3, talent = 'special_bonus_unique_bounty_hunter_9', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'dazzle', file = 'bots/BotLib/hero_dazzle.lua', line = 389, var = 'talent6', slot = 6, talent = 'special_bonus_unique_dazzle_3', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'lich', file = 'bots/BotLib/hero_lich.lua', line = 321, var = 'talent2', slot = 2, talent = 'special_bonus_unique_lich_6', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'lich', file = 'bots/BotLib/hero_lich.lua', line = 957, var = 'talent5', slot = 5, talent = 'special_bonus_unique_lich_4', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'lina', file = 'bots/BotLib/hero_lina.lua', line = 250, var = 'talent4', slot = 4, talent = 'special_bonus_unique_lina_3', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'lion', file = 'bots/BotLib/hero_lion.lua', line = 1213, var = 'talent5', slot = 5, talent = 'special_bonus_unique_lion_8', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'luna', file = 'bots/BotLib/hero_luna.lua', line = 103, var = 'talent6', slot = 6, talent = 'special_bonus_unique_luna_lunar_orbit_speed_damage', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'nevermore', file = 'bots/BotLib/hero_nevermore.lua', line = 391, var = 'talent4', slot = 4, talent = 'special_bonus_unique_nevermore_frenzy_max_collection_count', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'ogre_magi', file = 'bots/BotLib/hero_ogre_magi.lua', line = 246, var = 'talent8', slot = 8, talent = 'special_bonus_unique_ogre_magi_multicast_chance', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'omniknight', file = 'bots/BotLib/hero_omniknight.lua', line = 278, var = 'talent7', slot = 7, talent = 'special_bonus_unique_omniknight_1', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'phantom_lancer', file = 'bots/BotLib/hero_phantom_lancer.lua', line = 171, var = 'talent5', slot = 5, talent = 'special_bonus_unique_phantom_lancer_lance_damage', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'pugna', file = 'bots/BotLib/hero_pugna.lua', line = 250, var = 'talent7', slot = 7, talent = 'special_bonus_unique_pugna_2', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'riki', file = 'bots/BotLib/hero_riki.lua', line = 243, var = 'talent8', slot = 8, talent = 'special_bonus_unique_riki_9', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'riki', file = 'bots/BotLib/hero_riki.lua', line = 347, var = 'talent6', slot = 6, talent = 'special_bonus_unique_riki_5', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'riki', file = 'bots/BotLib/hero_riki.lua', line = 356, var = 'talent5', slot = 5, talent = 'special_bonus_unique_riki_1', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'shadow_shaman', file = 'bots/BotLib/hero_shadow_shaman.lua', line = 184, var = 'talent7', slot = 7, talent = 'special_bonus_unique_shadow_shaman_3', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'tidehunter', file = 'bots/BotLib/hero_tidehunter.lua', line = 387, var = 'talent3', slot = 3, talent = 'special_bonus_unique_tidehunter_2', verdict = 'UNIQUE-READS-ZERO' },
        { hero = 'zuus', file = 'bots/BotLib/hero_zuus.lua', line = 975, var = 'talent5', slot = 5, talent = 'special_bonus_unique_zeus_2', verdict = 'UNIQUE-READS-ZERO' },
    },
}
